### ISSUE TITLE
Feature Request: add `domains` fastly_service_v1

### ISSUE THREAD

**Issue by brycefisher** [fastly/terraform-provider-fastly#103]
### Feature: Add new property `domains` to resource `fastly_service_v1`

**Use case**: at my current job, our team is trying to create reusable modules for use inside other team**s terraform configuration. We don't know ahead of time how many `domain` blocks should inside a `fastly_service_v1`. As a result, we've written separate module for a `fastly_service_v1` with 1 domain, 2 domains, 3 domains, etc. When we try to update the code, we have to change each of these different modules leading to the possibility of copypasta errors and a small amount of tedious work.

**Proposal:** Add a new property `domains` to `fastly_service_v1`. The value would be a list of maps with `name` and optionally `comment`. This would allow arbitrary numbers of domains to be associated with a fastly_service inside a separate module.

**Current Syntax:**

```hcl
resource "fastly_service_v1" "bryce" {
  ..

  domain {
       name = "bryce.rocks",
       comment = "Bryce's rock-n-roll domain"
    }

  domain {
       name = "bryce.pizza"
    }
}
```

**New Syntax:**

```hcl
resource "fastly_service_v1" "bryce" {
  ..

  domains = [
    {
       name = "bryce.rocks",
       comment = "Bryce's rock-n-roll domain"
    },
    {
       name = "bryce.pizza"
    },
  ]
}
```

The main idea however is that a separate variable would contain this list rather writing the list inline.

This should be functionally equivalent to current syntax. One advantage is that this syntax is fully compatible with the existing syntax -- it should be purely additive syntactic sugar. It shouldn't require lots of new complex logic, if I'm thinking about this correctly

**Open Questions:**
 - Can you mix and match `domain` and `domains` within a single `fastly_service_v1` resource? Possibly no.

If you're willing to accept a PR for something along these lines, I might be able to work on the implementation but would likely need some coaching.

**Comment by maciejdudzinski** [comment]
@brycefisher doesn't new terraform version with updated syntax solve that issue?

**Comment by brycefisher** [comment]
I'm not up to speed on the new syntax; that would be great! Are you
referring to 0.12 release?

**Comment by maciejdudzinski** [comment]
@brycefisher Yes, check Dynamic Nested Blocks here https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each

**Comment by brycefisher** [comment]
Yes! Let's close out this issue in favor of the new syntax. Is it possible
to start using version 0.12 today?

**Comment by maciejdudzinski** [comment]
It's in beta, so it's possible, but again it's in beta and I don't know how stable it is.
