### ISSUE TITLE
Importing changes from fastly, unecessary diff

### ISSUE THREAD

**Issue by marcb1** [fastly/terraform-provider-fastly#105]
I ran terraform import, to import our fastly config into `terraform.tfstate`, and I started working on writing the `*.tf` files. I want to recreate the config so I can run `terraform plan` and no diff will be generated. I hit this weird issue. We have this one VCL:

This is taken directly from `terraform.tfstate`:
```
                            "vcl.1292465265.content": "sub sitemaps_miss {\n    if (req.url ~ \"^/sitemap/\" \u0026\u0026 req.backend == F_Sitemaps__google_cloud_storage_) {\n        set bereq.http.host = \"test-sitemaps.storage.googleapis.com\";\n        set bereq.url = regsub(req.url, \"^/sitemap\", \"\");\n    }\n}\n",
                            "vcl.1292465265.main": "false",
                            "vcl.1292465265.name": "sitemaps.vcl",
 
```

I have copied the above as-is from the terraform state file into the `.tf` file, like so:
```
 vcl {
    "main"    = "false"
    "name"    = "sitemaps.vcl"
    "content" = "sub sitemaps_miss {\n    if (req.url ~ \"^/sitemap/\" && req.backend == F_Sitemaps__google_cloud_storage_) {\n        set bereq.http.host = \"test-sitemaps.storage.googleapis.com\";\n        set bereq.url = regsub(req.url, \"^/sitemap\", \"\");\n    }\n}\n"
  }
```

The weird part, is that this still generates a diff when I run `terraform plan`:

```
Terraform will perform the following actions:

  ~ fastly_service_v1.test
      vcl.#:                  "4" => "1"
      vcl.1292465265.content: "sub sitemaps_miss {\n    if (req.url ~ \"^/sitemap/\" && req.backend == F_Sitemaps__google_cloud_storage_) {\n        set bereq.http.host = \"test-sitemaps.storage.googleapis.com\";\n        set bereq.url = regsub(req.url, \"^/sitemap\", \"\");\n    }\n}\n" => "1217c1394086c3c4c0fd93a384ba9c056d02a924"
      vcl.1292465265.main:    "false" => "false"
      vcl.1292465265.name:    "sitemaps.vcl" => "sitemaps.vcl"
```

I don't understand why there is a UUID for the vcl's content `1217c1394086c3c4c0fd93a384ba9c056d02a924`, I also get the same issue when i try to move the vcl to a separate file and read it through terraform's `file` function.

**Comment by kmotrebski** [comment]
I think it may be connected or duplicate of the issue added few days ago: https://github.com/terraform-providers/terraform-provider-fastly/issues/104 ?
(edited: fixed issue ID)

**Comment by marcb1** [comment]
Yeah, this is related. I'll close this ticket.
