### ISSUE TITLE
`No known usage` on API token console

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#108]
I am trying to play around this terraform provider, but I noticed that there is no API usage report with the following simple example:

```
provider "fastly" {
  version = "~> 0.4"
}

data "fastly_ip_ranges" "fastly" {}

output "cidr_blocks" {
  value = "${data.fastly_ip_ranges.fastly.cidr_blocks}"
}
```

Here are some version info:
```
$ terraform version
Terraform v0.11.10
+ provider.fastly v0.4.0
```

Thanks for making this tf provider!

**Comment by smaeda-ks** [comment]
https://developer.fastly.com/reference/api/utils/public-ip-list/

the endpoint has no authentication and anyone can hit that without a token.

That said, we now have `no_auth` provider option available:
https://registry.terraform.io/providers/fastly/fastly/latest/docs/data-sources/ip_ranges

Closing this issue.
