### ISSUE TITLE
Incorrect default values for format and format_version

### ISSUE THREAD

**Issue by philippschulte** [fastly/terraform-provider-fastly#114]
Hi there,

The default values for `format` and `format_version` are incorrect. The [Fastly API Documentation](https://docs.fastly.com/api/logging) has recently been updated to indicate the correct default value for `format_version`. [All new logging endpoints use the version 2 custom log format by default.](https://docs.fastly.com/guides/streaming-logs/custom-log-formats)

### Terraform Version

```
Terraform v0.11.11
+ provider.fastly v0.4.0
```

### Affected Resource(s)

All logging providers (exept `syslog`) for the `format` field and the following providers for the `format_version` field:

- s3logging
- sumologic
- syslog
- logentries

### Terraform Configuration Files

The `format_version` field is supported by each logging provider and it has the same values and purpose. However, this client currently only supports the `format_version` field for: `s3logging`, `sumologic`, `syslog`, and `logentries`. The field is not required and it defaults to `1`.

The `format` field is also supported by each logging provider. The field is not required and it defaults to `%h %l %u %t %r %>s`.

Below is an example `s3logging` configuration which doesn't specify the `format` and `format_version` fields so that it will use the incorrect default values for both fields:

```
s3logging {
  name = "test"
  bucket_name = "my_bucket"
  s3_access_key = "kldfsjalkdsfjasldkfjadslkfjasdlkfjasdklf"
  s3_secret_key = "alsdkfjadlskfjadlskfjasdlkfjasdlkfjasdlkfjaslkdfjasld"
}
```

### Debug Output

NA

### Panic Output

NA

### Expected Behavior

The default for the `format_version` field should be `2` instead of `1`. The default for the `format` field should be `%h %l %u %t \"%r\" %>s %b` instead of `%h %l %u %t %r %>s`. This applies to all logging providers.

### Actual Behavior

The default value for `format_version` is set to `1` and the default value for `format` is set to `%h %l %u %t %r %>s`.

Here is an example configuration for `s3logging`:

```
s3logging {
  name = "test"
  bucket_name = "my_bucket"
  s3_access_key = "kldfsjalkdsfjasldkfjadslkfjasdlkfjasdklf"
  s3_secret_key = "alsdkfjadlskfjadlskfjasdlkfjasdlkfjasdlkfjaslkdfjasld"
}
```

Which defaults to `format_version` = `"1"`  and to `format` = `"%h %l %u %t %r %>s"` and therefore to [Version 1 log format](https://docs.fastly.com/guides/streaming-logs/custom-log-formats#version-1-log-format):

```
Terraform will perform the following actions:

  ~ fastly_service_v1.nyt
      s3logging.#:                             "0" => "1"
      s3logging.3732549606.bucket_name:        "" => "my_bucket"
      s3logging.3732549606.domain:             "" => "s3.amazonaws.com"
      s3logging.3732549606.format:             "" => "%h %l %u %t %r %>s"
      s3logging.3732549606.format_version:     "" => "1"
      s3logging.3732549606.gzip_level:         "" => "0"
      s3logging.3732549606.message_type:       "" => "classic"
      s3logging.3732549606.name:               "" => "test"
      s3logging.3732549606.path:               "" => ""
      s3logging.3732549606.period:             "" => "3600"
      s3logging.3732549606.placement:          "" => ""
      s3logging.3732549606.redundancy:         "" => ""
      s3logging.3732549606.response_condition: "" => ""
      s3logging.3732549606.s3_access_key:      <sensitive> => <sensitive> (attribute changed)
      s3logging.3732549606.s3_secret_key:      <sensitive> => <sensitive> (attribute changed)
      s3logging.3732549606.timestamp_format:   "" => "%Y-%m-%dT%H:%M:%S.000"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

You just need to configure a logging endpoint without specifying the `format_version` and `format` fields.

### Important Factoids

NA

### References

None

**Comment by Integralist** [comment]
I believe this has been resolved as of Terraform provider `v1.0.0`:
https://registry.terraform.io/providers/fastly/fastly/latest/docs/guides/1.0.0
