### ISSUE TITLE
Migrate codebase to use Go Modules 

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#124]
### Description
Go 1.11 has introduced [Go modules](https://github.com/golang/go/wiki/Modules), which looks like the official solution for dependency management going forward.

### References
terraform-providers/terraform-provider-aws#5773
https://github.com/golang/go/wiki/Modules

**Comment by philippschulte** [comment]
Related issue: [#125](https://github.com/terraform-providers/terraform-provider-fastly/issues/125)

This issue can be closed because the switch to `Go Modules` has been made via [#128](https://github.com/terraform-providers/terraform-provider-fastly/pull/128).
