### ISSUE TITLE
Feature request: Add comment to Version

### ISSUE THREAD

**Issue by wosc** [fastly/terraform-provider-fastly#126]
Configuration versions support a `comment` field, that is e.g. displayed in the Fastly Manage UI, and can also be [set via the API](https://docs.fastly.com/api/config#api-section-version), if I understand it correctly. It would be helpful if one could set this trough terraform, so one could e.g. stuff the relevant git commit messages in there.

**Comment by mpriscella** [comment]
Seconding this request, it would be incredibly helpful to be able to describe what changes were made to a service for documentation's sake and also in case one needs to rollback using the UI.

**Comment by smaeda-ks** [comment]
This is now supported (the `version_comment` attribute).

Closing.
