### ISSUE TITLE
Feature request: Use TypeLists instead of TypeSets for backends, conditions, headers, domains etc.

### ISSUE THREAD

**Issue by JiriKovar** [fastly/terraform-provider-fastly#127]
Hi there. 

We hit a current limitation due to using typesets. 

### Scenario
We use Terraform to manage our environments in Azure & Fastly. We have 3 environments (DEV, QA, PROD), that are different in aspect of number of data centers as there is no reason to have DEV & QA in that many regions. 80%+ of our Fastly settings are static in a sense that for example all backends have the same timeouts, ports, certificates, etc. and only small portion is different for each of them. 

### Desired solutions
We would like to create a module that would receive only the differentiating values through input variables (lists of maps) and the static parts would be filled in by the module, thus allowing the definition to be more data driven instead of being hardcoded. That would allow us for example changing number of backends between environments by merely adding the necessary data to inputs instead of modifying the definitions. It would also simplify the definition greatly as we would not need to repeat the static parts.

### Current situations
Each part of fastly_service_v1 must be explicitly defined including all common values and their numbers are defined by the number of definitions in the code. That leads to lengthy, repetitive definitions that are harder to maintain, extend and its impossible to share them (via modules) in case that the numbers of definition parts varies. 

### Proposed solution
Using TypeList instead of TypeSets allows for data driven approach and therefor is perfect fit. The only downside might be that in simple scenarios, they might be a bit less readable compared to type sets. Also it might require a breaking change when dropping the TypeSets in some of the future versions.

Anyway, thanks for your great work on this provider as we are glad we can manage Azure and Fastly through the same technology.

**Comment by JiriKovar** [comment]
I think this issue was addressed by the new terraform versions. Thank you very much!

**Comment by Integralist** [comment]
Thanks @JiriKovar for coming back and closing this issue! 🙂 ❤️
