### ISSUE TITLE
Setting custom director's quorum to 0% sets it to 75%

### ISSUE THREAD

**Issue by drastawi** [fastly/terraform-provider-fastly#129]
The custom director fails to set quorum to 0%, and does not print any warning or throw an error.

### Terraform Version
0.11.11

### Affected Resource(s)
- director

### Terraform Configuration Files
```hcl
  director {
    name = "director"
    backends = [ "${compact(data.null_data_source.non_zero_weight_backends.*.outputs.name)}"]
    quorum = 0
  }
```

### Expected Behavior
The resulting Fastly varnish file should be:

```vcl
director director random {
   .quorum =0%;
   .retries = 5;
   {
    .backend = my_backend;
    .weight  = 1;
   }
}
```
or throw an error.

### Actual Behavior

The resulting Fastly varnish file is:
```vcl
director director random {
   .quorum =75%;
   .retries = 5;
   {
    .backend = my_backend;
    .weight  = 1;
   }
}
```
and prints a succes message

### Steps to Reproduce
`terraform apply`

### References

Similar issue to #109

**Comment by philippschulte** [comment]
👋 thanks for opening this issue! I can confirm the behavior and this is definitely a bug. However, this is not an issue of the Terraform provider it is actually a bug of the [go-fastly](https://github.com/fastly/go-fastly) HTTP client. We'll work on a solution for this issue. Thanks

**Comment by smaeda-ks** [comment]
should be fixed in https://github.com/fastly/terraform-provider-fastly/pull/511
