### ISSUE TITLE
Better visual way to show the VCL config plan

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#142]
Right now the VCL content string is diff via [`sha1.Sum([]byte(v.(string)))`](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/fastly/resource_fastly_service_v1.go#L1242), I wonder if there is better way to reflect the change more visually.

**Comment by philippschulte** [comment]
I'll close this one out in favor of #140.

**Comment by chenrui333** [comment]
Sounds good with me, glad somebody also raised this issue. 😄
