### ISSUE TITLE
Since 0.7.0 PREFETCH is no longer accepted as a condition type

### ISSUE THREAD

**Issue by jwadolowski** [fastly/terraform-provider-fastly#171]
### Terraform Version

```
$ terraform -v
Terraform v0.11.14
```

### Affected Resource(s)

`fastly_service_v1`

### Terraform Configuration Files

```hcl
resource "fastly_service_v1" "stg" {
  # ...

  condition {
    name      = "WAF_Prefetch"
    priority  = "10"
    statement = "req.backend.is_origin && !req.http.bypasswaf"
    type      = "PREFETCH"
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Condition should be created as it used to be on `0.6.1` version of Terraform provider.

### Actual Behavior

```
$ terraform apply

Error: fastly_service_v1.stg: expected condition.0.type to be one of [REQUEST RESPONSE CACHE], got PREFETCH
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It used to work just fine on `0.6.1`, but the problem surfaced as soon as we upgraded to `0.7.0`. 

Provider downgrade fixes the issue:

```hcl
provider "fastly" {
  api_key = "${var.whatever_fastly_api_key}"
  version = "~> 0.6.1"
}
```

### References

N/A

**Comment by philippschulte** [comment]
👋 I am sorry that the new release isn't working for you. Our source of truth is the Fastly API documentation and the `PREFETCH` type value isn't documented in the [condtion](https://docs.fastly.com/api/config#api-section-condition) docs. I'll add `PREFETCH` as a valid type. This will go out with the next release. I am sorry for the inconvenience.

**Comment by jwadolowski** [comment]
Thanks for your prompt reply @philippschulte. 

Lack of `PREFETCH` in the docs may come from the fact that Fastly's WAF can be managed via Terraform only up to some extent. You can define just some scaffolding, but things like ruleset management is not yet available.

`PREFETCH` is special in a way that it puts given condition into `vcl_miss` and `vcl_pass` at once. Naming convention of that particular condition also matters from WAF perspective, as it translates into the following VCL code (I didn't define `call waf` anywhere):

```vcl
sub vcl_miss {
  # <custom code>

  #--FASTLY MISS BEGIN
  # Prefetch Condition: WAF_Prefetch Prio: 10
  if( req.backend.is_origin && !req.http.bypasswaf ) {
      call waf;
  }
  # end condition

  # <the rest of "#FASTLY miss" macro>

  #--FASTLY MISS END

  # <custom code>
}

sub vcl_pass {
  # <custom code>

  #--FASTLY PASS BEGIN
  # Prefetch Condition: WAF_Prefetch Prio: 10
  if( req.backend.is_origin && !req.http.bypasswaf ) {
      call waf;
  }
  # end condition

  # <the rest of "#FASTLY pass" macro>

  #--FASTLY PASS END

  # <custom code>
}
```

Docs update would be great too.

**Comment by jwadolowski** [comment]
Just upgraded to `0.8.0`, but I'm still having the same problem:

```
$ terraform init -backend-config="profile=whatever" -upgrade

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "fastly" (0.8.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.fastly: version = "~> 0.8"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ terraform plan

Error: fastly_service_v1.stg: expected condition.0.type to be one of [REQUEST RESPONSE CACHE], got PREFETCH
```

As far as I can see the [last relevant commit](https://github.com/terraform-providers/terraform-provider-fastly/commit/07e8823a3bac6abaa642da33dc4fe7196eeb2e3e) to `master` branch removes `PREFETCH` support. Was this intentional?

**Comment by philippschulte** [comment]
@jwadolowski I am sorry for the confusion! I had to revert #172 because we wanted the update of the new SDK `v0.12` to be a stand-alone release. I'll create a new PR to support the `PREFETCH` type this week. We'll cut a new release `v0.8.1` early next week.
