### ISSUE TITLE
Support Terraform version 0.12

### ISSUE THREAD

**Issue by bkero** [fastly/terraform-provider-fastly#175]
### Terraform Version

Terraform v0.11.14

### Affected Resource(s)

All released versions of terraform-provider-fastly

### Terraform Configuration Files
```hcl
resource "fastly_service_v1" "my_fastly_service" {
  name = "${var.domain}"
  backend = "${var.backend}"
  domain {
    name = "${var.domain}"
  }
}
```

### Debug Output

```
$ terraform 0.12checklist
After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

- [ ] Upgrade provider "fastly" to a version that is compatible with Terraform 0.12.

  No compatible version is available for automatic installation at this time. If this provider is still supported (not archived) then a compatible release should be available soon. For more information, check for 0.12 compatibility tasks in the provider's issue tracker.```
```

### Expected Behavior
`terraform 0.12checklist` should pass with no error

### Actual Behavior
0.12 upgrade check fails with aforementioned error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Install terraform 0.11.14
2. Run `terraform 0.12checklist`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
- https://www.terraform.io/upgrade-guides/0-12.html
- https://www.terraform.io/docs/commands/0.12upgrade.html

**Comment by philippschulte** [comment]
👋I don't see an error in the output! The Fastly provider isn't compatibility for Terraform v0.12 yet. The good news is that we already requested a new release `v0.8.0` which includes only a Terraform SDK upgrade with compatibility for Terraform v0.12. It would be great if you could run the command again after `v0.8.0` has been released. I am hoping this will happen today.

**Comment by bkero** [comment]
I'd be glad to help try this after it is released. Thank you!

**Comment by jean-smaug** [comment]
`v0.8` has been released. 
It works now 🎉

**Comment by philippschulte** [comment]
@bkero can you please confirm?

**Comment by nagibyro** [comment]
Not the original poster but I used the above example locally with placeholder values. `terraform 0.12checklist` with terraform `0.11.14` and it passed. No errors.

**Comment by philippschulte** [comment]
@jean-smaug, @Nilithus, @bkero thanks for testing `terraform 0.12checklist` against our provider!
