### ISSUE TITLE
Always invalidates and recreates backends

### ISSUE THREAD

**Issue by querry43** [fastly/terraform-provider-fastly#179]
Terraform is updating the backends of two fastly services every time it is run.  This behavior changed when upgrading from Terraform 0.11.14 to 0.12.3 and from the fastly provider version 0.5 to 0.8.  Additionally, I use terraform workspaces for different environments (dev, prod, etc) and this only happens in some workspaces.

```
      - backend {
          - address               = "my.address" -> null
          - auto_loadbalance      = false -> null
          - between_bytes_timeout = 10000 -> null
          - connect_timeout       = 10000 -> null
          - error_threshold       = 0 -> null
          - first_byte_timeout    = 50000 -> null
          - max_conn              = 500 -> null
          - name                  = "django-frontend" -> null
          - port                  = 443 -> null
          - ssl_cert_hostname     = "my-hostname" -> null
          - ssl_check_cert        = true -> null
          - use_ssl               = true -> null
          - weight                = 100 -> null
        }
      + backend {
          + address               = "my.address"
          + auto_loadbalance      = false
          + between_bytes_timeout = 10000
          + connect_timeout       = 10000
          + error_threshold       = 0
          + first_byte_timeout    = 50000
          + max_conn              = 500
          + name                  = "django-frontend"
          + port                  = 443
          + ssl_cert_hostname     = "my-hostname"
          + ssl_check_cert        = true
          + use_ssl               = true
          + weight                = 100
        }
```

### Terraform Version
```
Terraform v0.12.3
+ provider.aws v2.17.0
+ provider.fastly v0.8.0
+ provider.template v2.1.2
```

### Affected Resource(s)
- fastly_service_v1

### Expected Behavior
The fastly service should not change.

### Actual Behavior
The fastly service is being updated every apply.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

**Comment by querry43** [comment]
I am not sure how to securely share configs and trace output (~300k lines).  If there are useful snippets, I can sanitize and post here.

**Comment by querry43** [comment]
I think this could be related to ssl parameters.  Here is a complete backend config block after a few changes from my initial configuration.  In this case, the port is 80 so all ssl parameters should be false or null.

```
  backend {
    name = "java-backend-primary"

    address = var.java_backend_addresses[0]
    port    = var.java_backend_port

    healthcheck        = "Backend Healthcheck"
    max_conn           = 400
    connect_timeout    = 15000
    first_byte_timeout = 50000
    auto_loadbalance   = false

    use_ssl           = var.java_backend_port == 443
    ssl_cert_hostname = var.java_backend_port == 443 ? module.dns_zones.external_zone_names[0] : null
    ssl_check_cert    = var.java_backend_port == 443
  }
```

I now see this as a diff.  Note, ssl_check_cert is getting toggled for some reason.

```
      + backend {
          + address               = "some-address"
          + auto_loadbalance      = false
          + between_bytes_timeout = 10000
          + connect_timeout       = 15000
          + error_threshold       = 0
          + first_byte_timeout    = 50000
          + max_conn              = 400
          + name                  = "java-backend-failover"
          + port                  = 80
          + ssl_check_cert        = false
          + use_ssl               = false
          + weight                = 100
        }
      - backend {
          - address               = "some-address" -> null
          - auto_loadbalance      = false -> null
          - between_bytes_timeout = 10000 -> null
          - connect_timeout       = 15000 -> null
          - error_threshold       = 0 -> null
          - first_byte_timeout    = 50000 -> null
          - max_conn              = 400 -> null
          - name                  = "java-backend-failover" -> null
          - port                  = 80 -> null
          - ssl_check_cert        = true -> null
          - use_ssl               = false -> null
          - weight                = 100 -> null
        }
```

**Comment by querry43** [comment]
I found the issue.  It was two-fold:

1. ssl_cert_hostname was getting set even when ssl wasn't used
2. ssl_check_cert is apparently always true and should not be present in the backend config

I don't know why this is a problem now when it wasn't before but it does explain why a subset of workspaces are impacted as it varies between http and https.

There are perhaps two usability improvements which would have made this easier:
1. Remove and/or ignore the ssl_check_cert parameter if it cannot be set to false.
2. If a subset of providers need to be changed, only update that subset.  One of my services has three backends and only two are susceptible to this problem, however, I was attempting to debug with the third backend which was a red herring.

**Comment by yanjunding** [comment]
If use_ssl is enabled, you can set ssl_check_cert as either value.
If use_ssl is disabled, please leave ssl_check_cert enabled (true) or remove it. As its default Vale is true.
You can try it at fastly 'configure host' page, when use_ssl selected, the ssl_check_cert is disabled, means you cannot select any Value.

**Comment by yanjunding** [comment]
I have no idea it's terraform doing any logic or at fastly side.
But follow above rules, working totally fine

**Comment by ziggythehamster** [comment]
I'm experiencing this too, on an older Terraform version, and I am also computing `ssl_cert_hostname` (and the other SSL stuff). Here's my backend block:

```
  backend {
    address           = "${var.foo["origin_domain"]}"
    name              = "foo-${var.environment}-bar"
    port              = "${lookup(var.foo, "origin_ssl_cert_hostname", "") == "" ? 80 : 443}"
    use_ssl           = "${lookup(var.foo, "origin_ssl_cert_hostname", "") == "" ? false : true}"
    ssl_ca_cert       = "${lookup(var.foo, "origin_ssl_cert_trust_chain", "")}"
    ssl_cert_hostname = "${lookup(var.foo, "origin_ssl_cert_hostname", "")}"
    shield            = "sjc-ca-us"
  }
```

What appears to change according to Terraform is actually `ssl_client_cert` and `ssl_client_key`, which I've not configured

**Comment by ziggythehamster** [comment]
Simplifying it to this still doesn't work:

```hcl
  backend {
    address           = "${var.xxx["origin_domain"]}"
    name              = "xxx-${var.environment}-xxx"
    port              = 443
    shield            = "sjc-ca-us"
    ssl_ca_cert       = "${var.xxx["origin_ssl_cert_trust_chain"]}"
    ssl_cert_hostname = "${var.xxx["origin_ssl_cert_hostname"]}"
    ssl_check_cert    = true
    ssl_sni_hostname  = "${var.xxx["origin_ssl_cert_hostname"]}"
    use_ssl           = true
  }
```

**Comment by ziggythehamster** [comment]
`${var.xxx["origin_ssl_cert_hostname"]}` in my case was being passed into this module as `${module.foo.bar}`. This causes this behavior. If instead I provide it to the submodule as a string literal, e.g., `my.host.name`, I no longer see these changes. Something is likely broken with the way that the Fastly provider handles computed values being passed in here.

**Comment by ziggythehamster** [comment]
Even more background: It appears that any computed thing being passed into the `backend` block does this. If I pass something that's the result of a resource/data source into any of `ssl_sni_hostname`, `ssl_cert_hostname`, or `ssl_ca_cert`, the problem comes up (those are the ones I tried).

**Comment by xsalazar** [comment]
Just to add my findings here:
- @sbfaulkner seems to have identified a separate _real_ issue where one backend will reapply all backends within the resource
- If the `address` within the `backend` has a "https://" prefix, the `backend` will always reapply as the Fastly API strips this prefix off. Effectively, Terraform will say apply "https://google.com" and Fastly says it has "google.com", so it will always want to rewrite it. This also triggers the above bug where now that one `backend` has changed, ALL other backends will reapply.
- If you pass in an `ssl_cert_hostname` to a `backend` with `use_ssl = false`, this will also cause the resource to reapply since Fastly does not store the `ssl_cert_hostname` if `use_ssl = false`. So Terraform will always try to write an `ssl_cert_hostname` and Fastly will always say it doesn't have a value for that, so it will always to rewrite it. This also triggers the above bug where now that one `backend` has changed, ALL other backends will reapply.

As far as I can tell, the URL prefix issue and the `ssl_cert_hostname` issue are all coming from _within_ the [Fastly API](https://docs.fastly.com/api/config#api-section-backend) itself. Neither this provider code nor the [Fastly Go API](https://github.com/fastly/go-fastly) are doing any logic to cause this.

**Comment by tibbon** [comment]
I'm seeing similar happen.

**Comment by tibbon** [comment]
Here's what I'm seeing (slightly redacted):

```
  # fastly_service_v1.staging will be updated in-place
  ~ resource "fastly_service_v1" "staging" {
        activate       = true
        active_version = 111
        cloned_version = 111
        comment        = "Managed by Terraform"
        default_ttl    = 3600
        id             = "service-id"
        name           = "staging"

      - backend {
          - address               = "my-service.s3.amazonaws.com" -> null
          - auto_loadbalance      = false -> null
          - between_bytes_timeout = 10000 -> null
          - connect_timeout       = 1000 -> null
          - error_threshold       = 0 -> null
          - first_byte_timeout    = 15000 -> null
          - max_conn              = 200 -> null
          - name                  = "my-service" -> null
          - port                  = 80 -> null
          - ssl_check_cert        = false -> null
          - use_ssl               = false -> null
          - weight                = 100 -> null
        }
      + backend {
          + address               = "my-service.s3.amazonaws.com"
          + auto_loadbalance      = false
          + between_bytes_timeout = 10000
          + connect_timeout       = 1000
          + error_threshold       = 0
          + first_byte_timeout    = 15000
          + max_conn              = 200
          + name                  = "my-service"
          + port                  = 80
          + ssl_check_cert        = false
          + use_ssl               = false
          + weight                = 100
        }

(many more backends continue like this)
```

**Comment by mihai-cindea** [comment]
I also had the problem, and simply removing `use_ssl = false` fixed it.

**Comment by smaeda-ks** [comment]
I believe this is no longer the case with the most recent provider version. Closing this for now.
