### ISSUE TITLE
Developing WAF resource

### ISSUE THREAD

**Issue by KeisukeYamashita** [fastly/terraform-provider-fastly#193]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

* Is there any WAF related resources? And also, if there someone developing this, please let me know. 
* I am currently developing the WAF resource

### Terraform Version

```terminal
$ terraform -v
Terraform v0.11.8
```

### Affected Resource(s)
Please list the resources as a list, for example:
- None

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

My plan is to create a resource something like this.

```hcl
resource "fastly_waf" xxx {
     ...
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

* Feature to create WAF related resources.(WAF, Rules, etc)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by KeisukeYamashita** [comment]
Got feedback from fastly team. Thank you.

**Comment by chenrui333** [comment]
@KeisukeYamashita 👋 what is the feedback on this issue? Just curious. Thanks!
