### ISSUE TITLE
Feature Request: support sensitive VCL snippet which is hidden in plan result

### ISSUE THREAD

**Issue by cookie-s** [fastly/terraform-provider-fastly#195]
Fastly provides [a guide](https://docs.fastly.com/en/guides/amazon-s3) that injects secret keys into VCL snippet to use Amazon S3 private bucket as origin.
When managing this kind of VCL snippet by terraform, I wouldn't like at least `awsSecretKey` in the guide to be visible in `terraform plan` result.
Therefore, I'd like `snippet` block in `fastly_service_v1` to support an argument like [`sensitive_content` in `local_file` resource](https://www.terraform.io/docs/providers/local/r/file.html#sensitive_content).

### Terraform Version
```
$ terraform -v
Terraform v0.12.8
```

### Affected Resource(s)
- fastly_service_v1

### Terraform Configuration Files
```hcl
resource "fastly_service_v1" "myservice" {
  name = "myawesometestservice"

  snippet {
    name = "myawesomesnippet"
    type = "recv"
    sensitive_content = "some sensitive vcl snippet"
  }
}
```

### Expected Behavior
```
$ terraform plan
...
      + snippet {
          + sensitive_content    = (sensitive value)
          + name     = "myawesomesnippet"
          + priority = 100
          + type     = "recv"
        }
...
```

**Comment by philippschulte** [comment]
The solution is to use a [write-only dictionary](https://www.terraform.io/docs/providers/fastly/r/service_v1.html#write_only) for your secrets which you can then reference in your snippet.
