### ISSUE TITLE
Feature Request: Support tls_client_cert and tls_client_key for syslog

### ISSUE THREAD

**Issue by laramackey** [fastly/terraform-provider-fastly#202]
The Fastly API supports creating a syslog endpoint with mutual tls by specifying a client cert and key. https://docs.fastly.com/api/logging#api-section-logging_syslog

These fields haven't been implemented in `terraform-provider-fastly`, and therefore it is not currently possible to deploy syslog with mutual tls through terraform.

**Comment by eheydrick** [comment]
Think this can be closed now that #203 is out in 0.12.0?
