### ISSUE TITLE
Acceptance tests fail because of hardcoded domain name

### ISSUE THREAD

**Issue by msuterski** [fastly/terraform-provider-fastly#21]
The acceptance tests in the latest master (2ea108d47244cd150cff8ab6cdfd2c73aabc3154) are failing due to domain collision in Fastly. It happens probably when the test suite is run by multiple people at the same time.

```
--- FAIL: TestAccFastlyServiceV1_VCL_basic (6.69s)
	testing.go:428: Step 0 error: Error applying: 1 error(s) occurred:

		* fastly_service_v1.foo: 1 error(s) occurred:

		* fastly_service_v1.foo: 400 - Bad Request
		Message: Bad request
		Detail: Domain 'notadomain.com' is already taken by another customer
=== RUN   TestValidateLoggingFormatVersion
--- PASS: TestValidateLoggingFormatVersion (0.00s)
=== RUN   TestValidateLoggingMessageType
--- PASS: TestValidateLoggingMessageType (0.00s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-fastly/fastly	247.298s
make: *** [testacc] Error 1
```

### Terraform Version
Tests were run on the Fastly provider repo. Not sure which version of terraform the tests pulled in.

### Expected Behavior
Tests should pass

### Actual Behavior
TestAccFastlyServiceV1_VCL_basic test case failed

### Steps to Reproduce
1. `make testacc`

**Comment by grubernaut** [comment]
Fixed via #22, thanks!
