### ISSUE TITLE
`Invalid template control keyword` issue for s3logging

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#210]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

v0.12.20

### Affected Resource(s)
Please list the resources as a list, for example:
- s3logging

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
  s3logging {
    name             = "s3-waf-logging"
    bucket_name      = "com.meetup.logging.fastly"
    domain           = "s3.amazonaws.com"

    s3_access_key    = var.s3_access_key
    s3_secret_key    = var.s3_secret_key

    path             = "/www.meetup.com/waf/date=%Y-%m-%d/"
    period           = 600
    format           = "{\\\"type\\\":\\\"waf\\\",\\\"request_id\\\":\\\"%{req.http.fastly-soc-x-request-id}V\\\",\\\"rule_id\\\":\\\"%{waf.rule_id}V\\\",\\\"severity\\\":\\\"%{waf.severity}V\\\",\\\"anomaly_score\\\":\\\"%{waf.anomaly_score}V\\\",\\\"logdata\\\":\\\"%{json.escape(waf.logdata)}V\\\",\\\"waf_message\\\":\\\"%{waf.message}V\\\"}"
    format_version   = 2
    gzip_level       = 0
    message_type     = "blank"

    placement        = "waf_debug"
    redundancy       = "standard"
    timestamp_format = "%Y-%m-%dT%H:%M:%S.000"
  }
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

```
$ tf plan -no-color

Error: Invalid template control keyword

  on www-meetup-com-config.tf line 528, in resource "fastly_service_v1" "www_meetup_com":
 528:     format           = "{\\\"type\\\":\\\"waf\\\",\\\"request_id\\\":\\\"%{req.http.fastly-soc-x-request-id}V\\\",\\\"rule_id\\\":\\\"%{waf.rule_id}V\\\",\\\"severity\\\":\\\"%{waf.severity}V\\\",\\\"anomaly_score\\\":\\\"%{waf.anomaly_score}V\\\",\\\"logdata\\\":\\\"%{json.escape(waf.logdata)}V\\\",\\\"waf_message\\\":\\\"%{waf.message}V\\\"}"

"req" is not a valid template control keyword.
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

terraform plan should work properly.

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by philippschulte** [comment]
@chenrui333 this is not an issue of the Fastly provider.

"In both quoted and heredoc string expressions, Terraform supports template sequences that begin with `${` and `%{`."

"To include these sequences literally without beginning a template sequence, double the leading character: `$${` or `%%{`."

Please have a look at the [docs](https://www.terraform.io/docs/configuration/expressions.html#string-literals) for more details.

**Comment by chenrui333** [comment]
Thank you for the quick insight!! Much appreciated!
