### ISSUE TITLE
Feature Request: Google Cloud Pub/Sub Logging Endpoint

### ISSUE THREAD

**Issue by nullobject** [fastly/terraform-provider-fastly#218]
Fastly has enabled their [Google Cloud Pub/Sub logging endpoint](https://docs.fastly.com/en/guides/log-streaming-google-cloud-pubsub).

It seems very similar to the other GCP endpoints, so hopefully it's not too difficult to add pub/sub support to the Fastly provider too.

![](https://docs.fastly.com/img/guides/create-new-pubsub-endpoint.png)

**Comment by phamann** [comment]
Hi @nullobject thank you for the report and feature request. We are currently evaluating the work to update/add all of our logging providers to the provider which will include pub/sub. I will update this issue once the work commences.

**Comment by mccurdyc** [comment]
Hello @nullobject!

Google Cloud Pub/Sub logging endpoint support is included in the `v0.17.0` release of the provider.

For more details on the release, please refer to [the Changelog](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/CHANGELOG.md#0170-june-22-2020).

Kind Regards,

Colton
