### ISSUE TITLE
Feature Request: Elasticsearch Logging Endpoint

### ISSUE THREAD

**Issue by ashi-agrawal** [fastly/terraform-provider-fastly#224]
Fastly has the option to create an Elasticsearch logging endpoint in their console, but this option is unavailable in the provider. It would be great to support this in the provider as well.

**Comment by phamann** [comment]
Hi @ashi-agrawal thank you for the report and feature request. We are currently evaluating the work to update/add all of our logging providers to the provider which will include Elasticsearch. I will update this issue once the work commences.

**Comment by ashi-agrawal** [comment]
Thank you!

**Comment by ezkl** [comment]
@ashi-agrawal #234 has been opened to address this request.

**Comment by ashi-agrawal** [comment]
Thank you for the update!

**Comment by mccurdyc** [comment]
Hello @ashi-agrawal  !

Elasticsearch logging endpoint support is included in the `v0.17.0` release of the provider.

For more details on the release, please refer to [the Changelog](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/CHANGELOG.md#0170-june-22-2020).

Kind Regards,

Colton
