### ISSUE TITLE
s3_logging block rewritten every apply due to server_side_encryption parameter 

### ISSUE THREAD

**Issue by cparmar** [fastly/terraform-provider-fastly#225]
Support for the server_side_encryption parameter for the s3logging configuration was recently added to the terraform provider (FYI the documentation needs updating https://www.terraform.io/docs/providers/fastly/r/service_v1.html#s3logging)

The s3_logging block is re-written every time `terraform apply` is ran.

### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
  dynamic s3logging {
    for_each = var.s3_logging
    content {
      bucket_name            = s3logging.value.fastly_logs_bucket
      domain                 = "s3-eu-west-1.amazonaws.com"
      gzip_level             = 5
      format_version         = 2
      name                   = "s3_logging"
      format                 = "%%{HOST}i:%p %h %l %u %t \"%r\" %>s %b \"%%{Referer}i\" \"%%{User-Agent}i\""
      s3_access_key          = s3logging.value.fastly_logs_key
      s3_secret_key          = s3logging.value.fastly_logs_secret
      server_side_encryption = "AES256"
    }
  }

```
### Expected Behavior
s3_logging block is not 

### Actual Behavior
```
      - s3logging {
          - bucket_name      = "<redacted>" -> null
          - domain           = "s3-eu-west-1.amazonaws.com" -> null
          - format           = "%{HOST}i:%p %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" -> null
          - format_version   = 2 -> null
          - gzip_level       = 5 -> null
          - message_type     = "classic" -> null
          - name             = "s3_logging" -> null
          - period           = 3600 -> null
          - s3_access_key    = (sensitive value)
          - s3_secret_key    = (sensitive value)
          - timestamp_format = "%Y-%m-%dT%H:%M:%S.000" -> null
        }
      + s3logging {
          + bucket_name            = "<redacted>"
          + domain                 = "s3-eu-west-1.amazonaws.com"
          + format                 = "%{HOST}i:%p %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""
          + format_version         = 2
          + gzip_level             = 5
          + message_type           = "classic"
          + name                   = "s3_logging"
          + period                 = 3600
          + s3_access_key          = (sensitive value)
          + s3_secret_key          = (sensitive value)
          + server_side_encryption = "AES256"
          + timestamp_format       = "%Y-%m-%dT%H:%M:%S.000"
        }
```

As you can see above, it's removing server_side_encryption and then re-adding it back in.

**Comment by phamann** [comment]
@cparmar Thank you for the report. Can you confirm a couple of things for me before I try to create a reduced reproduction test case.

1) In your output above, the diff is showing that the previous state didn't have the `server_side_encryption` property and it is adding it, this suggests to me this is the first time you are running apply after adding the property, which is the correct behaviour and would cause the resource to be recreated. Can you confirm once that is has been applied a subsequent run is causing the same diff output?

2) Another common issue with loggingendpoints that causes this behaviour is the raw value of your secrets (for instance access key and secret_key) contain whitespace, which is subsequently stripped by the Fastly API and therefore causes the value in the statefile to always be different from your input.

**Comment by cparmar** [comment]
@phamann thank you for the prompt response.

1. This parameter was added last week and we have run the terraform code with the parameter present dozens- every time our pipeline runs, it removes and re-adds the server_side_encryption parameter back in. 

2. I have just checked a pipeline run prior to adding the SSE parameter, and it seems it was removing and adding the s3logging block, everytime then as well:
```
       - s3logging {
           - bucket_name      = "<redacted>" -> null
           - domain           = "s3.eu-west-1.amazonaws.com" -> null
           - format           = "%h %l %u %t %r %>s" -> null
           - format_version   = 1 -> null
           - gzip_level       = 5 -> null
           - message_type     = "classic" -> null
           - name             = "s3_logging" -> null
           - period           = 3600 -> null
           - s3_access_key    = (sensitive value)
           - s3_secret_key    = (sensitive value)
           - timestamp_format = "%Y-%m-%dT%H:%M:%S.000" -> null
         }
       + s3logging {
           + bucket_name      = "<redacted>"
           + domain           = "s3.eu-west-1.amazonaws.com"
           + format           = "%h %l %u %t %r %>s"
           + format_version   = 1
           + gzip_level       = 5
           + message_type     = "classic"
           + name             = "s3_logging"
           + period           = 3600
           + s3_access_key    = (sensitive value)
           + s3_secret_key    = (sensitive value)
           + timestamp_format = "%Y-%m-%dT%H:%M:%S.000"
         }
```

So I think there are 2 problems here:
1. SSE parameter removed and re-added
2. s3logging block removed and re-added due to the access/secret keys

But there is definitely no whitespace in the credentials as we're generating them using terraform:
```
fastly_logs_key    = aws_iam_access_key.fastly_logs_key.id
fastly_logs_secret = aws_iam_access_key.fastly_logs_key.secret
```

**Comment by phamann** [comment]
@cparmar Thanks for checking and confirming with me that this was happening before the SSE change. Having dug further into the issue I can now see this is because the field wasn't added to a mapping the provider uses to persist the response to the state, which can be found [here](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/fastly/resource_fastly_service_v1.go#L4059-L4092), this means the `server_side_encryption` field is never written into state and therefore will trigger a difference on every apply. I will make sure this gets fixed and report back here once released.

**Comment by cparmar** [comment]
Great, thanks!

The terraform docs needs updating to include the new parameters for SSE as well (https://www.terraform.io/docs/providers/fastly/r/service_v1.html#s3logging) - I don't know who administrates these.

I think we may still be having issues with the access/secret keys though - there should be no whitespace in them.

**Comment by cparmar** [comment]
@phamann when can we expect a fix for this?

**Comment by cparmar** [comment]
I've created the above PR to fix this.

**Comment by cparmar** [comment]
Thanks, @phamann! I can confirm the fix worked and we now have expected behavior:
```
No changes. Infrastructure is up-to-date.
```
