### ISSUE TITLE
Feature Request: Newrelic Logs Logging Endpoint

### ISSUE THREAD

**Issue by bashou** [fastly/terraform-provider-fastly#226]
Hi,

Fastly has the option to create an Newrelic Logs logging endpoint in their console, but this option is unavailable in the provider. It would be great to support this in the provider as well.

https://docs.fastly.com/en/guides/log-streaming-newrelic-logs

Thanks a lot

**Comment by phamann** [comment]
Hi @bashou thank you for the report and feature request. We are currently evaluating the work to update/add all of our logging providers to the provider which will include newrelic logs. I will update this issue once the work commences.

**Comment by ezkl** [comment]
@bashou We've opened #243 to address this request.

**Comment by bashou** [comment]
thanks !

**Comment by mccurdyc** [comment]
Hello @bashou !

New Relic logging endpoint support is included in the `v0.17.0` release of the provider.

For more details on the release, please refer to [the Changelog](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/CHANGELOG.md#0170-june-22-2020).

Kind Regards,

Colton
