### ISSUE TITLE
Fastly Terraform Version 0.12.x Support

### ISSUE THREAD

**Issue by UNC1739** [fastly/terraform-provider-fastly#227]
Would it be possible for the Fastly terraform provider to be updated to support Terraform version 0.12.x? We are facing issues with conflicting dependencies where one Terraform provider only supports 0.10.x (Fastly) and several other providers only support 0.12.x.

**Comment by phamann** [comment]
@praetorian-adam-crosser Thank you for your question. 

The Fastly Provider has in been updated to support, and works successfully with, 0.12.x of Terraform. This work was complete in June 2019 (see PR for further info: https://github.com/terraform-providers/terraform-provider-fastly/pull/173).

Therefore, please can you provide more details and context to any errors you are seeing to come to this conclusion.

**Comment by UNC1739** [comment]
Thanks @phamann. I think you are correct. I saw "0.10.x" on the readme and thought 0.12.x wasn't supported so we couldn't upgrade.
