### ISSUE TITLE
Splunk logging

### ISSUE THREAD

**Issue by karnauskas** [fastly/terraform-provider-fastly#25]
There's no way to configure Splunk logging for Fastly with current fastly provider. Tho this is not GA yet. 
Not sure how to deal with open source project and non GA features here.

**Comment by grubernaut** [comment]
Hey @karnauskas, 

Historically we've held off on implementing beta features within Terraform so as not to incur any breaking changes that the beta API contains. While this is frustrating for some, it allows Terraform to always be reliable in terms of configuration for provider resources. However, if the beta feature is considered stable enough, and doesn't require extra opt-in permissions, it's generally "ok" to add.

**Comment by karnauskas** [comment]
Is there any estimates, priority when this would be implemented? Would we need to wait till feature be GA on Fasly?

**Comment by wonderphil** [comment]
Any updates on when this will be implemented?
