### ISSUE TITLE
missing ACL entries data source

### ISSUE THREAD

**Issue by innovia** [fastly/terraform-provider-fastly#306]
Hi

Is there a reason why data acl entries does not exist? you have the underlying fastly-go code that list the entries but not the data source

I need to get the acls entries and extract the IP address from each for firewall rules

**Comment by phamann** [comment]
Hi @innovia thank you for raising this feature request (and the corresponding PR #312). Before we go any further and accept the change, I'd like to first understand your use-case/need for the data source, as this isn't a request we've heard previously or the "terraform way" of achieving this pattern.

There are two other options which I think may be more flexible than using a datasource:

**1) Native data structures :**
It's more common for users to store their ACL/IP ranges in a native Terraform collection type such as a` list` of `object`s bound to a `local` or `var`. You can then pass this list to the ACL entries resource and any other resources from other providers. 

Such as:
```
locals {
  acl_name = "my_acl"
  acl_entries = [
    {
      ip      = "1.2.3.4"
      comment = "acl_entry_1"
    },
    {
      ip      = "1.2.3.5"
      comment = "acl_entry_2"
    },
    {
      ip      = "1.2.3.6"
      comment = "acl_entry_3"
    }
  ]
}

resource "fastly_service_v1" "myservice" {
  name = "demofastly"

  domain {
    name    = "demo.notexample.com"
    comment = "demo"
  }

  backend {
    address = "1.2.3.4"
    name    = "localhost"
    port    = 80
  }

  acl {
    name = local.acl_name
  }

  force_destroy = true
}

resource "fastly_service_acl_entries_v1" "entries" {
  service_id = fastly_service_v1.myservice.id
  acl_id     = { for d in fastly_service_v1.myservice.acl : d.name => d.acl_id }[local.acl_name]
  dynamic "entry" {
    for_each = [for e in local.acl_entries : {
      ip      = e.ip
      comment = e.comment
    }]

    content {
      ip      = entry.value.ip
      subnet  = 22
      comment = entry.value.comment
      negated = false
    }
  }
}
```

**2) Resource exported output attributes:**
As we already have an ACL entires resource ([`fastly_service_acl_entries_v1`](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_acl_entries_v1)), we can avoid creating a new data source completely by exposing the set of entries as an exported attribute on the resource.

This would allow the following puesdo code:
```
resource "fastly_service_acl_entries_v1" "entries" {
  service_id = fastly_service_v1.myservice.id
  acl_id = {for d in fastly_service_v1.myservice.acl : d.name => d.acl_id}[var.myacl_name]
  entry {
    ip = "127.0.0.1"
    subnet = "24"
    negated = false
    comment = "ALC Entry 1"
  }
}

resource "google_compute_firewall" "default" {
  name    = "test-firewall"
  network = google_compute_network.default.name

  allow {
    protocol = "tcp"
    ports    = ["80"]
  }

  source_ranges = [ 
    for entry in fastly_service_acl_entries_v1.my-entries.entries: entry.ip
  ]

}
```
--- 

I assume you want to read the ACLs defined on a service and pass to another 3rd party resource or share with another Fastly service? Both patterns should be possible (and more flexible in the long term) with the suggested alternatives above. Though am very happy to hear you're needs/ideas here and why you opted for a data source.

Thanks!

**Comment by innovia** [comment]
Hi @phamann 

thanks for taking the time to explain, my use case is that I need to be able to pull the ACLs and their IP address for whitelisting in firewall rules

I understand that If i managed these using the ACL resource it would be the right way, but since this is a separate module that will be using the IP addresses to whitelist on GCP it kinda loopy to get the remote state and query that.

do you think we should be importing and managing the ACLS just via terraform?

**Comment by phamann** [comment]
Ok thinking about your problem some more, are you sure Fastly ACL IPs are actually what you want to provide to your GCP firewall rules? Let's imagine you have the following architecture:

Client -> Fastly -> GCP firewall -> GCP VM

The ACLs on a Fastly service are data-structures scoped to a specific Fastly service that you can use within VCL logic to control inbound access from the `Client` IP ranges. However normally, you'd want the GCP firewall to only allow access to the global IP ranges of `Fastly` edge nodes and not the real client IP ACLs which Fastly is terminating. For this pattern we already have the [`fastly_ip_ranges`](https://registry.terraform.io/providers/fastly/fastly/latest/docs/data-sources/ip_ranges) datasource which customers use to pass to other third party resources such as AWS/GCP/Azure VM firewalls. As an example:

```
data "fastly_ip_ranges" "fastly" {}

resource "aws_security_group" "from_fastly" {
  name = "from_fastly"

  ingress {
    from_port         = "443"
    to_port           = "443"
    protocol          = "tcp"
    cidr_blocks       = ["${data.fastly_ip_ranges.fastly.cidr_blocks}"]
    ipv6_cidr_blocks  = ["${data.fastly_ip_ranges.fastly.ipv6_cidr_blocks}"]
  }
}
```

If i've misunderstood your need and you do in-fact want to share _client_ IP ACLs between Fastly and GCP firewalls, then I suggest you use example 1 "native data-structures" example in my previous post to allow you to manage the list in a single TF location and share the data between two resources.

Hope this makes sense.

**Comment by brionmoss** [comment]
There are two use cases we're trying to solve here.  

The first is admittedly a bit of a specific case -- we use Fastly ACLs as our main source of truth for managing ACL entries for certain environments, and (because of the Fastly API and its integrations) have found them very convenient place for storing ACL information even for use in other systems.

The more general case is that we use this pattern in development for copying Fastly services.  We generate temporary development environments, each of which is fronted by a matching Fastly service.  As part of standing up a new Fastly service for that development environment, we want terraform to be able to say "be just like that existing Fastly service over there" -- including matching the current ACLs.  Having the ability for Terraform to query the current state and configuration of an existing Fastly service in order to build a new matching one has been very convenient for us.

The master set of ACLs on that template environment aren't managed by Terraform -- we have a few different interfaces (jenkins, slack bots) whixh allow people to add entries to the ACL.  Trying to maintain those updates in Terraform as well as in Fastly would be possible but a lot more complicated.

**Comment by innovia** [comment]
@phamann What do you think? I work with Brion on this one.

**Comment by innovia** [comment]
@phamann Im going to leave the company in 2 weeks from now, I would be happy to get this moving before i do

**Comment by phamann** [comment]
@innovia Apologies for the delay in getting back to you on this. I wanted to discuss with some people internally first before responding. 

Thanks to @brionmoss' description we now have a better understanding of the use-cases and your need for a data source. We're slightly uncomfortable that you're essentially using the Fastly API as a general purpose ACL database for other non-Fastly services, and would be even more concerned if you were hitting the API within those applications to get the data as it wasn't designed for these purposes (you'd also most likely get rate-limited). 

However, we do see the value in using this proposed data source to clone/copy data from one (template) Fastly service to another and across environments etc - which admittedly the Fastly API doesn't expose good primitives to do so yet.  So given the above considerations and your use-case, i'm happy for us to go ahead with implementing your data source in #312.

**Comment by Integralist** [comment]
👋🏻 @brionmoss can I just double check whether you still require a data source for ACL entries? Reading back over the various conversations within this issue and the subsequent PR opened, it sounds like the original PR author has since left the company that had requested this feature. I'm happy to open a PR to implement this and to take over from where innovia left off but wanted to be sure the feature was still required. Thanks.

**Comment by Integralist** [comment]
Going to close off this issue as it appears to be stale/inactive. We can reopen it if there's further interest/discussion to be had.
