### ISSUE TITLE
Unable to remove override_host from fastly_service_v1 backend

### ISSUE THREAD

**Issue by thomaspeitz** [fastly/terraform-provider-fastly#323]
Hi fastly team <3

thanks for your awesome product and especially this terraform provider which makes our
vcl life a lot easier.

We think we found a small bug regarding override_host in fastly_service_v1.backend.

### Terraform Version
Terraform v0.13.3

### Affected Resource(s)
- fastly_service_v1 (backend)

### Terraform Configuration Files
First apply the following
```hcl
resource "fastly_service_v1" "debug" {
  name = "debug.test.com"

  domain {
    name    = "debug.test.com.host"
    comment = ""
  }

  backend {
    address       = "backend.test.com"
    name          = "backend"
    override_host = "override.host.test.com"
  }
}
```

Then apply the following. The host override will be not removed.
```hcl
resource "fastly_service_v1" "debug" {
  name = "debug.test.com"

  domain {
    name    = "debug.test.com.host"
    comment = ""
  }

  backend {
    address = "backend.test.com"
    name    = "backend"
  }
}
```

And even this snippet does not remove it:
```hcl
resource "fastly_service_v1" "debug" {
  name = "debug.test.com"

  domain {
    name    = "debug.test.com.host"
    comment = ""
  }

  backend {
    address       = "backend.test.com"
    name          = "backend"
    override_host = ""
  }
}
```

### Expected Behavior
What should have happened? -The host override in the backend should be set to "" again in both cases (second and third terraform run)

### Actual Behavior
What actually happened? - The host override keeps the value override.host.test.com.

Removing manually through user interface works.

Greetings, Thomas :)

**Comment by Integralist** [comment]
Hi @thomaspeitz thanks for opening this issue (and your patience awaiting our feedback).

I believe we now may have a fix in place to resolve the issue you're describing. We merged it this morning as the new minor version `v0.21.3`, here are some details about the changes:

- [Migrate Terraform provider to use latest Go-Fastly 2.0.0 release](https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.21.3).
- [Key changes in Go-Fastly 2.0.0](https://github.com/fastly/terraform-provider-fastly/issues/85) that I think relate to this issue.

If possible, could you try upgrading to the latest version (`v0.21.3`) and let me know if this indeed resolves the issue.

Thanks again Thomas.

**Comment by smaeda-ks** [comment]
Hi @thomaspeitz

We've dug into this further and identified a problem that was on our API backend side. We've deployed the fix yesterday and confirmed this operation now works fine.

Thanks again for your report.
