### ISSUE TITLE
BigQuery logging setting is always created/destroyed every time when applying terraform

### ISSUE THREAD

**Issue by RomTin** [fastly/terraform-provider-fastly#326]
Hi, Fastly team.

Thank you for providing this `terraform-provider-fastly`, and I'm very satisfied with its convenience.
I respect you all :)

I confronted unrecognized behavior like a bug or something else while using this provider.

### Terraform Version

```
%> terraform -v
Terraform v0.12.9

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)
- fastly_service_v1.bigquerylogging

### Terraform Configuration Files
```hcl
resource "fastly_service_v1" "web" {

  ... 

  #*-- Logging: BigQuery --*#
  bigquerylogging {
    project_id = var.project
    name       = "BigQuery Log Endpoint"
    dataset    = "fastly_log"
    table      = "log"
    email      = data.terraform_remote_state.gcp.outputs.fastly-log-streaming-email
    secret_key = jsondecode(base64decode(data.terraform_remote_state.gcp.outputs.fastly-log-streaming-credential))["private_key"]
    format     = file("${path.module}/templates/log_format.json")
  }
  #*------------------------------*#

}
```

### Debug Output

nothing

### Panic Output

nothing

### Expected Behavior

- A Logging setting for GCP BigQuery is created
- Unless the logging setting is modified, the setting persists in existing in the actual VCL configuration which was deployed to Fastly CDN.

### Actual Behavior

- A Logging setting for GCP BigQuery is created
- Although the logging setting was not modified and nothing was shown in the next `terraform plan` command output, that logging setting was deleted in the next deployment.
- After that, I re-ran the command `terraform plan` and `terraform apply` again. Then I found a creation plan for BigQuery logging setting in `plan` output, and the logging setting was created.

Thus it means, "`terraform plan` didn't show any diffs but it actually destroyed BigQuery logging setting.
And in the case of no modifications to BigQuery logging setting, the actual VCL configuration deployed to Fastly always vibrates its behavior "creation" and "destruction" every time running the command `terraform apply`.

### Steps to Reproduce

1. `terraform apply` (BigQuery logging setting was created)
2. `terraform apply` (destroyed)
3. `terraform apply` (created)
... 

### Important Factoids

- Email and credential are loaded from terraform_remote_state of another tfstate organizing GCP resources
- Here's my workaround to resolve this problem that is recreating BigQuery logging setting every time by setting `uuid()` as its name.

```hcl
resource "fastly_service_v1" "web" {

  ... 

  #*-- Logging: BigQuery --*#
  bigquerylogging {
    project_id = var.project
    name       = "BigQuery Log Endpoint-${uuid()}" # this is
    dataset    = "fastly_log"
    table      = "log"
    email      = data.terraform_remote_state.gcp.outputs.fastly-log-streaming-email
    secret_key = jsondecode(base64decode(data.terraform_remote_state.gcp.outputs.fastly-log-streaming-credential))["private_key"]
    format     = file("${path.module}/templates/log_format.json")
  }
  #*------------------------------*#

}
```

**Comment by phamann** [comment]
Hi @RomTin thank you for your detailed issue report. Apologies for the delay in getting back to you.

This issue is normally related to how the `secret_key` value is encoded when being read from an external source. It may contain additional whitespace or more likely double encoded newline escape sequences. It seems this is related to how Terraform encodes strings that it reads from external sources such as via `file()`,  a `data` datasource, or `TF_VAR_` environment variables. We often see the `\n` new line escape sequences within the private key being double encoded as `\\n` which the Fastly API then accepts and sanitises, which causes the circular plan diff.  

Therefore, can you please try our suggested workaround to see if it fixes the issue for you, which is to use `replace()` to fix the newline encoding, such as:

```hcl
resource "fastly_service_v1" "web" {

  ... 

  #*-- Logging: BigQuery --*#
  bigquerylogging {
    project_id = var.project
    name       = "BigQuery Log Endpoint-${uuid()}" # this is
    dataset    = "fastly_log"
    table      = "log"
    email      = data.terraform_remote_state.gcp.outputs.fastly-log-streaming-email
    secret_key = replace(jsondecode(base64decode(data.terraform_remote_state.gcp.outputs.fastly-log-streaming-credential))["private_key"], "\\n", "\n")
    format     = file("${path.module}/templates/log_format.json")
  }
  #*------------------------------*#

}
...
```

**Comment by RomTin** [comment]
Hi @phamann, thank you for replying.

I tried the solution you suggested, but it seemed not to work well. It produced the same result as my first report.
Here's a more detailed process of behavior.

1. add bigquerylogging block to fastly_service_v1
2. terraform plan
3. diff for 'creating bigquerylogging setting' is shown
4. terraform apply
5. bigquerylogging setting is created
6. terraform plan
7. no changes
8. modify another block (something like domain's comment)
9. terraform plan
10. diff for 'recreating domain setting' is shown (**diff for bigquerylogging is not shown**)
11. terraform apply
12. domain setting is recreated, and **bigquerylogging setting is deleted**. 
13. terraform plan
14. diff for 'creating bigquerylogging setting' is shown because the setting was deleted in 12
15. terraform apply
16. bigquerylogging setting is created
17. terraform plan
18. no changes

It seems that fastly-provider comprehend there are no diffs about bigquerylogging setting, but it actually deleted bigquerylogging setting.

**Comment by RomTin** [comment]
Here's reproduction.
I hope it will be helpful 🙏 

## 1. add new service, including bigquery logging setting

it resulted `Version 3 was activated`

```
  +  resource "fastly_service_v1" "test" {
      + activate       = true
      + active_version = 3
      + comment        = "Managed by Terraform"
      + default_ttl    = 3600
      + id             = "..."
      + name           = "MyTestService"

      + backend {
          + address               = "origin.myexamplefortest.com"
          + auto_loadbalance      = false
          + between_bytes_timeout = 10000
          + connect_timeout       = 1000
          + error_threshold       = 0
          + first_byte_timeout    = 15000
          + max_conn              = 200
          + name                  = "origin.myexamplefortest.com"
          + port                  = 443
          + shield                = "tyo-tokyo-jp"
          + ssl_cert_hostname     = "origin.myexamplefortest.com"
          + ssl_check_cert        = true
          + use_ssl               = true
          + weight                = 100
        }

      + bigqueryloging {
          + dataset    = "fastly_log"
          + email      = (sensitive value)
          + format     = "..."
          + name       = "BigQuery Log Endpoint"
          + project_id = "..."
          + secret_key = (sensitive value)
          + table      = "log"
        }

      + domain {
          + comment = "test for creating logging setting"
          + name    = "myexamplefortest.com"
        }
    }

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

## 2. re-run terraform apply with the same source code to confirm there's no changes.

```
No changes. Infrastructure is up-to-date.
```

## 3. change domain setting's comment to update service

Only change for comment is shown in terraform plan, but actually bigquerylogging setting was destroyed.
It resulted `Version 4 was activated` .

```
  # fastly_service_v1.test will be updated in-place
  ~ resource "fastly_service_v1" "test" {
        activate       = true
        active_version = 3
        cloned_version = 3
        comment        = "Managed by Terraform"
        default_ttl    = 3600
        id             = "..."
        name           = "MyTestService"

        backend {
            address               = "origin.myexamplefortest.com"
            auto_loadbalance      = false
            between_bytes_timeout = 10000
            connect_timeout       = 1000
            error_threshold       = 0
            first_byte_timeout    = 15000
            max_conn              = 200
            name                  = "origin.myexamplefortest.com"
            port                  = 443
            shield                = "tyo-tokyo-jp"
            ssl_cert_hostname     = "origin.myexamplefortest.com"
            ssl_check_cert        = true
            use_ssl               = true
            weight                = 100
        }

        bigquerylogging {
            dataset    = "fastly_log"
            email      = (sensitive value)
            format     = "..."
            name       = "BigQuery Log Endpoint"
            project_id = "..."
            secret_key = (sensitive value)
            table      = "log"
        }

      - domain {
          - comment = "test for creating logging setting" -> null
          - name    = "myexamplefortest.com" -> null
        }
      + domain {
          + comment = "test for creating logging setting. update comment."
          + name    = "myexamplefortest.com"
        }
    }
```

## re-run terraform apply with the same source code

There's creating plan for bigquerylogging setting because it was destroyed previous apply.
It resulted `Version 5 was activated`

```
  # fastly_service_v1.test will be updated in-place
  ~ resource "fastly_service_v1" "test" {
        activate       = true
        active_version = 4
        cloned_version = 4
        comment        = "Managed by Terraform"
        default_ttl    = 3600
        id             = "..."
        name           = "MyTestService"

        backend {
            address               = "origin.myexamplefortest.com"
            auto_loadbalance      = false
            between_bytes_timeout = 10000
            connect_timeout       = 1000
            error_threshold       = 0
            first_byte_timeout    = 15000
            max_conn              = 200
            name                  = "origin.myexamplefortest.com"
            port                  = 443
            shield                = "tyo-tokyo-jp"
            ssl_cert_hostname     = "origin.myexamplefortest.com"
            ssl_check_cert        = true
            use_ssl               = true
            weight                = 100
        }

      + bigquerylogging {
          + dataset    = "fastly_log"
          + email      = (sensitive value)
          + format     = "..."
          + name       = "BigQuery Log Endpoint"
          + project_id = "..."
          + secret_key = (sensitive value)
          + table      = "log"
        }

        domain {
            comment = "test for creating logging setting. update comment."
            name    = "myexamplefortest.com"
        }
    }

```

## change logs

![スクリーンショット 2020-10-15 18 11 17](https://user-images.githubusercontent.com/9119338/96103539-cabacd80-0f12-11eb-9a4b-4269a7908e30.png)

**Comment by phamann** [comment]
Thank you for the reduced test case @RomTin this is indeed useful. Can you please let us know the exact version of Terraform and the Fastly provider you are using to reproduce this?

**Comment by RomTin** [comment]
These are.

```
%> terraform -v
Terraform v0.12.9

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from www.terraform.io/downloads.html
```

```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "fastly" (terraform-providers/fastly) 0.20.4...
```

**Comment by RomTin** [comment]
I'm gonna try the latest versions of terraform and fastly provider once. Thanks🙏

**Comment by phamann** [comment]
@RomTin Were you able to test on a newer version of Terraform and the Fastly provider?

I came to look at this issue and noticed that your reproduction above only includes the plan output and not the TF config itself. Are you able to supply us with the config that is causing this issue (with any secrets omitted/redacted) that we are then able to reproduce locally?

**Comment by RomTin** [comment]
I'm very sorry for being late to reply.

I'm in a difficult situation so that I can't upgrade Terraform and Fastly provider easily, so I haven't tried yet.
I'd like to let you know the result of retries with upgraded Terraform and Fastly provider, and give you a full sample of TF config to reproduce this later.

**Comment by RomTin** [comment]
I'm very sorry to be late in my response.
Here are codes for reproduction that work properly, and reproduce the same result of the reported phenomenon.

`main.tf`
```
resource "google_service_account" "fastly-log-streaming" {
  account_id   = "fastly-log-streaming"
  display_name = "fastly-log-streaming"
}

resource "fastly_service_v1" "test" {
  name = "sample-project-bglogging"

  domain {
    name = "bqlogging-test-foobar.com"
  }

  backend {
    name                  = "bqlogging-test-foobar.com"
    address               = "bqlogging-test-foobar.com"
    port                  = 443
    auto_loadbalance      = false
    shield                = "tyo-tokyo-jp"
    ssl_cert_hostname     = "bqlogging-test-foobar.com"
    ssl_check_cert        = true
    use_ssl               = true
    weight                = 100
    between_bytes_timeout = 10000
    first_byte_timeout    = 10000
    connect_timeout       = 5000
    error_threshold       = 3
    max_conn              = 200
  }

  bigquerylogging {
    project_id = var.project
    name       = "BigQuery Log Endpoint"
    dataset    = "fastly_log"
    table      = "log"
    email      = google_service_account.fastly-log-streaming.name
    secret_key = jsondecode(base64decode(google_service_account_key.fastly-log-streaming.private_key))["private_key"]
    format     = file("${path.module}/log_format.json")
  }
}

```

`log_format.json`
```
{
  "timestamp":"%{begin:%Y-%m-%dT%H:%M:%S}t",
  "time_elapsed":%{time.elapsed.usec}V,
  "is_tls":%{if(req.is_ssl, "true", "false")}V,
  "client_ip":"%{req.http.Fastly-Client-IP}V",
  "geo_city":"%{client.geo.city}V",
  "geo_country_code":"%{client.geo.country_code}V",
  "geo_datacenter":"%{server.datacenter}V",
  "request":"%{req.request}V",
  "host":"%{Fastly-Orig-Host}i",
  "url":"%{json.escape(req.url)}V",
  "request_referer":"%{json.escape(req.http.Referer)}V",
  "request_user_agent":"%{json.escape(req.http.User-Agent)}V",
  "request_accept_language":"%{json.escape(req.http.Accept-Language)}V",
  "request_accept_charset":"%{json.escape(req.http.Accept-Charset)}V",
  "request_type":"%{if(req.http.fastly-ff, "shield", "edge")}V",
  "cache_status":"%{regsub(fastly_info.state, "^(HIT-(SYNTH)|(HITPASS|HIT|MISS|PASS|ERROR|PIPE)).*", "\\2\\3") }V",
  "is_ipv6":%{if(req.is_ipv6, "true", "false")}V,
  "tls_version":"%{cstr_escape(tls.client.protocol)}V",
  "http_accept":"%{Accept}i",
  "http_connection":"%{Connection}i",
  "status":"%>s",
  "server_status":"%s",
  "cache_control":"%{Cache-Control}o",
  "cache_age":"%{Age}o",
  "cache_hits":"%{obj.hits}V",
  "cache_etag":"%{ETag}o",
  "response_header_size":"%{resp.header_bytes_written}V",
  "response_body_size":"%{resp.body_bytes_written}V"
}

```

**Comment by RomTin** [comment]
> Were you able to test on a newer version of Terraform and the Fastly provider?

I tested with Terraform v0.14.4 and fastly-provider 0.22.0, but it resulted in the same reproduction.

**Comment by smaeda-ks** [comment]
For those still watching this issue, we've made some changes in v0.33.0 and now return a proper error message if the `secret_key` value includes trailing space characters.

PR: https://github.com/fastly/terraform-provider-fastly/pull/439

We believe this will help users and prevent accidental logging deletion. As a reminder, we encourage you to use the `trimspace()` [function](https://www.terraform.io/docs/language/functions/trimspace.html) for this particular attribute going forward.

We appreciate your feedback. Thanks
