### ISSUE TITLE
Question about submitting documentation fixes

### ISSUE THREAD

**Issue by dbeckham** [fastly/terraform-provider-fastly#33]
While working with this provider, I've noticed a number of documentation issues. I'd like to help contribute by submitting fixes for docs, but I wanted to ask if this project is open to this, and if so, what is the best way to go about doing that? Is it better to submit one large PR, or break changes into multiple PRs that combine similar changes? I ask because PR #19 was quickly tagged documentation, but has been open for several weeks now without any feedback.

Some of the issues I've found:
* primary resource name in sidebar is incorrect (PR #19)
* some incorrectly documented parameters (PR #19 and possibly others)
* inconsistent parameter ordering 
* inconsistent formatting compared to official provider documentation (AWS)
* missing import documentation

**Comment by radeksimko** [comment]
Hi @dbeckham 
sorry for the delay in merging #19 - I just went ahead and merged it.

Regarding your question

> Is it better to submit one large PR, or break changes into multiple PRs that combine similar changes?

Almost always better to break changes into multiple PRs as that makes them much easier to review and less likely to conflict with other PRs (i.e. potential rebase should be easier).

Smaller the PR == higher chance to discover unintended consequences and details of the PR.

Do you mind me closing this issue/question now?

Thanks.

**Comment by dbeckham** [comment]
Sure, I'll break apart the changes, and begin creating PRs for them.  Thank you.
