### ISSUE TITLE
Feature request: HSTS support

### ISSUE THREAD

**Issue by stadskle** [fastly/terraform-provider-fastly#332]
It seems like enabling HSTS is not supported through the terraform provider (at least we are not able to find this in the documentation). Having support for that in terraform is important  so that we can manage the life cycle 100% from terraform.

**Comment by endzyme** [comment]
Any word on if this is in the works Fastly?

**Comment by smaeda-ks** [comment]
merging this to https://github.com/fastly/terraform-provider-fastly/issues/489
