### ISSUE TITLE
Add support for TLS subscriptions

### ISSUE THREAD

**Issue by eheydrick** [fastly/terraform-provider-fastly#334]
This is a feature request to add support for TLS subscriptions. This new resource would allow you to request TLS certs so you don't have to click around the UI to secure your service.

Docs: https://developer.fastly.com/reference/api/tls/subs/

**Comment by smaeda-ks** [comment]
This is now supported: https://www.fastly.com/blog/you-asked-we-delivered-terraform-support-for-tls-is-here

Closing.
