### ISSUE TITLE
format_version is not documented on all logging platforms

### ISSUE THREAD

**Issue by ericmj** [fastly/terraform-provider-fastly#34]

**Comment by catsby** [comment]
Looks like it's missing from `s3logging`. `sumologic` seems to be the only other logging backend that supports it ~~other than [syslog](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/fastly/resource_fastly_service_v1.go#L736-L805) which doesn't seem to be documented at all 😢~~

**Comment by catsby** [comment]
Ah, syslog is documented it's just not released yet

**Comment by philippschulte** [comment]
The `terraform-provider-fastly` currently supports the `format_version` field for:

* [logentries](https://docs.fastly.com/api/logging#api-section-logging_logentries)
* [s3](https://docs.fastly.com/api/logging#api-section-logging_s3)
* [sumologic](https://docs.fastly.com/api/logging#api-section-logging_sumologic)
* [syslog](https://docs.fastly.com/api/logging#api-section-logging_syslog)

The `format_version` field is listed and described in the [docs](https://www.terraform.io/docs/providers/fastly/r/service_v1.html#argument-reference) for all four logging providers. Therefore, I will close this issue.
