### ISSUE TITLE
If a backend has a healthcheck, terraform can't remove it

### ISSUE THREAD

**Issue by liebman** [fastly/terraform-provider-fastly#347]
We have a few services that have no `healthcheck` (and yes, it should have one),  In order to do maintenance we change a `backend`s `healthcheck` to one that purposely fails.  When done we change it back, in this case to `''`.  This  used to work and now does not remove the healthcheck even tho plan and apply show 
```
- healthcheck = "nlb_out_of_service"
```
I've also tried removing the `healthcheck` attribute with the same result. One has to use the Fastly GUI to manually set the `healthcheck` to `None`.

### Terraform Version
Terraform v0.11.14
+ provider.fastly v0.21.1

### Affected Resource(s)
Please list the resources as a list, for example:
- backend

### Terraform Configuration Files
`backend` WITH `healthcheck`
```hcl
  backend {
    address = "backend003.example.com"
    auto_loadbalance = "false"
    between_bytes_timeout = "10000"
    connect_timeout = "1000"
    error_threshold = "0"
    first_byte_timeout = "15000"
    healthcheck = "nlb_out_of_service"
    max_conn = "200"
    max_tls_version = ""
    min_tls_version = ""
    name = "backend003"
    port = "443"
    request_condition = ""
    shield = ""
    ssl_ca_cert = ""
    ssl_cert_hostname = "*.example.com"
    ssl_check_cert = "true"
    ssl_ciphers = ""
    ssl_client_cert = ""
    ssl_client_key = ""
    ssl_sni_hostname = ""
    use_ssl = "true"
    weight = "1"
  }
```

`backend` WITHOUT `healthcheck`
```hcl
  backend {
    address = "backend003.example.com"
    auto_loadbalance = "false"
    between_bytes_timeout = "10000"
    connect_timeout = "1000"
    error_threshold = "0"
    first_byte_timeout = "15000"
    max_conn = "200"
    max_tls_version = ""
    min_tls_version = ""
    name = "backend003"
    port = "443"
    request_condition = ""
    shield = ""
    ssl_ca_cert = ""
    ssl_cert_hostname = "*.example.com"
    ssl_check_cert = "true"
    ssl_ciphers = ""
    ssl_client_cert = ""
    ssl_client_key = ""
    ssl_sni_hostname = ""
    use_ssl = "true"
    weight = "1"
  }
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
`healthcheck` to be set to `None` (in GUI)

### Actual Behavior
`healthcheck` unchanged

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
None

### References
None

**Comment by smaeda-ks** [comment]
This should be fixed in https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.21.3 could you please confirm? Thanks for your report!

**Comment by liebman** [comment]
I won't be able to test this right away.  Not until we do a terraform upgrade.  So I'll close this.  Thanks!
