### ISSUE TITLE
Feature Request - logging_kinesis

### ISSUE THREAD

**Issue by MrTish** [fastly/terraform-provider-fastly#350]
Although currently only limited availability, Fastly support AWS [Kinesis Data Streams](https://docs.fastly.com/en/guides/log-streaming-amazon-kinesis-data-streams) for logging.

We are keen to test this as soon as possible so it would be exceptionally useful if you could add a corresponding `logging_kinesis` argument to the `fastly_service_v1` resource ahead of general release.

**Comment by Integralist** [comment]
👋🏻 @MrTish thanks for opening this issue. 

Speaking with the team responsible it would appear we have this tracked to be worked on. 

Unfortunately I'm unable to confirm any timeline at this point.

**Comment by MerlinDMC** [comment]
I've started working in a fork so we can do some testing without opening the management console 😉 

Would you accept a PR to add the functionality once I've tested the whole thing?

Current work in https://github.com/MerlinDMC/terraform-provider-fastly/compare/master...kinesis-logging

**Comment by Integralist** [comment]
@MerlinDMC we’d happily accept a PR. Thanks!

**Comment by MerlinDMC** [comment]
@Integralist there you go ... #351 we were only able to run the acceptance tests for `fastly_service_v1` as our account does not have access to Compute@Edge 😄 (we would gladly take it and then test things)
