### ISSUE TITLE
Add support for custom TLS certificates

### ISSUE THREAD

**Issue by devblackops** [fastly/terraform-provider-fastly#357]
It would be nice if this provider supported uploading custom certificates and enabling TLS on a domain.

Docs: https://developer.fastly.com/reference/api/tls/custom-certs/

Related: https://github.com/fastly/terraform-provider-fastly/issues/334

**Comment by Integralist** [comment]
Hi @devblackops thanks for opening this issue. 

You'll be pleased to know that we are _actively_ working on supporting our TLS API.

I can't give an exact timeframe for when the work will be complete, but I'll be sure to reach out to let you know.

**Comment by devblackops** [comment]
Thanks @Integralist!

**Comment by chenrui333** [comment]
Any update on this? :)

**Comment by Integralist** [comment]
Hi @chenrui333 - my apologies! We released the initial TLS support in https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.25.0 

I'd recommend using the latest release as there was a couple of updates related to TLS in https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.28.0
