### ISSUE TITLE
cloned_version in output is not reflecting the real state.

### ISSUE THREAD

**Issue by rayzorinc** [fastly/terraform-provider-fastly#358]
Hi,

We usually do not activate immediately thru terraform, and compare the diff with the active and clone version via the fastly console, just in case someone had done some out of workflow changes in prod that wasn't capture in tf yet.  So in the output, we usually generate the fastly diff url to view the changes before activating.  However, the `cloned_version` attribute seems to be off by 1 and not reflecting the recently actual cloned version in our testing.

### Terraform Version
```
terraform -v
Terraform v0.14.4
+ provider registry.terraform.io/fastly/fastly v0.22.0
```

### Affected Resource(s)
- fastly_service_v1
- output

### Terraform Configuration Files

```hcl
resource "fastly_service_v1" "test_service" {
  name = "test service"

  default_ttl = 3600

  domain {
    name    = "debug.test.com"
    comment = ""
  }

  backend {
    address = "backend.test.com"
    name    = "backend"
    port    = 80
  }

  vcl {
    name = "main_vcl"
    content = file("${path.module}/vcls/main.vcl")
    main = true
  }

  # do not automatically activate
  activate = false
}

output "fastly_console_diff_url" {
  description = "The fastly diff url between active version and the clone version"
  value       = "https://manage.fastly.com/configure/services/${fastly_service_v1.test_service.id}/diff/${fastly_service_v1.test_service.active_version},${fastly_service_v1.test_service.cloned_version}"
}
```

### Expected Behavior

After running `terraform apply`, I expected the output to be something like the following where the current active version is 1 and the created clone version should be 2:

```
fastly_service_v1.test_service: Modifying... [id=<FASTLYSERVICEID>]
fastly_service_v1.test_service: Still modifying... [id=<FASTLYSERVICEID>, 10s elapsed]
fastly_service_v1.test_service: Modifications complete after 16s [id=<FASTLYSERVICEID>]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

fastly_console_diff_url = "https://manage.fastly.com/configure/services/<FASTLYSERVICEID>/diff/1,2"
```

### Actual Behavior
Instead for some reason, the output is off by 1.

```
fastly_service_v1.test_service: Modifying... [id=<FASTLYSERVICEID>]
fastly_service_v1.test_service: Still modifying... [id=<FASTLYSERVICEID>, 10s elapsed]
fastly_service_v1.test_service: Modifications complete after 16s [id=<FASTLYSERVICEID>]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

fastly_console_diff_url = "https://manage.fastly.com/configure/services/<FASTLYSERVICEID>/diff/1,1"
```

### Steps to Reproduce
sample assumption: current active version is 1
1.  make some dummy changes to service.
1.  run `terraform apply`

assumption is next clone version is 2, but output u get is:
```
fastly_console_diff_url = "https://manage.fastly.com/configure/services/<FASTLYSERVICEID>/diff/1,1"
```

1. make another dummy change to service.
2. run another `terraform apply`

assumption is the next clone draft version will be 3, but output u get is:
```
fastly_console_diff_url = "https://manage.fastly.com/configure/services/<FASTLYSERVICEID>/diff/1,2"
```

at this point, if you rerun with `terraform plan`, you will see the following output:
```
Changes to Outputs:
~ fastly_console_diff_url = "https://manage.fastly.com/configure/services/<FASTLYSERVICEID>/diff/1,2" -> "https://manage.fastly.com/configure/services/<FASTLYSERVICEID>/diff/1,3"
```
### Important Factoids
If I looked inside the terraform state file, I see the `cloned_version` value is accurate, just that output is off.

The hack right now, is we have to run a `terraform refresh` after apply to get the correct output.

**Comment by Integralist** [comment]
Thanks for your patience on this @rayzorinc. 

I've been investigating this for a while as it initially appeared that our terraform provider was correct and it was the use of terraform's legacy SDK that was causing the issue. But after a deeper investigate it would appear to be an issue with the fastly terraform provider (although at this point it's still unclear what the root cause is).

We have marked this as requiring further investigation, and so for now I would suggest using an appropriate command to refresh the terraform state (e.g. `terraform plan` or `terraform refresh`).

**Comment by Integralist** [comment]
This should now be fixed by https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.33.0
