### ISSUE TITLE
state out of sync when there's a draft version created after the active version

### ISSUE THREAD

**Issue by tmountjr** [fastly/terraform-provider-fastly#369]
### Terraform Version
```
$ terraform -v
Terraform v0.14.6
+ provider registry.terraform.io/fastly/fastly v0.24.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

### Terraform Configuration Files
```hcl
resource "fastly_service_v1" "bug_report" {
    # active_version = 1
    default_ttl    = 3600
    id             = "[redacted]"
    name           = "bug report"
    activate       = false

    backend {
        address               = "httpbin.org"
        auto_loadbalance      = false
        between_bytes_timeout = 10000
        connect_timeout       = 1000
        error_threshold       = 0
        first_byte_timeout    = 15000
        max_conn              = 200
        name                  = "Host 1"
        port                  = 443
        ssl_cert_hostname     = "httpbin.org"
        ssl_check_cert        = true
        ssl_sni_hostname      = "httpbin.org"
        use_ssl               = true
        weight                = 100
    }

    domain {
        name = "test-domain-1.ps-pantheon.com"
    }

    snippet {
        content  = <<-EOT
            if (req.url !~ "^/anything") {
              set req.url = "/anything" req.url;
            }
        EOT
        name     = "url rewrite"
        priority = 100
        type     = "recv"
    }
}

```

### Steps to Reproduce
1. Import an active Fastly service (TF file above is the initial active state, call it v1).
2. Update a few things, eg. add a domain and change a snippet.
3. Using `activate = false`, run `terraform apply` and confirm to create a new draft service (v2).
4. DO NOT activate v2.
5. Update the TF script again, eg. add another snippet.
6. Run `terraform apply` again.

Example of first edit (step 2):
```diff
     domain {
         name = "test-domain-1.ps-pantheon.com"
     }
+    domain {
+        name = "test-domain-2.ps-pantheon.com"
+    }
 
     snippet {
         content  = <<-EOT
-            if (req.url !~ "^/anything") {
-              set req.url = "/anything" req.url;
+            if (req.url !~ "^/(status|cookies)") {
+              if (req.url !~ "^/anything") {
+                set req.url = "/anything" req.url
+              }
             }
         EOT
         name     = "url rewrite"
```

Note the missing semicolon in the new snippet which will cause Fastly to error out when activating.

Screenshot of diff from v2 to v1:
<img width="471" alt="Screen Shot 2021-02-18 at 10 27 14" src="https://user-images.githubusercontent.com/1203675/108379503-040e8d00-71d4-11eb-966f-70f27e28e886.png">

Diff of `.tf` file after fixing error:
```diff
         content  = <<-EOT
             if (req.url !~ "^/(status|cookies)") {
               if (req.url !~ "^/anything") {
-                set req.url = "/anything" req.url
+                set req.url = "/anything" req.url;
               }
             }
         EOT
```

Diff of v3 and v1 from the Fastly UI:
<img width="492" alt="Screen Shot 2021-02-18 at 10 30 33" src="https://user-images.githubusercontent.com/1203675/108379937-64053380-71d4-11eb-863e-902c1e5df801.png">

Note that the new domain created on v2 no longer appears in the changeset.

`active_version` is `1` in `terraform.tfstate` (which is correct).

### Expected Behavior
When TF refreshes the state on a `plan` or `apply`, it should use v1 as the baseline and determine that the domain and two snippets need to be created. The changes that are applied on the new draft should be _all_ of the changes specified in the `.tf` file that are not present in the active version.

### Actual Behavior
Only the most recently added snippet is created. The diff of v3 to v1 in the Fastly UI is the delta of changes between v2 (not activated) and v3 and does not contain all of the changes requested by the `.tf` file.

I suspect based on [these lines](https://github.com/fastly/terraform-provider-fastly/blob/8f24204024233504fa9efb2099f11374885ca9eb/fastly/base_fastly_service_v1.go#L456-L463) that the presence of an unactivated draft means that the provider will fall back to the draft when calculating a diff between the `.tf` file and the current state. The problem is that _isn't_ the current state; the real current state that needs to be the baseline is the active version.

### Potential Workarounds
1. If a draft service is created but not activated and another TF push is required (eg. there was a typo in the draft service [v2]), clone the active version (v1) into a new version (v3), activate v3, and then push a new draft (v4) with the fixes. Not ideal because you end up with a draft service you should not activate every time this happens.
2. (not personally tested but I've heard this works) Set `active_version = x` in the `.tf` file where `x` is the actual active version of the config, and most important keep it up-to-date. The downside to doing this is that the `.tf` file is not automatically updated after a successful push, and if left committed in the repo you run the risk of calculating a diff against an out-of-date config, especially if someone goes into the Fastly UI and makes manual changes.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #358 may be related

**Comment by tmountjr** [comment]
I did check out the second workaround - `active_version` is a read-only variable so that workaround won't work.

**Comment by sysamma** [comment]
I think we experienced this issue today. We had a failed Terraform apply that created a draft version. After that we could not do another apply. We got errors regarding duplicate resources.

We eventually resolved this by reverting back to a previous Fastly service configuration, presumably one that matched the Terraform state.

What appeared to be happening was that the Terraform plan was running against the active configuration, but then the Terraform apply cloned the latest draft, and then failed to apply.  (this is just an assumption)

**Comment by sysamma** [comment]
We experienced this again today, and found that ...

 - if Terraform errors during an apply you get a draft version
 - this is then used as a base for future applies and can cause errors

We resolved by updating cloned_version in the state file to match the active version in Fastly

I think the Terraform provider should update the state file to ensure cloned_version matches the active version, when a state refresh is done

**Comment by tmountjr** [comment]
The latest version of the provider seems to fix this (I've missed a few
semicolons or ending braces and had to redeploy). There a new bit of
metadata imported into the state file - cloned_version or draft_version,
not in front of my computer to be able to check - and subsequent runs of
`terraform apply` seem to run against the active version even if there's a
higher draft version. I'd upgrade your provider and give it a try.

**Comment by sysamma** [comment]
I'm still seeing this issue in v0.30.0. cloned_version in the Terraform state file points to a draft version, and the plan can fail with duplicate resources.

The only way I'm finding to work around this is to change "cloned_version" in the state file to match the current active version.

**Comment by bengesoff** [comment]
I think I can see what's happening here, it sounds like the provider is:

1. cloning a new version
2. setting `cloned_version` to the new version
3. making some updates
4. failing
5. attempting to clone the new broken version the next time when it tries again
6. getting confused
 
A possible fix for this could be to only increment `cloned_version` to the new version once the updates have all completed successfully. I'll try and reproduce the original issue and see if this helps. The new steps would be:

1. clone a new version
2. make some invalid updates
3. fail
4. clone the original `cloned_version` before the broken version
5. make the valid updates and hopefully not get confused
6. update `cloned_version` to the point to the successful version

@sysamma, just to check, have you got `activate=false` in your service?

**Comment by sysamma** [comment]
HI @bengesoff 

Yes, I think that's exactly what's happening, it updates cloned_version before it's successful activated.

Whereabouts is that activate option? I can't find it.

Thanks

**Comment by bengesoff** [comment]
@sysamma if you can't find it, I'm guessing it'll be the default of `activate=true` so don't worry. I believe I may have reproduced the issue with the following steps:

1. provision a service with a valid snippet and one backend
2. update the service with an invalid snippet and rename the backend
3. update the service with a valid snippet and the new backend name

This gives an error of `Invalid configuration for Fastly Service` for step 2, then the following error for step 3:

```
        Error: 409 - Conflict:
        
            Title:  Duplicate record
            Detail: Duplicate backend: 'backend2'
```

Does that look vaguely similar to what you were doing?

**Comment by sysamma** [comment]
@bengesoff - yep, exactly that :-)

**Comment by Integralist** [comment]
I'll be cutting a new release Monday that will include the above PR changes. I'll post an update once it's published.

**Comment by Integralist** [comment]
👋🏻 

`v0.31.0` has just been published:  
https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.31.0

**Comment by PaulRudin** [comment]
I know this is closed, but I think I've hit something similar. The provider shows the cloned version as being several version behind the currently active version and I'm not exactly sure how to get it to sync up.
