### ISSUE TITLE
v0.25.0 has checksum issue

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#375]
👋  it looks like the registry is using 0.25.0, but the latest release in here is 0.24.0.

```
Initializing the backend...

Initializing provider plugins...
- Finding fastly/fastly versions matching "~> 0.25.0"...

Error: Failed to install provider

Error while installing fastly/fastly v0.25.0: could not query provider
registry for registry.terraform.io/fastly/fastly: failed to retrieve
authentication checksums for provider: 404 Not Found
```

reverting back to 0.24.0 fixed my issue.

```
Initializing provider plugins...
- Finding fastly/fastly versions matching "0.24.0"...
- Installing fastly/fastly v0.24.0...
- Installed fastly/fastly v0.24.0 (signed by a HashiCorp partner, key ID 508A0A1DCC9FE27E)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
```

---

registry info
![image](https://user-images.githubusercontent.com/1580956/109319837-51ff4280-781d-11eb-8a1c-8ef7c06486e0.png)

**Comment by Integralist** [comment]
@chenrui333 are you able to try again. I noticed something funky happened with one of our GitHub Actions, and that the release I had published had reverted back to a 'draft'. I just re-published and updated a project locally to use the new version 0.25.0 and it seems to have worked...

<img width="733" alt="Screenshot 2021-02-26 at 15 37 09" src="https://user-images.githubusercontent.com/180050/109320967-863c2880-7848-11eb-8ea0-3504a9407f40.png">

**Comment by Integralist** [comment]
Going to close this issue today if there's not further feedback following my last comment.

**Comment by chenrui333** [comment]
yeah, it works fine for me now. Thanks @Integralist! 
```
Initializing provider plugins...
- Finding fastly/fastly versions matching "0.25.0"...
- Installing fastly/fastly v0.25.0...
- Installed fastly/fastly v0.25.0 (signed by a HashiCorp partner, key ID 508A0A1DCC9FE27E)
```

**Comment by Integralist** [comment]
Thanks great news. Thanks @chenrui333
