### ISSUE TITLE
Support for Syslog logging

### ISSUE THREAD

**Issue by Constantin07** [fastly/terraform-provider-fastly#38]
Hi,

At the moment fastly provider does support S3 logging endpoint but it would be nice to have possibility to template as well **syslog** logging endpoints.

Regards,
Constantin

**Comment by MrTish** [comment]
We're using the **syslog** endpoint for this.  Sadly this is not yet supported.

In https://github.com/terraform-providers/terraform-provider-fastly/issues/34#issuecomment-322472823, there is mention of something in the pipeline.

@catsby - any idea when it might appear?

**Comment by MerlinDMC** [comment]
It apparently did hit with https://github.com/terraform-providers/terraform-provider-fastly/pull/16 just no new release since then.

**Comment by catsby** [comment]
I'll see about a release this week, thanks for the poke

**Comment by MerlinDMC** [comment]
@catsby I don't want to poke too much but I have to reconfigure a lot of services and a new release would make it a nice and easy job 😃

**Comment by catsby** [comment]
cc @thommahoney

**Comment by ctennis** [comment]
Yeah, we'd love a release too to be able to use the syslog feature!!!

**Comment by philippschulte** [comment]
Support for `syslog` logging was part of release [0.1.3 (December 18, 2017)](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/CHANGELOG.md#013-december-18-2017). Therefore, I will close this issue.
