### ISSUE TITLE
`acl` Parameter For s3logging Block On `fastly_service_v1` Resource

### ISSUE THREAD

**Issue by jeffwecan** [fastly/terraform-provider-fastly#409]
### Terraform Version
```
%▶ tf -version
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/fastly/fastly v0.29.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
-  fastly_service_v1

### Terraform Configuration Files
```
resource "fastly_service_v1" "hc_releases" {
# [...]
  s3logging {
    acl              = "bucket-owner-full-control"
    bucket_name      = var.fastly_s3_logs_bucket_name
    format           = "%h %l %u %%{now}V %%{req.request}V %%{req.url}V %>s"
    format_version   = 2
    gzip_level       = 7
    message_type     = "classic"
    name             = "S3 Logs"
    path             = "some-path/"
    period           = 3600
    redundancy       = "standard"
    s3_iam_role      = aws_iam_role.fastly_logging.arn
    timestamp_format = "%Y-%m-%dT%H:%M:%S.000"
  }
# [...]
}
  ```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior

The `s3logging` block supports an `acl` parameter as [documented in the API / developers documentation](https://developer.fastly.com/reference/api/logging/s3/):

> The access control list (ACL) specific request header. See the AWS documentation for Access Control List (ACL) Specific Request Headers for more information.

### Actual Behavior
```
╷
│ Error: Unsupported argument
│ 
│   on fastly.tf line 122, in resource "fastly_service_v1" "hc_releases":
│  122:     acl              = "bucket-owner-full-control"
│ 
│ An argument named "acl" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on fastly.tf line 138, in resource "fastly_service_v1" "hc_releases":
│  138:     acl              = "bucket-owner-full-control"
│ 
│ An argument named "acl" is not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by Integralist** [comment]
Hi @jeffwecan, thanks for opening this issue. I've added it to our backlog.

I can't give an exact time frame for when it will be implemented but I am now aware of the issue and because it's not necessarily a large request (although there's some co-ordination that needs to happen with the [go-fastly](https://github.com/fastly/go-fastly) dependency), I'll see if this is able to be pushed through sooner rather than later. 

In the mean time, if you have any further feedback or context you wish to share with me, then please comment below.

Thanks again!

**Comment by tpansino** [comment]
Added https://github.com/fastly/go-fastly/issues/278 to request gofastly support this property 👍

**Comment by Integralist** [comment]
Quick update to say there is a new go-fastly 3.7.0 release that adds some missing options. We'll look to work on the Terraform integration shortly.

**Comment by Integralist** [comment]
I'll be cutting a new release Monday that will include the above PR changes. I'll post an update once it's published.

**Comment by Integralist** [comment]
👋🏻 

`v0.31.0` has just been published:  
https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.31.0
