### ISSUE TITLE
Error on terraform apply: header seems to be changing after any kind of terraform apply.

### ISSUE THREAD

**Issue by idonca** [fastly/terraform-provider-fastly#412]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.15.3

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
It shouldn't try to change anything or to see anything changed on the configuration.

### Actual Behavior
What actually happened?
```
Hello,

There seem to be some issues with the fastly terraform provider, even if we didn't change anything on the header side, somehow terraform see that there are some changes. Above are more details. Could you tell us where can be the problem?

  # module.fastly-vid-connatix-com.fastly_service_v1.fastly will be updated in-place
  ~ resource "fastly_service_v1" "fastly" {
        id             = "id"
        name           = "vid.connatix.com"
        # (6 unchanged attributes hidden)
      - header {
          - action        = "set" -> null
          - destination   = "http.Cache-Control" -> null
          - ignore_if_set = true -> null
          - name          = "response-cache" -> null
          - priority      = 100 -> null
          - source        = "\"max-age=31557600\"" -> null
          - type          = "response" -> null
        }
      + header {
          + action        = "set"
          + destination   = "http.Cache-Control"
          + ignore_if_set = true
          + name          = "response-cache"
          + priority      = 100
          + regex         = (known after apply)
          + source        = "\"public,max-stale=31557600,stale-while-revalidate= 31557600, immutable,max-age=31557600\""
          + substitution  = (known after apply)
          + type          = "response"
        }




        # (15 unchanged blocks hidden)
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by Integralist** [comment]
Hi @idonca, thanks for opening this issue.

From what I can see it appears you have made some configuration changes. Specifically, the following attributes appear to have changed...

```diff
+ regex         = (known after apply)
+ source        = "\"public,max-stale=31557600,stale-while-revalidate= 31557600, immutable,max-age=31557600\""
+ substitution  = (known after apply)
```

I'm not sure what version of the Fastly Terraform provider you're using, but I would recommend upgrading to the latest version just as a standard practice. Otherwise I would recommend checking that the Header resource wasn't changed outside of Terraform (e.g. directly in the UI or via an external script using the Fastly API).

**Comment by Integralist** [comment]
@idonca I've also opened up a conversation in your customer Fastly Support Slack account.

**Comment by idonca** [comment]
Hello @Integralist ,

Thanks for your answer. Terraform fastly provider is at the latest version:

```
provider "registry.terraform.io/fastly/fastly" {
  version = "0.30.0"
```
  
From the UI we didn't change anything neither from an external script that is using Fastly API.
The problem is that I tried to apply the changes and this is the output:
```
Error: [ERR] Invalid configuration for Fastly Service (36Lzm6My8YNjc9gb1wME9f): Failed to parse log format string.
│
│   with module.fastly-vid-connatix-com.fastly_service_v1.fastly,
│   on module/main.tf line 1, in resource "fastly_service_v1" "fastly":
│    1: resource "fastly_service_v1" "fastly" {
```

**Comment by Integralist** [comment]
Thanks @idonca can you reach out to support@fastly.com and link them to this issue as it might be easier to discuss with customer support (as they can share more internal information about your account and configuration details). Thanks!

**Comment by idonca** [comment]
hello @Integralist ,

thank you for all the details and the support! I managed to resolve the problem:
First, the error was from my side, a mistake on the log format
Second, we solve also the problem with the header that appeared continuously as a need to be changed.

Closing this issue.

**Comment by Integralist** [comment]
Great news! Thanks @idonca. Glad you got things resolved 👍🏻
