### ISSUE TITLE
Fastly s3loggingg function not working with Terraform 

### ISSUE THREAD

**Issue by idonca** [fastly/terraform-provider-fastly#413]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Details
We do not have indeed an issue, we have only a question and we want to see if we can get an answer. Below are described the details.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
terraform v0.15.4

### Affected Resource(s)
Please list the resources as a list, for example:
- s3logging

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
Pasted below
```

### Debug Output
- not applicable

### Panic Output
- not applicable

### Expected Behavior
We have this setup:
```
format = jsonencode({
"timestamp" : "%%{%Y-%m-%dT%H:%M:%S%z}t",
"responsesize" : "%O",
"continentcode" : "%%{geoip.continent_code}V",
"playerid" : "%%{querystring.get{%q, playerId)}V",
"source" : "%%{querystring.get(%q, source)}V",
"implementationtype" : "%%{querystring.get(%q, implementationType)}V",
})
```
but this is what I receive:
```
{
	"continentcode": "EU",
	"implementationtype": "{querystring.get(/2c95b9ae-2490-4b79-a482-b39de207a0a6/f666c067-c4f6-4cdd-bedd-0eabf6a3e9f9_360_h264.mp4, implementationType)}V",
	"playerid": "{querystring.get(/2c95b9ae-2490-4b79-a482-b39de207a0a6/f666c067-c4f6-4cdd-bedd-0eabf6a3e9f9_360_h264.mp4, playerId)}V",
	"responsesize": "1090578",
	"source": "{querystring.get(/2c95b9ae-2490-4b79-a482-b39de207a0a6/f666c067-c4f6-4cdd-bedd-0eabf6a3e9f9_360_h264.mp4, source)}V",
	"timestamp": "2021-05-28T12:42:24+0000"
}
Seems like function "querystring.get" is threat like a string and not like a function.
https://developer.fastly.com/reference/vcl/functions/query-string/querystring-get/
```

### Actual Behavior
What actually happened?
It's not logging properly.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
- not applicable
- 
### Important Factoids
- not applicable

### References
- not applicable

Thank you,
-Ionut

**Comment by Integralist** [comment]
Hi @idonca 

The docs seem to imply that only VCL variables are supported in the logging format, and not VCL functions, which would explain the behaviour you're seeing...

> The literal VCL to include without quoting. This can be used to write VCL variables to your logs

https://docs.fastly.com/en/guides/custom-log-formats#version-2-log-format.

Also, all of the examples in the docs show variables instead of functions so I think the use of functions isn't supported in the custom log format configuration. If the use of VCL functions in the configuration is critical then please open a Fastly support ticket (via support@fastly.com) and one of our customer service engineers will be able to investigate this further.

**NOTE**: There may be a typo in your snippet, with a `{` where a `(` should be. Specifically: `"%%{querystring.get{%q, playerId)}V"` looks like `querystring.get{` should be `querystring.get(`. I highly doubt this would be causing the issue with the other fields but it might be worth double checking that just in case.

Thanks.

**Comment by idonca** [comment]
Hello @Integralist,

Thanks for your reply and help.
Unfortunately, wasn't that typo...

```
Invalid configuration for Fastly Service (36Lzm6My8YNjc9gb1wME9f): Syntax error: Expected string variable or constant
│ at: (input Line 1945 Pos 154)
│   log {"syslog "} req.service_id {" fastly-vid-s3-logging :: "} {"{"continentcode":""} geoip.continent_code {"","implementationtype":""} querystring.get(%q, implementationType) {"","
playerid":""} querystring.get(%q, playerId) {"","responsesize":""} resp.bytes_written {"","source":""} querystring.get(%q, source) {"","timestamp":""} strftime({"%Y-%m-%dT%H:%M:%S%z"},
 time.start) {"""} "}";
 ```
 I also opened a ticket in the fastly support portal.
 Do you mind if I keep also this issue open? Maybe someone already had this problem and can jump with some tips/hints.

Thanks,
-Ionut

**Comment by Integralist** [comment]
@idonca 

> Do you mind if I keep also this issue open? Maybe someone already had this problem and can jump with some tips/hints.

Absolutely! 

If you get a more concrete answer/solution from Fastly Support, then if you wouldn't mind letting me know.

Thanks.

**Comment by idonca** [comment]
hello @Integralist,

we find out how we should have the format:
```
      format = jsonencode({
        "timestamp" : "%%{%Y-%m-%dT%H:%M:%S%z}t",
        "responsesize" : "%O",
        "continentcode" : "%%{geoip.continent_code}V",
        "playerid" : "%%{querystring.get(req.url, \"playerId\")}V",
        "source" : "%%{querystring.get(req.url, \"source\")}V",
        "implementationtype" : "%%{querystring.get(req.url, \"implementationType\")}V",
      })
```
But now, we are receiving this response:
```
{"continentcode":"EU","implementationtype":"(null)","playerid":"(null)","responsesize":"1454","source":"(null)","timestamp":"2021-06-04T08:31:18+0000"}
```
and we want to achieve this response:
```
{"continentcode":"EU","implementationtype":null,"playerid":null,"responsesize":"1454","source":null,"timestamp":"2021-06-04T08:31:18+0000"}
```
Do you know by any chance how we should do that?

**Comment by smaeda-ks** [comment]
in pure VCL:

```
if(querystring.get(req.url, "playerId"), {"""} querystring.get(req.url, "playerId") {"""}, "null");
```

so I assume you need to escape like this in your TF file:

```
"%%{if(querystring.get(req.url, \"playerId\"), \{\"\"\"\} querystring.get(req.url, \"playerId\") \{\"\"\"\}, \"null\")}V"
```

**Comment by idonca** [comment]
Hello @smaeda-ks ,

Yes, I already tried that, but no luck. Is complaining: `Illegal escape sequence`
Thanks,
-Ionut

**Comment by smaeda-ks** [comment]
maybe you need double escape around `{ }`?

`\\{` `\\}`

**Comment by Integralist** [comment]
👋🏻 @smaeda-ks are you able to create a working solution on https://fiddle.fastlydemo.net/ (might be easier to play around with)

**Comment by smaeda-ks** [comment]
That's an escape in TF world, Fiddle won't help that much. As I mentioned, pure VCL just works fine.

**Comment by Integralist** [comment]
Ah, fair enough 🙂

**Comment by idonca** [comment]
Hello,

We finally found the correct solution for our problem:
```hcl
      format = jsonencode({
        "timestamp" : "%%{%Y-%m-%dT%H:%M:%S%z}t",
        "responsesize" : "%O",
        "continentcode" : "%%{geoip.continent_code}V",
        "playerid" : "%%{if(querystring.get(req.url, \"playerId\"), querystring.get(req.url, \"playerId\"), \"null\")}V",
        "source" : "%%{if(querystring.get(req.url, \"source\"), querystring.get(req.url, \"source\"), \"null\")}V",,
        "implementationtype" : "%%{if(querystring.get(req.url, \"implementationType\"), querystring.get(req.url, \"implementationType\"), \"null\")}V",
      })
```
I will close this issue.
And again, thank you for your help, much obliged.

**Comment by Integralist** [comment]
Great news! Thanks for the update @idonca 

Thanks @smaeda-ks for your help!
