### ISSUE TITLE
Crash while changing "request_setting > max_stale_age" value 

### ISSUE THREAD

**Issue by akavga** [fastly/terraform-provider-fastly#415]
**1/ Environment** 
Terraform v0.15.4 on linux_amd64 + provider registry.terraform.io/fastly/fastly v0.30.0

**2/ Issue : plugin crash while changing "request_setting > max_stale_age" value** 
```
request_setting {
        max_stale_age = 80001  # previous value is 80000
    }
```

terraform apply
```
Stack trace from the terraform-provider-fastly_v0.30.0 plugin:

panic: interface conversion: interface {} is int, not uint

goroutine 50 [running]:
github.com/fastly/terraform-provider-fastly/fastly.(*RequestSettingServiceAttributeHandler).Process(0xc00000e608, 0xc00017f780, 0x11, 0xc000580440, 0x0, 0x1)
        github.com/fastly/terraform-provider-fastly/fastly/block_fastly_service_v1_requestsetting.go:122 +0
```

**3/ Quick & dirty solution**

It seems the tfstate file is read as a `int`, but the provider expects a `uint`. 
I cloned the repository on my local machine to change locally change the cast

In `terraform-provider-fastly/fastly/block_fastly_service_v1_requestsetting.go`, I changed:

```
		if v, ok := modified["max_stale_age"]; ok {
			// Old code: opts.MaxStaleAge = gofastly.Uint(v.(uint))
			helper := uint(v.(int))
			opts.MaxStaleAge = &helper
		}
```

This solved the issue for us.

**Comment by Integralist** [comment]
Thanks @akavga for raising this issue. We've implemented a fix and will cut it into a new release soon.

**Comment by akavga** [comment]
Thanks @Integralist and  @bengesoff for fixing it.
