### ISSUE TITLE
When activate=true, should we always read and clone the service from the active version, or the version last activated from Terraform?

### ISSUE THREAD

**Issue by bengesoff** [fastly/terraform-provider-fastly#416]
# Context
The behaviour prior to #390, when `activate` was `false`, was that the provider would always **read** the state from the highest version of the service, but always **clone** the version (to make updates) from the active version of the service. When `activate` was `true`, this wasn't an issue as the provider would always read the active version, and this would be the same version used for cloning. However, given that these two versions could be different when `activate` was `false`, this was a bug, as Terraform's plan could be based on a different state to that which it would be applying the changes to.

To fix this bug, the aforementioned PR changed the behaviour to always read and clone from the same version. The decision as to which version this should be ended up being the `cloned_version`, i.e. the last version that Terraform had cloned and updated. I chose this for a couple of reasons. Firstly because it seemed logical both when `activate` is `true` or `false`, and therefore avoids having to write different reading and cloning logic depending on the value of `activate`. The alternative of always reading and cloning the active version doesn't work for when `activate` is `false` as it means Terraform can never read its own changes until someone activates the service externally, and there will be constant non-empty plans until this happens. The other alternative of always reading and cloning the most recent version (highest version number) also probably doesn't fit as it doesn't allow anyone to experiment with new drafts outside of Terraform without Terraform attempting to revert their changes in the next `apply`. Therefore this decision seemed to be the best tradeoff.

However after merging that PR, a good point was made (having used the provider with the change), that this changes the behaviour when `activate` is `true`, and in a way that is actually different from how most other providers work. In particular, if you make changes outside of Terraform and activate them, the provider will now ignore the currently active version, whereas before it would have taken the updated active version and applied the changes to that. In most other providers, without having another versioning system in the service's API, the behaviour is to treat these externally-made changes as "state drift" and include them in the plan.

# Possible Solution
Based on the previous context, there seems to be an argument that the version to read/clone from be different depending on the value of `activate`. In particular:

- when `activate` is `true`, the version to read/clone from should always be the currently active version, even if this has been modified outside of Terraform
- when `activate` is `false` the version to read/clone from should be the `cloned_version`, i.e. the one that the provider last created, thus allowing other experimental drafts to be created outside of Terraform

While this adds slightly more complexity, it does appear to cater better for the two workflows. The first question is therefore does this seems to break anything else workflow-wise?

# Extra Problem with Possible Solution and Possible Solution for this Extra Problem
Another concern that arises from diverging the read/clone behaviour depending on the value of `activate`, is what happens if `activate` is toggled while a service is active. This could potentially lead to confusing diffs and behaviour that is hard to reason about, because the version of the service that the Terraform state is being read from could be quite different. For example, I think you'd naively expect the behaviour from changing `activate` to `true` to be that the `cloned_version` gets activated, when instead the `active_version` would be read, potentially cloned and modified, and then activated.

To get around this, it might be better to disallow swapping between workflows, and change the `activate` attribute to be `ForceNew`. This would cause the plan to show the service being recreated if `activate` is changed. Therefore the suggestion to the user would be to choose a behaviour and commit to it.

Other opinions on this are welcome, and it might be the case that it's perfectly fine to toggle between the different `activate` workflows, but it does seem to be more of a grey area if the behaviour is changing so signficantly with it.

**Comment by Integralist** [comment]
Hi @JiriKovar just wanted to bring the discussion from https://github.com/fastly/terraform-provider-fastly/pull/390#issuecomment-854982834 to this new issue so we can have a fresh conversation with @bengesoff about workflows and possible solutions.

Also going to cc @fastly/terraform-reviewers
