### ISSUE TITLE
Error: 409 - Conflict

### ISSUE THREAD

**Issue by idonca** [fastly/terraform-provider-fastly#419]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.15.5
```

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
╷
│ Error: 409 - Conflict:
│ 
│     Title:  Duplicate record
│     Detail: Duplicate logging_syslog: 'fastly-vid-s3-logging'
│ 
│   with module.fastly-vid-connatix-com.fastly_service_v1.fastly,
│   on module/main.tf line 1, in resource "fastly_service_v1" "fastly":
│    1: resource "fastly_service_v1" "fastly" {
│ 
╵
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
What should have happened and what is happening exactly?
We deactivated from the UI, the S3logging for a domain because we wanted to it faster than terraform (we had an emergency). The s3logging was already activated and running for that domain before that, we did with terraform.
And now, when we are trying to apply it again from terraform, we are receiving 409 error: Conflict.

**Comment by Integralist** [comment]
Hi @idonca 

Just so I have the steps clear in my head, your scenario was as follows (please correct anything I have wrong):

1. You had an active service (managed by latest Terraform version `0.30.0`) that also had S3 logging enabled.
2. Your Terraform configuration has the `fastly_service_v1` attribute `activate` set to `true`.
3. You removed the S3 logging via the UI and then activated a new service version.
4. You ran `terraform plan` with no diff/issues.
5. You ran `terraform apply` but see a 'duplicate record' error for S3 logging.

Do I have this correct? 

My understanding would be that if your Terraform configuration had `activate: true`, then Terraform would still be able to track the new service version that didn't have S3 logging enabled (even though the service version was created via the UI, i.e. outside of Terraform). 

But if you had `activate: false` set in your Terraform configuration, then Terraform would try to clone from the last active version it knew about (and in that case it would be the service version before your latest one, i.e. the service version that had the S3 logging **_enabled_**, hence you would see the 'duplicate record' error message).

I'm going to cc also @bengesoff who implemented the recent update to the `clone_version` behaviour and might be able to comment on this, as the issue looks to be related.

**Comment by idonca** [comment]
Hello @Integralist,

Thanks for answering me and sorry to bother again with a new issue.
1. Yes
2. We have the default value there because we didn't specify anything. I saw that the default value is `true`
3. Exactly
4. Also `terraform plan` and `terraform apply` are giving me the `duplicate record` error for S3 logging.

Thank you,
-Ionut

**Comment by Integralist** [comment]
Thanks @idonca for raising this issue. This helped us to identify a problem with how the active version was being tracked. We've merged a fix for this and I'll look to get a new release cut shortly.

**Comment by idonca** [comment]
Hello @Integralist ,

has been this already deployed?
