### ISSUE TITLE
Support for M1 Silicon

### ISSUE THREAD

**Issue by 0x91** [fastly/terraform-provider-fastly#429]
Produce darwin_arm64 builds to support Apple M1 Macs.

Upgrading to go1.16 should be enough as the goreleaser configuration is already present.

**Comment by chenrui333** [comment]
Should be fixed by #399

**Comment by Integralist** [comment]
Should be fixed by https://github.com/fastly/terraform-provider-fastly/pull/447

I'm aiming to get a new release cut very soon.
