### ISSUE TITLE
Using Write_once Dictionary Results in 400 Errors With fastly_service_dictionary_items_v1

### ISSUE THREAD

**Issue by virgofx** [fastly/terraform-provider-fastly#442]
Using Terraform to create a new Fastly service that utilizes a **private** (specifically via the `write_only = true` flag in the service) dictionary with a defined item.

### Terraform Version
```
Terraform v0.14.6
+ provider registry.terraform.io/fastly/fastly v0.32.0
```

### Affected Resource(s)
- fastly_service_dictionary_items_v1

### Terraform Configuration Files
```hcl
locals {
  fastly_edge_dictionary_name  = "dictionary_name"
  fastly_edge_dictionary_items = {
    edge_auth_secret : "secret"
  }
}
```
```hcl
resource "fastly_service_v1" "service" {
  name = "service"
  activate = true

  domain {
    name = "some-domain.com"
  }

  dictionary {
    name       = local.fastly_edge_dictionary_name
    write_only = true 
  }
}
```
```hcl
resource "fastly_service_dictionary_items_v1" "service_dictionary_items" {
  for_each = {
    for d in fastly_service_v1.service.dictionary : d.name => d if d.name == local.fastly_edge_dictionary_name
  }

  service_id    = fastly_service_v1.service.id
  dictionary_id = each.value.dictionary_id
  items         = local.fastly_edge_dictionary_items

  # Added this to try and avoid the error; however, still got the error
  lifecycle {
    ignore_changes = all
  }
}
```

### Output

```
Error: 400 - Bad Request:

    Title:  Bad request
    Detail: Not allowed to read contents of write_only dictionary

```

### Expected Behavior
I've tested adding the lifecycle rule with ignore_changes set to the special `all` keyword to avoid having the dictionary items attempt to query via API in the future but it doesn't work. 

I'd expect that with lifecycle rules set to ignore items or `all` the dictionary items wouldn't call into read items and thus not error.

**Comment by smaeda-ks** [comment]
Thanks, @virgofx 
We will look into this.

**Comment by virgofx** [comment]
Much appreciated 👍

**Comment by smaeda-ks** [comment]
@virgofx , After reviewing this issue, unfortunately, there seems to be no reasonable workaround for this.

The most obvious reason is that it's a private dictionary, we can't fetch the actual items in the dictionary using API, meaning there is no way to track diff for a given private dictionary.

This is also why we mention:

https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_v1#nestedblock--dictionary

> `write_only` (Boolean) If `true`, the dictionary is a private dictionary, and items are not readable in the UI or via API. Default is `false`. It is important to note that changing this attribute will delete and recreate the dictionary, and discard the current items in the dictionary. _**Using a write-only/private dictionary should only be done if the items are managed outside of Terraform**_

We could ignore the error and let it process, but then that almost certainly causes another 400 - "Duplicate dictionary_item: ... " error. Because we can't know what items in the dictionary currently, and we try to create new items using `CREATE` batch operation, and get 400 since the items exist already.

Our best bet is to address this in our documentation by adding a clear warning message to indicate that we can't support private dictionaries with `fastly_service_dictionary_items_v1` resource.

Also: https://github.com/fastly/terraform-provider-fastly/pull/400

**Comment by virgofx** [comment]
@smaeda-ks Most of that makes sense. I'm wondering if it would be possible to add an enhancement where we could seed the write-only dictionary from Terraform. Specifically, only once. Thus, by adding a lifecycle rule to either `items` or special value of `all`, the resource would only ever seed the first time and then never make any more subsequent calls to the API thereby avoiding the write-only restrictions and because of the lifecycle rule, there would never be any future duplicate dictionary items.

Thoughts?

**Comment by smaeda-ks** [comment]
@virgofx That seems an extremely rare use case and I don't think it's worth adding at the moment. That doesn't really make sense to me using Terraform for such a one-time-only operation.

> the resource would only ever seed the first time and then never make any more subsequent calls to the API thereby avoiding the write-only restrictions and because of the lifecycle rule, there would never be any future duplicate dictionary items.

Considering write_only dictionaries are "versionless" objects as well as there's no way to see what's in there, it is still possible to end up with the duplicate error scenario even with that approach (e.g., if someone updated the write_only dictionary outside from TF executions).

Given that, we will be addressing this with documentation updates for the time being. Appreciate your comment though.

**Comment by smaeda-ks** [comment]
We've added a `Limitations` section based on your feedback:
https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_dictionary_items_v1#limitations

Thank you.
