### ISSUE TITLE
`"now" is not a valid template control keyword` for custom log format

### ISSUE THREAD

**Issue by kiyanwang** [fastly/terraform-provider-fastly#443]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/fastly/fastly v0.32.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior

I was able to import the service, and then `terraform show > myservice.tf` to write to a tf file.

### Actual Behavior

The next time I run terraform import/plan etc, it errors, on the s3 logging format:

```
terraform import fastly_service_v1.rl_widgets_assets REDACTED                                ─╯
╷
│ Error: Invalid template control keyword
│
│   on rl_talis_com_service.tf line 341, in resource "fastly_service_v1" "rl_talis_com":
│  341:         format           = "%h %l %u %{now}V %{req.request}V %{req.url}V %>s %{resp.status}V"
│
│ "now" is not a valid template control keyword. Did you mean "for"?
╵
```

However as per the fastly documentation `now` is valid: https://docs.fastly.com/en/guides/custom-log-formats

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by smaeda-ks** [comment]
Hi @kiyanwang ,

This is not an issue with our provider. Please see: https://www.terraform.io/docs/language/expressions/strings.html#escape-sequences

You need to escape `%{` to `%%{`.

**Comment by kiyanwang** [comment]
thank you!
