### ISSUE TITLE
Updates to TLS Subscription Doesn't update Managed DNS Challenges Value

### ISSUE THREAD

**Issue by virgofx** [fastly/terraform-provider-fastly#451]
The recent change to support multiple domain DNS challenges was great. Thank you.

However, it appears, after the first seed, and when updating the domains from X to X+1, the `managed_dns_challenges` output doesn't increase it's output set to include new values on the corresponding plan/apply. Thus any subsequent dependencies (e.g. Route 53, won't update until a future run).

```
resource "fastly_tls_subscription" "default" {
  domains               = ["test1.example.com"]
  certificate_authority = "lets-encrypt"
  force_update          = true
  force_destroy         = true
}
```

```
resource "aws_route53_record" "domain_validation_records" {
   for_each = { for domain in fastly_tls_subscription.default.managed_dns_challenges : domain.record_name => domain }
   ...

   depends_on = [ fastly_tls_subscription.default ]
}
```

Then change...
```
  domains               = ["test1.example.com", "test2.example.com"]
```

The next plan/apply will update the subscription but **not** any changes for the Route53 records. In order to apply the domain validation record, an additional apply must be run after the current apply completes.

Additionally, once applied, Terraform will return immediately. However, Fastly, takes 1-10 minutes to provision appropriately.

This also causes an issue when going from a long list to small list. It will actually cause Terraform to fail.

----

I just retested the example above an in the documentation ... It appears on the very first run (no subscription, no DNS entries), it also errors also:

```
Error: Invalid for_each argument
  on dns.tf line 65, in resource "aws_route53_record" "domain_validation_records":
  65:   for_each = { for domain in fastly_tls_subscription.default.managed_dns_challenges : domain.record_name => domain }

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

The above is virtually the same as the documentation. This could be avoided as one could key the above with domains that are specified in the TLS record. However, if you do this, it doesn't work when updating the the domains of a TLS subscription due to the bug listed initially.

### Thus, recommendation:
1) Fix the `managed_dns_challenges` output to return proper values and count on a plan/apply after a change is made to the `domains` field.
2) Update the documentation for domain validation Route53 for_each loop to key using a locally defined array that is passed into the TLS subscription `domains` as that should correspond 1:1:1 all the way through.

### Fastly Provider
`0.33.0`

### Terraform Version
`0.14.6`

### Affected Resource(s)
Please list the resources as a list, for example:
- `fastly_tls_subscription`

**Comment by smaeda-ks** [comment]
Thanks. This is not a bug in our provider, but a limitation in Terraform, specifically for [`for_each`](https://www.terraform.io/docs/language/meta-arguments/for_each.html#limitations-on-values-used-in-for_each) as the error message says. [`managed_dns_challenges`](https://github.com/fastly/terraform-provider-fastly/blob/v0.33.0/fastly/resource_fastly_tls_subscription.go#L78-L81) is indeed a [`Computed`](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#computed) attribute.

It is updating the state file properly when a change is made to the subscription, but because it's a computed value `for_each` can't know it at the time of execution.

We will address this in documentation updates to note that `fastly_tls_subscription` resource must be created first then run `aws_route53_record`.

**Comment by Integralist** [comment]
@smaeda-ks would it be possible to use a `depends_on` here?

e.g.

```terraform
resource "aws_route53_record" "domain_validation_records" {
   depends_on = [fastly_tls_subscription.default.managed_dns_challenges]
   for_each = { for domain in fastly_tls_subscription.default.managed_dns_challenges : domain.record_name => domain }
   ...
}
```

...and even if we could, I wonder if that would then cause Terraform to have timeout issues (considering the provisioning can take up to 10mins on Fastly's side).

**Comment by virgofx** [comment]
The `depends_on` should be all that's needed, but it doesn't impact in this case. I actually did my tests with it on and updated the reference above^.

This really is a severe limitation and makes it practically unusable from a Terraform point of view. The records could easily be created as follows as I mentioned using the value of domains as the keys:

```
locals {
  domains = ["test1.example.com"]
}

resource "fastly_tls_subscription" "default" {
  domains               = locals.domains
  certificate_authority = "lets-encrypt"
  force_update          = true
  force_destroy         = true
}

resource "aws_route53_record" "domain_validation_records" {
  # If we enumerate managed_dns_challenges, we can't properly
  # determine how many of these will be created until the subscription is created. Since we
  # know we'll need validation records for each domain supplied to the subscription, just
  # enumerate the same set and then pluck the managed_dns_challenges by filtering the
  # somewhat pretty consistent Fastly validation format that just uses a
  # "_acme-challenge.EXISTING-DOMAIN-RECORD.COM" format.
  for_each = {
    for domain in local.domains :
    domain => element([
      for obj in fastly_tls_subscription.default.managed_dns_challenges :
      obj if domain == replace(obj.record_name, "/^[a-zA-Z0-9-_]+\\./", "")
    ], 0)
  }

   ...

   depends_on = [ fastly_tls_subscription.default ]
}
```

Here's the issue - this works the first time and is often the workaround I've seen recommended for computed values. However, there is a bug that managed DNS challenges DOES NOT UPDATE computed value in plan/apply on a second modification. Being computed is fine but there is definitely a difference running first vs. second time (with domain changes)

Side note - if the `managed_dns_challenges` output also returned the original domain value in each challenge object that would be helpful and avoid the little hack to determine which domain the managed_dns_challenge object belongs to.

**Comment by smaeda-ks** [comment]
I will take a look.

**Comment by smaeda-ks** [comment]
@virgofx You're right that there appears to be a bug in Terraform core. I'll be working on this fix in https://github.com/fastly/terraform-provider-fastly/pull/453

Thanks

**Comment by virgofx** [comment]
Awesome, thanks so much @smaeda-ks . And for reference was explicitly using `0.14.7`. If this is somehow related to Terraform core and a newer version is needed let me know.

**Comment by smaeda-ks** [comment]
Hi @virgofx, could you please try: https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.34.0 ? Thanks

**Comment by virgofx** [comment]
@smaeda-ks I've confirmed 0.34.0 fixes the issue. Thank you so much! 👍
