### ISSUE TITLE
optional backend block

### ISSUE THREAD

**Issue by marcb1** [fastly/terraform-provider-fastly#454]
For the resource `fastly_service_v1`, it seems that the `backend` argument is required, this is mentioned in the docs here: https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_v1#required

The backend arg wasn't required in old versions of this plugin (namely `0.26.0`), and we have a few services that define the backend in the actual VCL (as this is allowed by the fastly API).

Is there a workaround to this, or is it possible to make the `backend` arg optional?

Currently getting this error when trying to upgrade to the latest version of the plugin:
```
The argument "backend" is required, but no definition was found.
```

**Comment by smaeda-ks** [comment]
@marcb1 Good point. Thanks for pointing that out. I will look into that.

**Comment by smaeda-ks** [comment]
@marcb1 This will be released in the next version.
