### ISSUE TITLE
[Feature Req] Possibility to add capability to automatically purge `fastly_service_v1` on Terraform apply

### ISSUE THREAD

**Issue by virgofx** [fastly/terraform-provider-fastly#460]
I was wondering if it would be possible to have a boolean parameter for the `fastly_service_v1` resource named something along the lines like `purge_service_on_apply`. This flag would dictate that whenever a `terraform apply` made a change and if this was set to `true`, it would do an API request to purge the cache. 

Documentation for this parameter would need to include the snippet that a corresponding `purge*` ACL must be included in your FASTLY_API_KEY.

Currently, we use a null resource in combination with a trigger to do the same thing and its very hackish. 

I feel like it's pretty common to make VCL related changes where a purge is required. Making it a parameter and opt-in would thus be 100% backwards compatible. Curious if core team is open to this idea?

**Comment by smaeda-ks** [comment]
Are you referring to "purge all"? Purge strategies can be quite varied depending on the customers/applications and I don't think adding this feature adds benefits for wider audiences (while I understand your use case).

Perhaps, `local-exec` would give you much more flexibility:
https://www.terraform.io/docs/language/resources/provisioners/local-exec.html

**Comment by smaeda-ks** [comment]
Also, VCL changes take some time to propagate across POPs (~90s, is not so stable). So an immediate purge upon activation may cause unexpected consequences (e.g., requests will still get processed by the old VCL version and may need to purge again). We would rather want customers to control the timing as necessary.

**Comment by virgofx** [comment]
Yeah I was referring to the purge all. Completely aware about the asynchronous 30 seconds plus timing to purge all. Would you be open to a pull request that adds this as a flag , opt in, with sufficient documentation addressing the limitations ?

**Comment by smaeda-ks** [comment]
Unfortunately, I wouldn't. Purge all is a feature we don't want customers to be relying on as part of their deployment workflow other than an emergency situation. I don't see much benefit in adding this as a new feature.

**Comment by virgofx** [comment]
Appreciate the update. Will close this request for now.

**Comment by smaeda-ks** [comment]
I appreciate your understandings. For those who are looking for a similar thing if any, I think `null_resource` is the convenient method and it's easy to add with something like this:

```
resource "null_resource" "purge_all" {
  triggers = {
    depends = fastly_service_v1.demo.active_version
  }

  provisioner "local-exec" {
    command = "sleep 60 && curl -sv -XPOST https://api.fastly.com/service/${fastly_service_v1.demo.id}/purge_all -H 'fastly-key: ${local.api_key}'"
  }
}
```

**Comment by virgofx** [comment]
That's exactly what we do :) Was just looking to remove the null_resource and local-exec because it's somewhat hackish and ideally not 100% operating system cross-compatible per say. But yes, that does work^. Thanks for the workaround.
