### ISSUE TITLE
Unable to upload/update intermediary certificate for `fastly_tls_certificate`

### ISSUE THREAD

**Issue by joshsouza** [fastly/terraform-provider-fastly#468]
### Terraform Version
1.0.5

### Affected Resource(s)
- fastly_tls_certificate

### Terraform Configuration Files
```hcl

# This uploads a CertLE-acquired certificate to Fastly
resource "fastly_tls_private_key" "this" {
  key_pem = local.private_key_pem
  name    = "example.com"
}

resource "fastly_tls_certificate" "this" {
  name             = "example.com"
  certificate_body = join("\n", [local.certificate_pem, local.intermediate_pem])
}

```

### Debug Output

```bash

Error: expected certificate_body to only contain one PEM-format block
│
│   with fastly_tls_certificate.this,

```

### Expected Behavior
The certificate and its intermediate should be uploaded to the Fastly API

### Actual Behavior
Terraform errors.
If you do not provide the intermediate, _some process_ acquires one, which may be incorrect.

### Steps to Reproduce
1. `terraform apply`

For complete reproduction:
1. Generate a certificate on LetsEncrypt and upload it to Fastly using this provider. (Needs to be issued by the R3 intermediate CA)
2. Ensure that the 'R3' intermediate certificate was not provided. 
3. Verify that the intermediate certificate being returned by Fastly is _not the newest_ R3 certificate (expires at the end of September)
4. Realize that without manually uploading the full chain, this cert will fail validation at the end of September.

### Important Factoids
We recently discovered that a certificate uploaded to Fastly via this provided (acquired from LetsEncrypt) had an old intermediate certificate that was about to expire.
Looking at our actual LetsEncrypt cert, it was properly issued, and had a proper (non-expiring) intermediate certificate. However this provider does not accept more than one certificate in the cert body, nor does it accept an intermediary certificate field. This is due to the `validatePEMBlock` code requiring only one PEM block be provided to the cert body.

There is no such limitation on the actual Fastly API itself, and we were able to upload the full certificate chain there to update the actual certificate manually, but would much prefer to have the certificate managed entirely through Terraform.

I have not yet tried forking/testing, but I assume that if there was logic in place to permit multiple PEM blocks on the `fastly_tls_certificate.certificate_body` field (and they were appropriately ordered), the Fastly API would accept them.

**Comment by smaeda-ks** [comment]
@joshsouza Thanks
By the way, the incorrect intermediate cert thing is a separate issue and I'd like to report that to an appropriate team. There's auto-discovery logic in place that covers most cases, and users should not be required to upload full chain in general.

Could you please share the cert ID in question?

Also, just curious... why do you want to upload your own LE certs in this case? If you're using Let's Encrypt you should consider issuing Let's Encrypt certs via Fastly TLS so that this will renew your certificates automatically, and you don't have to replace them every X months. And most importantly, there's no difference in pricing as we bill for the number of active TLS domains regardless of bring-your-own or Fastly TLS (managed).

**Comment by joshsouza** [comment]
A cert ID that is presently affected: `6AMoWrEyTSqf3K2KJ1bcbq`
We have reproduced this by creating a different certificate as well, and could do that on demand as needed.

If there is auto-discovery logic in place, how often does it run to ensure that the intermediary certs have not expired? We're within a month of expiration and it hasn't changed.

One reason why it would not be ideal to use Fastly to automatically renew (the reason we manage this cert ourselves) is when Fastly is not the only place a certificate will be used. I.E. when you use a wildcard cert.
We need a wildcard to handle `*.ourdomain` on Fastly, as well as on our own services. If Fastly was responsible for managing the certificate we would not be able to issue/manage that certificate on our own infrastructure as well. We could alternatively only have certificates with FQDNs on Fastly, but that leads to excessive propagation of domains to manage, and additional overhead in setting up and maintaining services (nevermind cost). We could also wire in some logic that messed around with the DNS whenever we needed to renew certificates outside of Fastly, but since the same DNS record is used for validation regardless of whether Fastly does it or we do it, that would impede automation, and greatly reduce reliability.

Thus we have automation in place on our end to renew the certificate centrally, and provide that certificate to Fastly and to our other systems.

I imagine we're not entirely alone in that need, but I could be wrong.

**Comment by smaeda-ks** [comment]
@joshsouza I see, so both issuers will be using the same CNAME record? (e.g., `_acme-challenge.example.com`)
then yes, that's a legit use case to me. Thanks for clarifying.

> If there is auto-discovery logic in place, how often does it run to ensure that the intermediary certs have not expired? We're within a month of expiration and it hasn't changed.

That process will only happen when the cert is uploaded, and we don't automatically replace the intermediary certs. That said, I'm currently talking to our TLS eng team to look into this. Thanks for the findings

**Comment by joeshaw** [comment]
@joshsouza Quick update on the wrong intermediate: we've fixed that on our end so that uploading just the leaf Let's Encrypt certificate will get the right intermediate now (R3 issued by ISRG Root X1).

**Comment by joshsouza** [comment]
@joeshaw Thanks! Appreciate the rapid response on that!
It might be a good idea to scan other folks certs and make sure anyone else in a similar boat is aware. We're pretty fortunate we had monitoring on this cert expiration, and I know there's folks out there that won't have that in place.

**Comment by joeshaw** [comment]
@joshsouza Yep, we're going to work on automatically updating these certs so they have the longer-lived intermediate.  I appreciate you looking out for everybody!

**Comment by joshsouza** [comment]
@joeshaw Awesome! Thanks again for all you folks do!

**Comment by smaeda-ks** [comment]
This has been fixed in: https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.35.0
