### ISSUE TITLE
edge dictionary documentation clarification

### ISSUE THREAD

**Issue by benzvan** [fastly/terraform-provider-fastly#470]
### Terraform Version
Documentation only
https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_v1

### Affected Resource(s)
Please list the resources as a list, for example:
- edge_dictionary

### Expected Behavior
Documentation states "should" but not "why"

### Actual Behavior
Documentation for creating a write-only dictionary states:
>Using a write-only/private dictionary should only be done if the items are managed outside of Terraform

Does this mean it will work but you shouldn't do it? Or does this mean it will fail (which is my suspicion)? Please add to the documentation indicating if it will fail or it is just not recommended.

**Comment by smaeda-ks** [comment]
Thanks for the feedback. In the meantime, you may read: https://github.com/fastly/terraform-provider-fastly/issues/442

**Comment by smaeda-ks** [comment]
So to recap,
the `fastly_service_v1` resource only manages the dictionary object itself, so you can create/delete a write-only dictionary using this resource. But, you can't manage "items" under the write-only dictionary using the `fastly_service_dictionary_items_v1` resource:
https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_dictionary_items_v1#limitations

We can be more clear about this, yes.

**Comment by benzvan** [comment]
Thank you so much for the fast feedback. It saves me the time of testing it out. Let me know if I can help update the documentation and resolve this issue.

**Comment by Integralist** [comment]
I'm going to close this issue now that @smaeda-ks' PR to update the documentation has been merged. 

> **NOTE**: This documentation won't be published to https://registry.terraform.io/providers/fastly/fastly/latest/docs until we cut a new Terraform provider release.
