### ISSUE TITLE
Improve service_dictionary_items_v1 documentation - index access instead of foreach

### ISSUE THREAD

**Issue by JiriKovar** [fastly/terraform-provider-fastly#476]
Hi there,

I found the for_each for finding the dictionary ID confusing (I could not understand the purpose until I looked into the terraform state file). The documentation would look like this:

```
locals {
  dictionary_ids = { for d in  fastly_service_v1.myservice.dictionary : d.name => d.dictionary_id }
}

resource "fastly_service_dictionary_items_v1" "items" {
  service_id = fastly_service_v1.myservice.id
  dictionary_id = local.dictionary_ids[var.mydict_name]

  items = {
    key1: "value1"
    key2: "value2"
  }

  lifecycle {
    ignore_changes = [items,]
  }
}
```

I think it would be better to use standard access by index, since there really is no cycle going on (the resource is applied exactly 0-1 times). In case the dictionary is not found by the name, for example due to a typo, the implementation with for_each would be silently skipped, compared to an error in case of accessing by index (which is desirable, I think - fail fast)

Am I missing something? Would you be willing to improve it?

Thank you very much!

**Comment by JiriKovar** [comment]
I'm sorry, there was an error in the sample I provided. I fixed it in the original comment. 

It could possibly be all in the one line (below), but I think adding a local variable makes the most sense. 

`dictionary_id = { for d in fastly_service_v1.deliver_assets.dictionary : d.name => d.dictionary_id }[local.projectdomains_dictionary_name]`

**Comment by smaeda-ks** [comment]
@JiriKovar 

> the resource is applied exactly 0-1 times

if there are more than one `dictionary` blocks in the `fastly_service_v1` resource, I think it still makes sense to use `for_each` because then you don't have to write multiple `fastly_service_dictionary_items_v1` resources.

**Comment by brycefisher** [comment]
@smaeda-ks -- I concur with @JiriKovar. The suggestion above would make the code much more approachable, especially for folks who aren't as familiar with HCL sets being used here. I would have expected a map of dictionaries indexed by dictionary name, so that we could dispense with the `locals` resource in the original comment.
