### ISSUE TITLE
FR: Resource to add API Tokens

### ISSUE THREAD

**Issue by timkelty** [fastly/terraform-provider-fastly#488]
We can create users with `fastly_user_v1`, but create/attach an api token.
This would be very helpful.

**Comment by smaeda-ks** [comment]
One thing to note is that you can't create tokens on behalf of users in the account. You can create users via TF provider, yes, but then you can't create tokens for someone else via TF provider.
If we create a new resource, the token is still created under the account associated with the token you set in the provider configuration.

**Comment by timkelty** [comment]
@smaeda-ks makes sense, thanks.

**Comment by smaeda-ks** [comment]
@timkelty yeah, so I guess this wouldn't give you much ability and hence not worth considering to support for now. Would you agree? then we can probably close this issue. We could revisit once Fastly platform had the ability to create account-level API tokens.

**Comment by timkelty** [comment]
Given that limitation, I would probably just create an explicit "Terraform" superuser in Fastly, use that for the Fastly provider creds, and have all the created tokens attached to that.

Seems like that would work, but yeah, not ideal.

> We could revisit once Fastly platform had the ability to create account-level API tokens

Is that slated to happen? Unless I'm mis-remembering, you used to be able to do this, and it was converted to user-only tokens.

**Comment by smaeda-ks** [comment]
> Is that slated to happen?

I don't have ETA to share but I believe we have a plan in progress.

**Comment by timkelty** [comment]
That's great news! User-only ones are quite awkward.

**Comment by smaeda-ks** [comment]
Closing this ticket for now since the blocker is at our product side. We can revisit when it's actually available.

**Comment by segiddins** [comment]
Given [automation tokens](https://developer.fastly.com/reference/api/auth-tokens/automation/) exist, this seems doable now?
