### ISSUE TITLE
Support "Redirect traffic to www subdomains"

### ISSUE THREAD

**Issue by timkelty** [fastly/terraform-provider-fastly#490]
The "Redirect traffic to www subdomains" setting does not appear to be supported at all by the `fastly_service_v1` resource.
![CleanShot 2021-10-19 at 16 57 02](https://user-images.githubusercontent.com/18329/137989368-7b369e60-912c-45cf-ab08-0c9d8be6b9ac.png)

### Affected Resource(s)
- `fastly_service_v1`

**Comment by smaeda-ks** [comment]
We can discuss this in #489. Closing
