### ISSUE TITLE
Regex with "|6" or any number following a "|" is transformed into [] during terraform apply

### ISSUE THREAD

**Issue by lorantfecske** [fastly/terraform-provider-fastly#495]
### Terraform Version
0.14.11

### Fastly provider versions
0.36.0 and 0.37.0

### Terraform resource
resource "fastly_service_v1" "site" 

### Terraform Configuration Files (it is actually in the VCL file containing regexes)
```hcl
  # CSRF checks
  if (req.request == "POST" && (req.url ~ "(?i)^\/api\/(nag\/v(1|2)|schools\/employers)) {
....
}
```

### Expected Behavior
Terraform runs without problems

### Actual Behavior
```
Error: [ERR] Invalid configuration for Fastly Service (1hqqjSsLahdNTS03qjI9Y3): Syntax error: Regexp compilation error:  
range out of order in character class
at: (input Line 7891 Pos 43)
  if (req.request == "POST" && (req.url ~ "(?i)^\/api\/(nag\/v(1[])|schools\/employers)) {
  .....
  ```

### Steps to Reproduce
Update your provider 036.0 then run terraform

### Important Factoids
It seems that the change in the pullrequest is also altering regexes in the VLC file 

### References
The pull-request seems to cause this is: https://github.com/fastly/go-fastly/pull/304

**Comment by smaeda-ks** [comment]
Thank you @lorantonodi, we're working on the fix.

**Comment by smaeda-ks** [comment]
Hi @lorantonodi, we've released a new version that should fix this issue:
https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.38.0

Let me know if you still see issues. Appreciate your feedback.

**Comment by lorantfecske** [comment]
Solved the problem on our side, thanks for the rapid fix.
