### ISSUE TITLE
Could not change "placement" option to Default

### ISSUE THREAD

**Issue by prakash-fb** [fastly/terraform-provider-fastly#505]
The placement option for Logentries is either 'none' or 'Format Version Default'. When using 'none' I do not see the logs in the logentries.com. But there is no option to set it to default in terraform. How to set placement to Format Version Default?

### Terraform Version
v1.0.8

### Affected Resource(s)
- logentries

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
logentry = [
    {
      "name"               = "logs"
      "token"              = var.log_token
      "format"             = "..."
      "format_version"     = "2"
      "port"               = "443"
      "placement"          = "none" <== Issue is here
      "response_condition" = "some conditions"
      "use_tls"            = "true"
    }
]
```

### Debug Output
https://gist.github.com/prakash-fb/de42422717dea9e4de95d1946dad9be6

### Expected Behavior
What should have happened?
Should be able to set 'none' to 'Default'

### Actual Behavior
What actually happened?
It is showing either to choose 'none' or 'waf_debug'

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Try adding logentries using terraform
2. Run `terraform plan`

**Comment by smaeda-ks** [comment]
@prakash-fb the `Format Version Default` option in the UI is equal to not setting the `placement` attribute at all and set `format_version  = "2"` in your `logentry` block.

What happens if you just remove `placement` line?

**Comment by prakash-fb** [comment]
@smaeda-ks Hello, I have set the value of placement to `""` before, but it didn't work. Are you suggesting removing `placement` from the config? Doing so will result in the error - **attribute "placement" is required**

**Comment by smaeda-ks** [comment]
@prakash-fb 
https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_v1#nested-schema-for-logentries
`placement` is an optional attribute. What is your Fastly TF "provider" version?

**Comment by prakash-fb** [comment]
Never mind. You were right, the error Placement is required was because of the variable I set. After I removed it, I can see it is now set to **Format Version Default**.
