### ISSUE TITLE
Fastly pulumi no longer works after v0.32.0

### ISSUE THREAD

**Issue by StarpTech** [fastly/terraform-provider-fastly#507]
As titled. More info see https://github.com/pulumi/pulumi-fastly/issues/119
Pulumi API broke in release https://github.com/fastly/terraform-provider-fastly/blob/main/CHANGELOG.md#0330-july-16-2021

According to the error message this might be the root issue https://github.com/fastly/terraform-provider-fastly/pull/446/files

**Comment by StarpTech** [comment]
@smaeda-ks feel free to contact me. I can assist or try out new versions.

**Comment by smaeda-ks** [comment]
To be clear, pulumi-fastly is not officially maintained by us. It was started unofficially by the community is my understanding.

As the recent discussion in https://github.com/pulumi/pulumi-fastly/issues/119 suggests, it's too early for us to start digging into this. Furthermore, it doesn't look like we're accountable for this or the issue belongs to us.

We do carefully release new versions by running heavy acceptance tests but whether pulumi-fastly works with them is not in our criteria.

I'm closing this issue for now.
