### ISSUE TITLE
Unsupported argument "format" for newrelic logging in compute service

### ISSUE THREAD

**Issue by StarpTech** [fastly/terraform-provider-fastly#508]
Hi, it looks like that we can't apply the logging format for a compute service. This is a blocker for us.
```
│ Error: Unsupported argument
│ 
│   on compute_service.tf line 38, in resource "fastly_service_compute" "test_dev":
│   38:     format = file("${path.module}/fastly-newrelic-log.tpl")
│ 
│ An argument named "format" is not expected here.

```

**Comment by kailan** [comment]
Hi @StarpTech – log format strings are not supported in Compute@Edge. The logs will be sent to the endpoint as logged by your app.

More info about the log format string: [Automatic logging in VCL](https://developer.fastly.com/learning/integrations/logging/#automatic-logging-in-vcl)

If you would like to log requests, this can be done in your edge code: [Logging – VCL vs Compute@Edge](https://developer.fastly.com/learning/integrations/logging/#vcl-vs-computeedge)

**Comment by StarpTech** [comment]
Hi @kailan, thanks for the fast response. I forgot it. You're right. Thanks.
