### ISSUE TITLE
How to add multiple backends dynamically on the same service?

### ISSUE THREAD

**Issue by StarpTech** [fastly/terraform-provider-fastly#509]
Hi, I'd like to create multiple backends via variable or locale data. Any help would be appreciated.

```tf
variable "backends" {
  type = list(object({
    address = string
    shield  = string
  }))
  default = [
    {
      address = "foo.com"
      shield  = "frankfurt-de"
    }
  ]
}

resource "fastly_service_v1" "service" {
   backend { ... }
}
```

**Comment by StarpTech** [comment]
Could solve it with https://www.terraform.io/docs/language/expressions/dynamic-blocks.html

**Comment by Integralist** [comment]
@StarpTech Ah yes I've written about Dynamic Blocks in our developer hub: https://developer.fastly.com/learning/integrations/orchestration/terraform/#configurability-with-dynamic-blocks

**Comment by StarpTech** [comment]
@Integralist thanks for the good resource.
