### ISSUE TITLE
fastly_tls_subscription with apex domain and wildcard is excessively complex

### ISSUE THREAD

**Issue by ohookins** [fastly/terraform-provider-fastly#513]
### Terraform Version
1.0.11

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_tls_subscription
- fastly_tls_subscription_validation
- some DNS record using the provider of your choice

### Terraform Configuration Files
```hcl
resource "fastly_tls_subscription" "example" {
  domains               = ["example.com", "*.example.com"]
  certificate_authority = "lets-encrypt"

  depends_on = [fastly_service_v1.example_com]
}

resource "aws_route53_record" "domain_validation" {
  depends_on = [fastly_tls_subscription.example]

  for_each        = {
    for domain in fastly_tls_subscription.example.domains : domain => element([
      for obj in fastly_tls_subscription.example.managed_dns_challenges :  obj if obj.record_name == "_acme-challenge.${domain}"
    ], 0)
  }
  name            = each.value.record_name
  type            = each.value.record_type
  zone_id         = data.aws_route53_zone.demo.id
  allow_overwrite = true
  records         = [each.value.record_value]
  ttl             = 60
}
```

### Debug Output
Regular output, debug unnecessary:

```
fastly_tls_subscription.example: Creation complete after 3s [id=xxxx]
╷
│ Error: Error in function call
│
│   on tls-subscription-example.tf line 17, in resource "cloudflare_record" "example_validation":
│   17:     domain => element([
│   18:       for obj in fastly_tls_subscription.example.managed_dns_challenges :
│   19:       obj if obj.record_name == "_acme-challenge.${domain}"
│   20:     ], 0)
│     ├────────────────
│     │ fastly_tls_subscription.example.managed_dns_challenges is set of object with 1 element
│
│ Call to function "element" failed: cannot use element function with an empty list.
╵
```

### Panic Output
N/A

### Expected Behavior
DNS Challenge records created for the TLS subscription.

### Actual Behavior
Error above.

Since the apex domain and wildcard subdomain records on the certificate subscription have the same challenge, only one DNS record can be created. However, a secondary Terraform issue is that the filtering above in the `for_each` block will exclude the wildcard, since the DNS validation record_name only contains the apex domain name, and not the `*.` prefix. Therefore, the filter doesn't match, and the `element()` function attempts to pull the first record out of an empty list.

Alternatively, we can attempt to use `try()` to set a default value if `element()` doesn't work, but then we run into the usual problem of eliminating nulls in Terraform lists and that is another complex problem to be solved.

In my case, I think the only option I have at the moment that isn't exceedingly complex is to use the deprecated `managed_dns_challenge` attribute of the `fastly_tls_subscription` object, so that I only take the first value (and only use it in this particular situation). However, without changing Terraform language, it's hard to think of an alternative in this provider. Perhaps the provider could eliminate the duplicate identical challenge for the wildcard?

### Steps to Reproduce
1. `terraform apply`

**Comment by smaeda-ks** [comment]
@ohookins `replace` works?

```tf
  for_each        = {
    for domain in fastly_tls_subscription.example.domains : domain => element([
      for obj in fastly_tls_subscription.example.managed_dns_challenges :  obj if obj.record_name == "_acme-challenge.${replace(domain, "*.", "")}"
    ], 0)
  }
```

**Comment by ohookins** [comment]
@smaeda-ks won't that result in attempting to create two validation records with the same record name?

**Comment by smaeda-ks** [comment]
@ohookins  It will. But the validation record values would be the exact same for those domains as long as they're on the same cert (e.g., `example.com` and `*.example.com` requires a validation record on `example.com` with the same value), so it will just override with the same value and shouldn't cause a real-world problem. As long as you set the `allow_overwrite` attribute to `true` they use upsert operation so that's fine.
https://github.com/hashicorp/terraform-provider-aws/blob/v3.69.0/internal/service/route53/record.go#L421-L429

**Comment by ohookins** [comment]
We're not actually using Route53 for DNS, I was using that as an example. Creating duplicate records doesn't work for us and errors out so I don't view this as a solution.

**Comment by smaeda-ks** [comment]
What provider are you using?

**Comment by ohookins** [comment]
That's not something I'm comfortable disclosing here. The original issue as I reported it stands - there's excessive working around a problem here that could be solved more gracefully by the fastly provider.

**Comment by smaeda-ks** [comment]
another easy workaround would be to use ellipsis `...` and only reads the first element in the list. 

```tf
resource "aws_route53_record" "domain_validation" {
  depends_on = [fastly_tls_subscription.example]

  for_each = {
    for domain in fastly_tls_subscription.example.domains :
    # remove "*." from the key as well
    replace(domain, "*.", "") => element([
      for obj in fastly_tls_subscription.example.managed_dns_challenges :
      obj if obj.record_name == "_acme-challenge.${replace(domain, "*.", "")}"
    ], 0)...
  }

  name            = each.value[0].record_name
  type            = each.value[0].record_type
  zone_id         = data.aws_route53_zone.demo.id
  allow_overwrite = true
  records         = [each.value[0].record_value]
  ttl             = 60
}
```

**Comment by smaeda-ks** [comment]
or, maybe just this works

```tf
  for_each = {
    for challenge in fastly_tls_subscription.example.managed_dns_challenges :
    trimprefix(challenge.record_name, "_acme-challenge.") => challenge
  }
```

**Comment by smaeda-ks** [comment]
@ohookins I've opened #516, but let me know if either solution works for you. Thanks

**Comment by ohookins** [comment]
I've been using this:

```hcl2
locals {
  toplevel_domains_without_wildcard = [
    for domain in fastly_tls_subscription.toplevel_domain.domains : domain if substr(domain, 0, 2) != "*."
  ]
}

resource "dns_record" "toplevel_domain_validation" {
  depends_on = [fastly_tls_subscription.toplevel_domain]

  for_each = {
    for domain in local.toplevel_domains_without_wildcard : domain => element([
      for obj in fastly_tls_subscription.toplevel_domain.managed_dns_challenges : obj if obj.record_name == "_acme-challenge.${domain}"
    ], 0)
  }
```

Although there's also a problem here if you have a cert for the wildcard but not the apex domain, as the latter challenge will be stripped. Unfortunately Terraform does not have the language constructs for very nicely dealing with this.

**Comment by smaeda-ks** [comment]
Thanks. My solution above should work better.

**Comment by smaeda-ks** [comment]
Closing for now as #516 is merged. Thank you for your feedback.
