### ISSUE TITLE
Provider Website should be updated to match docs

### ISSUE THREAD

**Issue by agilgur5** [fastly/terraform-provider-fastly#52]
Current website (https://www.terraform.io/docs/providers/fastly/r/service_v1.html) does not seem to reflect the documentation.

A pretty quick example to show this was that the `use_ssl` option is not even mentioned on the website, nor a bunch of other SSL configurations.

See attached screenshot of this (note that `healthcheck` is the last option under `backend`, so there are no more options further down):
<img width="852" alt="screen shot 2017-10-18 at 9 46 16 pm" src="https://user-images.githubusercontent.com/4970083/31754933-c7602b92-b44f-11e7-8d80-351034ae00c7.png">

**Comment by Constantin07** [comment]
but it's available in state output thought:
```
...
backend.2620238361.use_ssl                  = true
...
```

**Comment by smaeda-ks** [comment]
This issue seems to be stale. I'm going to close this for now.

**Comment by agilgur5** [comment]
It looks like the [`docs`](https://github.com/fastly/terraform-provider-fastly/tree/38ebaea6c3da671a0f34030dcdd43b4426528393/docs) folder here now _is_ the provider website and there's a CI workflow for generating the docs for the provider website [here](https://github.com/fastly/terraform-provider-fastly/blob/75f826c9e9577f1ee64fbd0bb456475b1b977c78/.github/workflows/pr.yml#L59).

So this ~4.5 year old issue indeed seems to no longer be relevant. This was still under the `terraform-providers` org back then; quite a bit has changed since then.
