### ISSUE TITLE
Support `activate` attribute for WAF

### ISSUE THREAD

**Issue by Integralist** [fastly/terraform-provider-fastly#529]
Customer is using Terraform to deploy VCL and Fastly WAF. 

There is an [`activate`](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_v1#optional) option for deploying VCL (so the customer can control to activate the service when they want), but there is no option like that for Fastly WAF. This means when the customer runs `terraform apply` for WAF it will attempt to activate.

**Comment by smaeda-ks** [comment]
Merged #530
