### ISSUE TITLE
S3 logging doesn't support SSE

### ISSUE THREAD

**Issue by sjparkinson** [fastly/terraform-provider-fastly#53]
The s3logging block works a treat, however there are no options to enable the server-side encryption using Terraform.

See https://docs.fastly.com/api/logging#logging_s3, under `server_side_encryption_kms_key_id` and `server_side_encryption`.

### Affected Resource(s)

- s3logging

**Comment by smaeda-ks** [comment]
Closing as they had been added: https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_v1#nested-schema-for-s3logging
