### ISSUE TITLE
terraform state issue with provider 1.0.0

### ISSUE THREAD

**Issue by Calange** [fastly/terraform-provider-fastly#541]
### Terraform Version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/fastly/fastly v1.0.0
+ provider registry.terraform.io/hashicorp/aws v3.74.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

- fastly_service_acl_entries_v1
- fastly_service_v1

### Terraform Configuration Files

I updated all the resources to be compatible with the provider 1.0.0, I changed things like that:

`resource "fastly_service_v1" "environment"`  to `resource "fastly_service_vcl" "environment"`

`resource "fastly_service_acl_entries_v1" "deny_ip_ranges"` to `resource "fastly_service_acl_entries" "deny_ip_ranges"`

### Actual Behavior

I got this output when I try to do terraform plan/apply:

```
Error: no schema available for module.fastly.fastly_service_acl_entries_v1.deny_ip_ranges while reading state; this is a bug in Terraform and should be reported

Error: no schema available for module.fastly.fastly_service_acl_entries_v1.internal_ip_ranges while reading state; this is a bug in Terraform and should be reported

Error: no schema available for module.fastly.fastly_service_v1.environment while reading state; this is a bug in Terraform and should be reported
```

How can I fix/update the state without destroying any resources?

Thank you for your help 🙏

### References
- [1.0.0](https://github.com/fastly/terraform-provider-fastly/releases/tag/v1.0.0)

**Comment by Integralist** [comment]
Hi @Calange 

Thanks for raising this issue. You didn't mention if your ACL entries were seeded via the HCL Terraform configuration file or if those were managed externally. **Please could you let me know**, thanks.

Meanwhile, I was able to setup a reduced test case to validate this by creating a basic VCL service, along with some seeded ACL entries, using the version of the Terraform provider prior to the `1.0.0` release, which was version `0.41.0`. 

Once I had the service activated I updated the Terraform provider to version `1.0.0` and then re-ran a plan and got a similar error to yourself.

The resolution I found was to remove the old resource from the state and to reimport it, something like the following (obviously the brackets `<...>` should be replaced with actual values):

```bash
terraform state rm 'fastly_service_acl_entries_v1.<your_resource_name>["<your_acl_name>"]'
terraform import 'fastly_service_acl_entries.<your_resource_name>["<your_acl_name>"]' <service_id>/<acl_id>

terraform state rm 'fastly_service_v1.<your_resource_name>'
terraform import 'fastly_service_vcl.<your_resource_name>' <service_id>
```

This worked for me, but I've yet to test with ACL entries that were being managed externally from the Terraform configuration. So if that is how your service is setup, then please let me know so I can also try to validate that scenario (if that is the case, then I also presume that your original configuration would have used `ignore_changes`).

**Comment by Integralist** [comment]
**UPDATE**: I've also validated this with a reduced test case where I define an `acl` resource but I do not seed any entries via the HCL Terraform configuration (so no `ignore_changes` defined in the HCL). 

Once I upgrade to the Fastly Terraform provider version `1.0.0` and go through the steps of removing the old service resource from the state and reimporting it under the new resource name, and then I plan/apply those changes. The ACL entries were not affected (i.e. they still exist within the version 2 of the service that was activated).

**Comment by Integralist** [comment]
**UPDATE 2**: I've now also validated this works with a reduced test case where the `acl` resource is seeded with entries via the HCL Terraform configuration and I also externally add entries via the Fastly API, meaning I need to utilise `ignore_changes` to prevent Terraform from removing the entries added externally to the HCL.

I upgrade the version to `1.0.0`, then do the `state rm` and `import` steps before re-running a plan and apply. It succeeds and all the ACL entries (those defined in the HCL and those I added externally) persist.

Finally, because my service is now using the Fastly Terraform provider version `1.0.0`, I remove the use of `ignore_changes` which was only necessary prior to `1.0.0` to help protect against data loss when entries were added outside of Terraform (the 'ignore changes' behaviour is now the default unless overridden using the `manage_entries` attribute).

**Comment by Integralist** [comment]
@Calange Along with my above comments I would also suggest keeping a backup of your state file so you can use it to reference any resource IDs. For now I'm going to close this issue. If you have any further questions then feel free to continue commenting in this thread.

**Comment by Calange** [comment]
Hello @Integralist, thank you very much for your reply.

I confirm you that my ACL entries are seeded via the HCL Terraform configuration file. I will try to do the `state rm` and `import` to fix the state like you suggest (and also do a backup of the state before). 

I will keep you informed If everything goes well 🤞.

**Comment by Calange** [comment]
Hello @Integralist, my terraform state is now fix with `state rm` and `import` like you suggest 🎉.

It would be nice to add the procedure into the Migration Guide If someone have the same issue.

**Comment by Integralist** [comment]
Thanks for the update @Calange I 💯 % agree this should be in the migration guide. I'll get that added 👍🏻
