### ISSUE TITLE
Ability to create a private edge dictionary

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#544]
Maybe this is any feature request, I am curious if there is any capability of creating a private edge dictionary throughout terraform code. Thanks!

**Comment by Integralist** [comment]
Hi @chenrui333 it's possible to create a private dictionary using the [`write_only` attribute](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl#nested-schema-for-dictionary), but as mention in [this thread](https://github.com/fastly/terraform-provider-fastly/issues/442#issuecomment-880380438) from last year, it isn't possible for Terraform to manage the contents of a private dictionary as we can't read the dictionary's items using the API and so Terraform can't generate a diff and determine state drift.
