### ISSUE TITLE
dynamic snippet content does not update on change

### ISSUE THREAD

**Issue by joeypiccola** [fastly/terraform-provider-fastly#555]
Hello, 

I noticed that when updating the value of `content` on the `fastly_service_dynamic_snippet_content` resource it does not actually update the content with my recent changes (Terraform doesn't even see the change).

Thanks for taking a look!

### Terraform Version
```
➜ t -v
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/fastly/fastly v1.1.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `fastly_service_dynamic_snippet_content`

### Terraform Configuration Files
```hcl
resource "fastly_service_vcl" "my_service" {
  name = "my_service"

  domain {
    name    = "{insert valid domain name}"
    comment = "my_comment"
  }

  backend {
    address = "{insert valid backend address}"
    name    = "my_backend"
    port    = 80
  }

  acl {
    name = "my_acl"
  }

  dynamicsnippet {
    name     = "my_dynamicsnippet"
    type     = "recv"
    priority = 110
  }

  force_destroy = true
}

resource "fastly_service_dynamic_snippet_content" "my_ds_content" {
  for_each = {
    for d in fastly_service_vcl.my_service.dynamicsnippet : d.name => d if d.name == "my_dynamicsnippet"
  }

  service_id = fastly_service_vcl.my_service.id
  snippet_id = each.value.snippet_id
  content = <<-EOT
    if (client.ip ~ my_acl) {
      error 403 "blocked";
    }
  EOT
}

resource "fastly_service_acl_entries" "my_acl_entries" {
  for_each = {
    for d in fastly_service_vcl.my_service.acl : d.name => d if d.name == "my_acl"
  }

  service_id = fastly_service_vcl.my_service.id
  acl_id = each.value.acl_id
  entry {
    ip = "{insert valid ip}"
    comment = "my_comment"
  }
}
```

### Debug Output
Can provide if needed. 

### Panic Output
None.

### Expected Behavior
When updating the `content` property of `fastly_service_dynamic_snippet_content` Terraform should recognize this change and update the dynamic VCL snippet.

### Actual Behavior
Terraform does not update the content of a dynamic VCL snippet when the `content` property of `fastly_service_dynamic_snippet_content` is udpated. 

### Steps to Reproduce
Apply the simple three resource config above. Update the content block of the `fastly_service_dynamic_snippet_content` resource (e.g. modify the error message or add additional VCL). Apply the config again, Terraform reports `No changes. Your infrastructure matches the configuration.`.

### Important Factoids
None other than the same issue exists for the `comment` property of the `fastly_service_acl_entries` resource (will open another issue). 

### References
None.

**Comment by Integralist** [comment]
Hi @joeypiccola thanks for raising this issue.

You need to set `manage_snippets = true` inside the `fastly_service_dynamic_snippet_content` resource.

If you refer to the [`fastly_service_dynamic_snippet_content` documentation](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_dynamic_snippet_content) you'll see the following note...

<img width="660" alt="Screenshot 2022-03-07 at 10 56 45" src="https://user-images.githubusercontent.com/180050/157018376-65566eaf-8231-496f-8cfe-795cf1acc0e9.png">

See also (in the same documentation page) the section ["Reapplying original snippets with `manage_snippets` if the state of the snippets drifts"](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_dynamic_snippet_content#reapplying-original-snippets-with-manage_snippets-if-the-state-of-the-snippets-drifts) which explains the attribute in more detail as well as the warning: 

<img width="660" alt="Screenshot 2022-03-07 at 10 59 38" src="https://user-images.githubusercontent.com/180050/157018773-214abdd5-cd8f-4bbc-a90c-e4b6e4b0e807.png">

This is a fundamental change introduced in the `1.0.0` major release of the Fastly Terraform provider. If you refer to the [migration guide](https://registry.terraform.io/providers/fastly/fastly/latest/docs/guides/migration-guide-1.0.0) section titled "Automatically opt-in to `ignore_changes` behaviour for versionless resources" it explains this change, which affects all versionless resources (including Dynamic VCL Snippets, ACL entries and Dictionary items), in more detail:

> The versionless resources (ACL entries, Dictionary items and Dynamic VCL Snippets) are sometimes used in a way whereby they are "seeded" via Terraform and then updated/managed externally via the API or web interface. For this, the documentation suggests using `ignore_changes`, a built-in Terraform meta-argument, that allows the user to specify fields to ignore and from which to allow the state to drift.
> 
> However, sometimes this isn't obvious or the user doesn't understand this suggestion until it is too late, and data ends up getting lost. This happens because the user makes changes elsewhere and doesn't use `ignore_changes`, so Terraform takes action to remove the state drift and deletes their changes. This data is then unrecoverable.
>
> Starting from version 1.0.0, Terraform now ignores any changes, and only allows the "dangerous" behaviour by explicitly opting in with a `manage_*` option (e.g. `manage_entries`, `manage_items`, `manage_snippets` depending on the versionless resource).
