### ISSUE TITLE
If you generate a .tfstate file from a pre-existing project, create a Terraform script, and then run terraform plan, the plan will show that you will clobber all pre-existing configurations

### ISSUE THREAD

**Issue by TMFEspresso** [fastly/terraform-provider-fastly#556]
### Terraform Version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/fastly/fastly v0.41.0

### Affected Resource(s)
- fastly_service_v1

It technically affects any resource though.

### Expected Behavior
Pre-existing configs in a pre-existing project should be left unchanged, since they exist in the tfstate file and were not defined to be changed in the Terraform script.

### Actual Behavior
Terraform thinks it should clobber existing configs. Basically, this, but on every single config:

```
Terraform will perform the following actions:

  # fastly_service_v1.www-testing will be updated in-place
  ~ resource "fastly_service_v1" "www-testing" {
      + activate           = true
      ~ active_version     = 1337 -> (known after apply)
      ~ cloned_version     = 775 -> (known after apply)
      + force_destroy      = false
        id                 = "REDACTED"
        name               = "www-testing"
        # (3 unchanged attributes hidden)



      - cache_setting {
          - cache_condition = "Store" -> null
          - name            = "Store - no cache" -> null
          - stale_ttl       = 0 -> null
          - ttl             = 0 -> null
        }
      - cache_setting {
          - cache_condition = "charts" -> null
          - name            = "indexchart" -> null
          - stale_ttl       = 120 -> null
          - ttl             = 120 -> null
        }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have a pre-existing Fastly service
2. Make literally any Terraform script that works with this provider and the pre-existing project
3. Run `terraform import`
3. Run `terraform plan`

### Important Factoids
Trying to tell Terraform that it should most assuredly use the pre-existing infra instead of throwing it out also does not work:

```
terraform import fastly_service_v1.www-testing www-testing
fastly_service_v1.www-testing: Importing from ID "www-testing"...
fastly_service_v1.www-testing: Import prepared!
  Prepared fastly_service_v1 for import
╷
│ Error: Resource already managed by Terraform
│ 
│ Terraform is already managing a remote object for fastly_service_v1.www-testing. To import to this address you must first remove the
│ existing object from the state.
╵
```

**Comment by Integralist** [comment]
Hi @TMFEspresso 

I've historically found importing an existing service into Terraform to be quite ...fiddly (and something that needs work and improved documentation for).

Could you try the steps in the following gist I wrote (it's old but the general steps should still apply I think):

https://gist.github.com/Integralist/2b4298d4d287376b8a939c4e9eadd693

Let me know if this helps at all.

Thanks!

**Comment by Integralist** [comment]
There's been no further feedback so I'm going to close off this ticket. 

Please feel free to continue the conversation, or to re-open, if you need to.

Thanks.
