### ISSUE TITLE
Typo in TF provider doc/info

### ISSUE THREAD

**Issue by emelgar-tek** [fastly/terraform-provider-fastly#557]
There is a reference to fastly_tls_custom_certificate resource here: 

https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/tls_private_key

I believe that should be titled fastly_tls_certificate

**Comment by agilgur5** [comment]
Could make a PR to fix [that line](https://github.com/fastly/terraform-provider-fastly/blame/2c421c0b1e2eade806549e6803a84b3c9cfb1964/docs/resources/tls_private_key.md#L11) yourself; the docs are hosted in this repo 🙂
