### ISSUE TITLE
[question] with provider 1.x.x, how can I have terraform manage WAF list

### ISSUE THREAD

**Issue by chenrui333** [fastly/terraform-provider-fastly#558]
With the provider 1.x.x upgrade, I noticed that I got opted into `ignore_changes` by default for WAF config setup. How can I update the config to have terraform config to manage the ip blocklist again?

The rationale of having terraform config to manage the ip blocklist have two major benefits:
- we already have a established workflow to deploy the change
- It would help reduce the duplicates when manually doing the change

Thanks!

**Comment by hrmsk66** [comment]
Hi @chenrui333 
Yes, that is a change introduced in the 1.0.0 release of the Fastly Terraform provider.
If you refer to the [migration guide](https://registry.terraform.io/providers/fastly/fastly/latest/docs/guides/migration-guide-1.0.0) section titled "**Automatically opt-in to ignore_changes behaviour for versionless resources**" it explains this change


To make Terraform config be the source of truth, please set `manage_entries = true` inside the fastly_service_acl_entries resource. Applying `managed_entries=true` will remove externally managed ACL entries, so you may want to add those entries to your Terraform configuration file.

Thanks.

**Comment by chenrui333** [comment]
Got it, gonna give it a try now.
