### ISSUE TITLE
data source fastly_tls_configurations with default = true can return more than one result

### ISSUE THREAD

**Issue by oopsbagel** [fastly/terraform-provider-fastly#566]
Hi folks, thanks for your great work on this provider. I ran into a bug where accounts with a *single* TLS configuration (not the norm) can cause an unexpected error due to how pagination is handled. I link to a fix below.

### Terraform Version
1.1.7

### Affected Resource(s)
- data.fastly_tls_configuration

### Terraform Configuration Files
This is relevant if you have ONE tls configuration -- the bug is not present if you have between 2 and 100.
```hcl
data "fastly_tls_configuration" "default" {
  default = true
  # bug is also present if you specify the name or any other attribute besides id
}

output "id" {
  value = data.fastly_tls_configuration.default.id
}
```

### Debug Output
I am willing to share this debug output with a Fastly support engineer, but it contains too much sensitive information to be worth redacting for the public internet. The key behaviour is visible when the account has a single TLS configuration: you can see the provider make a request to `/tls/configurations`, receive a page with a single record, then make a request to `/tls/configurations?page[number]=1`, receive the same page with a single record, then make a request to `/tls/configurations?page[number]=2` and stop. The bug fix linked below contains an explanation of the root cause of the bug.

In the case where there are more than 100 records (the default page size of the /tls/configurations endpoint): the provider would make a request to `/tls/configurations`, receive a page with the first 100 records, then request `tls/configurations?page[number]=100` instead of `tls/configurations?page[number]=2` and so on.

### Expected Behavior
The data source should correctly resolve the default TLS configuration in my Fastly account.

### Actual Behavior
Terraform exited with:
```
Error: Your query returned more than one result. Please change try a more specific search criteria and try again.

  with data.fastly_tls_configuration.default,
  on main.tf line 1, in data "fastly_tls_configuration" "default":
  data "fastly_tls_configuration" "default"
```

### Steps to Reproduce
0. Create an account with only one Fastly TLS configuration, set to default.
1. `terraform apply`

### Important Factoids
Remember, this bug is only present if you have ONE TLS configuration (not the norm) or over 100 (the default page size for the `/tls/configurations` endpoint).

### References
- https://github.com/fastly/terraform-provider-fastly/pull/565

**Comment by Integralist** [comment]
Thanks @oopsbagel for opening this issue (and the associated PR!) I'll take a look over this and your PR ASAP.
