### ISSUE TITLE
[Feature Request] BigQuery Logging config should support IAM impersonation

### ISSUE THREAD

**Issue by sakajunquality** [fastly/terraform-provider-fastly#601]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.3.2

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_vcl/logging_bigquery 

### Expected Behavior

Credential-less Authorization using IAM impersonation is avaiable now for Google BigQuery, Cloud Storage, and Pub/Sub
The provider should support this as well.

https://www.fastly.com/blog/easy-identity-access-management-across-google-bigquery-cloud-storage-and-pub
https://docs.fastly.com/en/guides/configuring-google-iam-service-account-impersonation-for-fastly-logging

### Actual Behavior
Cannot configure with the following errors

```
    Title:  Bad request
    Detail: credential validation error: "if no account name is provided, both a user and secret key must be provided"
```

### Steps to Reproduce
1. `terraform apply` with logging_bigquery without private_key

**Comment by sakajunquality** [comment]
Now it's GA
https://www.fastly.com/blog/easy-secrets-free-iam-authentication-for-google-bigquery-cloud-storage-and

**Comment by Integralist** [comment]
Hi @sakajunquality 

I believe support was added in version 3.0.0 of the provider (released November 2022):
https://github.com/fastly/terraform-provider-fastly/releases/tag/v3.0.0

**Comment by Integralist** [comment]
Closing this issue for now. Feel free to continue the conversation if there are issues. Thanks.
