### ISSUE TITLE
[Feature request] Support `project_id` on `logging_gcs` block of `fastly_service_vcl`

### ISSUE THREAD

**Issue by kuanhn** [fastly/terraform-provider-fastly#636]
### Description
If you selected the IAM Role in configuring logging to the google cloud storage endpoint, along with the service account name, the project_id field is also required.
Currently, in the `logging_gcs` block of `fastly_service_vcl,` the project ID field is not defined. I hope this field will be supported soon so I can convert auth without json key.

### Affected Resource(s)
- [logging_gcs](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl#nested-schema-for-logging_gcs) on `fastly_service_vcl`

### References

<img width="960" src="https://user-images.githubusercontent.com/30686391/215999325-2221352a-d08e-4111-a05d-f3838203194e.png">

- https://www.fastly.com/blog/easy-secrets-free-iam-authentication-for-google-bigquery-cloud-storage-and
- https://docs.fastly.com/en/guides/log-streaming-google-cloud-storage#adding-gcs-as-a-logging-endpoint

**Comment by Integralist** [comment]
👋🏻 Thanks for raising this issue @kuanhn.

I've opened a ticket internally to track this for you. I'll report back here once I have any further updates.

**Comment by kuanhn** [comment]
This version has been released so I closed the issue.
https://github.com/fastly/terraform-provider-fastly/blob/main/CHANGELOG.md#431-april-29-2023
