### ISSUE TITLE
Feature Request: HTTP/3 support in Terraform

### ISSUE THREAD

**Issue by hogelschmogel** [fastly/terraform-provider-fastly#637]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Description

When working with VCL services, I'm currently not able to activate HTTP/3 via Terraform but have to use the Web UI. The developer hub suggests that there [already is an available API](https://developer.fastly.com/reference/api/vcl-services/http3/#create-http3) for that.

### Affected Resource(s)

- vcl service

### Expected Behavior

I should be able to control HTTP/3 activation on the vcl service, e.g. as a flag.

**Comment by Integralist** [comment]
Hi @uncloudvernichter 

Thanks for raising this issue. I've opened an internal ticket to track this request and I'll update this issue once I have any further feedback.

**Comment by Integralist** [comment]
Hi @uncloudvernichter 

Just to give you an update, I have a PR open that is waiting a review: 
https://github.com/fastly/terraform-provider-fastly/pull/640

Once approved I'll be able to merge and publish a new minor release.
