### ISSUE TITLE
State for Conditions doesn't seem to be saved or accounted for

### ISSUE THREAD

**Issue by lczxpplnzeey** [fastly/terraform-provider-fastly#65]
terraform versions: 0.10.7 & 0.11.2
fastly: 0.1.4

After successfully running terraform apply, you would expect that running terraform plan right away  have no changes.  But it seems that conditions always needs to be re-modified.  Doing a diff in fastly, shows not difference but a new version is still incremented.

see below for the apply followed by plan
(FQDN replaced with generic)

After successfully running terraform apply, you would expect that running terraform plan right away  have no changes.  But it seems that conditions always needs to be re-modified.  Doing a diff in fastly, shows not difference but a new version is still incremented.

see below for the apply followed by plan
(FQDN replaced with generic)

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fastly_service_v1.dev-example: Modifying... (ID: someID)
  condition.1325525563.name:      "" => "http-condition_www.example.com"
  condition.1325525563.priority:  "" => "103"
  condition.1325525563.statement: "" => "!req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\""
  condition.1325525563.type:      "" => "request"
  condition.1491153257.name:      "" => "response_condition apex redirect to www"
  condition.1491153257.priority:  "" => "10"
  condition.1491153257.statement: "" => "req.http.host == \"example.com\""
  condition.1491153257.type:      "" => "request"
  condition.1556405024.name:      "http-condition_testz.example.com" => ""
  condition.1556405024.priority:  "100" => "0"
  condition.1556405024.statement: "!req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\"" => ""
  condition.1556405024.type:      "REQUEST" => ""
  condition.1722969688.name:      "hho-condition_testz.example.com" => ""
  condition.1722969688.priority:  "103" => "0"
  condition.1722969688.statement: "req.http.Host ~ \"testz.example.com\"" => ""
  condition.1722969688.type:      "REQUEST" => ""
  condition.1918102658.name:      "" => "response_condition redirect to testz"
  condition.1918102658.priority:  "" => "10"
  condition.1918102658.statement: "" => "req.http.host == \"www.example.com\""
  condition.1918102658.type:      "" => "request"
  condition.2400079878.name:      "response_condition redirect to testz" => ""
  condition.2400079878.priority:  "10" => "0"
  condition.2400079878.statement: "req.http.host == \"www.example.com\"" => ""
  condition.2400079878.type:      "REQUEST" => ""
  condition.2520921681.name:      "response_condition_redirect www.example.com" => ""
  condition.2520921681.priority:  "10" => "0"
  condition.2520921681.statement: "req.http.host == \"www.example.com\" && resp.status == 301" => ""
  condition.2520921681.type:      "RESPONSE" => ""
  condition.2616185564.name:      "" => "hho-condition_testz.example.com"
  condition.2616185564.priority:  "" => "103"
  condition.2616185564.statement: "" => "req.http.Host ~ \"testz.example.com\""
  condition.2616185564.type:      "" => "request"
  condition.2711185316.name:      "" => "http-condition_testz.example.com"
  condition.2711185316.priority:  "" => "100"
  condition.2711185316.statement: "" => "!req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\""
  condition.2711185316.type:      "" => "request"
  condition.2780597741.name:      "response_condition apex redirect to www" => ""
  condition.2780597741.priority:  "10" => "0"
  condition.2780597741.statement: "req.http.host == \"example.com\"" => ""
  condition.2780597741.type:      "REQUEST" => ""
  condition.2859898404.name:      "response_condition_redirect example.com" => ""
  condition.2859898404.priority:  "10" => "0"
  condition.2859898404.statement: "req.http.host == \"example.com\" && resp.status == 301" => ""
  condition.2859898404.type:      "RESPONSE" => ""
  condition.2992395967.name:      "http-condition_www.example.com" => ""
  condition.2992395967.priority:  "103" => "0"
  condition.2992395967.statement: "!req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\"" => ""
  condition.2992395967.type:      "REQUEST" => ""
  condition.3487387107.name:      "hho-condition_www.example.com" => ""
  condition.3487387107.priority:  "106" => "0"
  condition.3487387107.statement: "req.http.Host ~ \"www.example.com\"" => ""
  condition.3487387107.type:      "REQUEST" => ""
  condition.3587876867.name:      "" => "response_condition_redirect example.com"
  condition.3587876867.priority:  "" => "10"
  condition.3587876867.statement: "" => "req.http.host == \"example.com\" && resp.status == 301"
  condition.3587876867.type:      "" => "response"
  condition.3709459421.name:      "" => "https-condition_testz.example.com"
  condition.3709459421.priority:  "" => "101"
  condition.3709459421.statement: "" => "req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\""
  condition.3709459421.type:      "" => "request"
  condition.388083011.name:       "" => "https-condition_www.example.com"
  condition.388083011.priority:   "" => "104"
  condition.388083011.statement:  "" => "req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\""
  condition.388083011.type:       "" => "request"
  condition.3924691062.name:      "" => "response_condition_redirect www.example.com"
  condition.3924691062.priority:  "" => "10"
  condition.3924691062.statement: "" => "req.http.host == \"www.example.com\" && resp.status == 301"
  condition.3924691062.type:      "" => "response"
  condition.3933999559.name:      "https-condition_www.example.com" => ""
  condition.3933999559.priority:  "104" => "0"
  condition.3933999559.statement: "req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\"" => ""
  condition.3933999559.type:      "REQUEST" => ""
  condition.541353817.name:       "https-condition_testz.example.com" => ""
  condition.541353817.priority:   "101" => "0"
  condition.541353817.statement:  "req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\"" => ""
  condition.541353817.type:       "REQUEST" => ""
  condition.847311207.name:       "" => "hho-condition_www.example.com"
  condition.847311207.priority:   "" => "106"
  condition.847311207.statement:  "" => "req.http.Host ~ \"www.example.com\""
  condition.847311207.type:       "" => "request"
fastly_service_v1.dev-example: Still modifying... (ID: someID, 10s elapsed)
fastly_service_v1.dev-example: Modifications complete after 16s (ID: someID)

**Apply complete! Resources: 0 added, 1 changed, 0 destroyed.**

**Plan**
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

fastly_service_v1.dev-example: Refreshing state... (ID: someID)
dyn_record.testz-example-com: Refreshing state... (ID: 328664909)
dyn_record.example-com_3: Refreshing state... (ID: 328879903)
dyn_record.example-com_1: Refreshing state... (ID: 328879912)
dyn_record.example-com_2: Refreshing state... (ID: 328879911)
dyn_record.testz-example-com-cdn-example-net: Refreshing state... (ID: 328664920)
dyn_record.www-example-com: Refreshing state... (ID: 328664913)
dyn_record.www-example-com-cdn-example-net: Refreshing state... (ID: 328664919)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ fastly_service_v1.dev-example
      condition.1325525563.name:      "" => "http-condition_www.example.com"
      condition.1325525563.priority:  "" => "103"
      condition.1325525563.statement: "" => "!req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\""
      condition.1325525563.type:      "" => "request"
      condition.1491153257.name:      "" => "response_condition apex redirect to www"
      condition.1491153257.priority:  "" => "10"
      condition.1491153257.statement: "" => "req.http.host == \"example.com\""
      condition.1491153257.type:      "" => "request"
      condition.1556405024.name:      "http-condition_testz.example.com" => ""
      condition.1556405024.priority:  "100" => "0"
      condition.1556405024.statement: "!req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\"" => ""
      condition.1556405024.type:      "REQUEST" => ""
      condition.1722969688.name:      "hho-condition_testz.example.com" => ""
      condition.1722969688.priority:  "103" => "0"
      condition.1722969688.statement: "req.http.Host ~ \"testz.example.com\"" => ""
      condition.1722969688.type:      "REQUEST" => ""
      condition.1918102658.name:      "" => "response_condition redirect to testz"
      condition.1918102658.priority:  "" => "10"
      condition.1918102658.statement: "" => "req.http.host == \"www.example.com\""
      condition.1918102658.type:      "" => "request"
      condition.2400079878.name:      "response_condition redirect to testz" => ""
      condition.2400079878.priority:  "10" => "0"
      condition.2400079878.statement: "req.http.host == \"www.example.com\"" => ""
      condition.2400079878.type:      "REQUEST" => ""
      condition.2520921681.name:      "response_condition_redirect www.example.com" => ""
      condition.2520921681.priority:  "10" => "0"
      condition.2520921681.statement: "req.http.host == \"www.example.com\" && resp.status == 301" => ""
      condition.2520921681.type:      "RESPONSE" => ""
      condition.2616185564.name:      "" => "hho-condition_testz.example.com"
      condition.2616185564.priority:  "" => "103"
      condition.2616185564.statement: "" => "req.http.Host ~ \"testz.example.com\""
      condition.2616185564.type:      "" => "request"
      condition.2711185316.name:      "" => "http-condition_testz.example.com"
      condition.2711185316.priority:  "" => "100"
      condition.2711185316.statement: "" => "!req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\""
      condition.2711185316.type:      "" => "request"
      condition.2780597741.name:      "response_condition apex redirect to www" => ""
      condition.2780597741.priority:  "10" => "0"
      condition.2780597741.statement: "req.http.host == \"example.com\"" => ""
      condition.2780597741.type:      "REQUEST" => ""
      condition.2859898404.name:      "response_condition_redirect example.com" => ""
      condition.2859898404.priority:  "10" => "0"
      condition.2859898404.statement: "req.http.host == \"example.com\" && resp.status == 301" => ""
      condition.2859898404.type:      "RESPONSE" => ""
      condition.2992395967.name:      "http-condition_www.example.com" => ""
      condition.2992395967.priority:  "103" => "0"
      condition.2992395967.statement: "!req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\"" => ""
      condition.2992395967.type:      "REQUEST" => ""
      condition.3487387107.name:      "hho-condition_www.example.com" => ""
      condition.3487387107.priority:  "106" => "0"
      condition.3487387107.statement: "req.http.Host ~ \"www.example.com\"" => ""
      condition.3487387107.type:      "REQUEST" => ""
      condition.3587876867.name:      "" => "response_condition_redirect example.com"
      condition.3587876867.priority:  "" => "10"
      condition.3587876867.statement: "" => "req.http.host == \"example.com\" && resp.status == 301"
      condition.3587876867.type:      "" => "response"
      condition.3709459421.name:      "" => "https-condition_testz.example.com"
      condition.3709459421.priority:  "" => "101"
      condition.3709459421.statement: "" => "req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\""
      condition.3709459421.type:      "" => "request"
      condition.388083011.name:       "" => "https-condition_www.example.com"
      condition.388083011.priority:   "" => "104"
      condition.388083011.statement:  "" => "req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\""
      condition.388083011.type:       "" => "request"
      condition.3924691062.name:      "" => "response_condition_redirect www.example.com"
      condition.3924691062.priority:  "" => "10"
      condition.3924691062.statement: "" => "req.http.host == \"www.example.com\" && resp.status == 301"
      condition.3924691062.type:      "" => "response"
      condition.3933999559.name:      "https-condition_www.example.com" => ""
      condition.3933999559.priority:  "104" => "0"
      condition.3933999559.statement: "req.http.Fastly-SSL && req.http.Host ~ \"^www.example.com\"" => ""
      condition.3933999559.type:      "REQUEST" => ""
      condition.541353817.name:       "https-condition_testz.example.com" => ""
      condition.541353817.priority:   "101" => "0"
      condition.541353817.statement:  "req.http.Fastly-SSL && req.http.Host ~ \"^testz.example.com\"" => ""
      condition.541353817.type:       "REQUEST" => ""
      condition.847311207.name:       "" => "hho-condition_www.example.com"
      condition.847311207.priority:   "" => "106"
      condition.847311207.statement:  "" => "req.http.Host ~ \"www.example.com\""
      condition.847311207.type:       "" => "request"

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

**Comment by samijaber** [comment]
I am stumbling on this issue as well. My Fastly conditions keep re-triggering changes. I can reproduce by simply running `terraform apply` and following it up with `terraform plan` right away without any changes. Here's an example of the output of `terraform plan`:

```
condition.4148483447.name:      "" => "is-rails-endpoint-2"
condition.4148483447.priority:  "" => "1"
condition.4148483447.statement: "" => "(req.url~\"^/events/*\")"
condition.4148483447.type:      "" => "REQUEST"
condition.437050853.name:       "is-rails-endpoint-2" => ""
condition.437050853.priority:   "1" => "0"
condition.437050853.statement:  "(req.url~\"^/events/*\")" => ""
condition.437050853.type:       "REQUEST" => ""
```

Essentially, a new condition with a new ID is being created for no reason. This happens to all conditions in my configuration every time I run `terraform plan`.

**Comment by msuterski** [comment]
The way the Fastly's TF provider works is that if any of the defined sub-resources (like `conditions`) in your `.tf` files does not match the state file (that is refreshed on each TF run), all of those sub-resources are going to be re-generated. In your case all of the conditions are being re-created even though maybe only one of them changed. So, if at least one of your conditions' definition does not match exactly what was returned from Fastly's API, all of them are going to be re-created.

To not have this happening, your TF config needs to define values exactly as they are being returned from Fastly's API. This includes default values if they are not the same between TF and Fastly and/or string value case. E.g. if you look at your TF output, all your conditions that are being dropped have 

`type: "REQUEST"`

but the ones that are being created are

`type: "request"`

**Comment by samijaber** [comment]
@msuterski Thanks for pointing me in the right direction! Your comment about the condition `type` was inaccurate: the value is capitalized in both my configuration and the Fastly API output. Your explanation of how values need to match exactly got me digging, and I found the culprit: multi-line strings. Here is what my `statement` values actually look like in the config:

```tf
statement = <<EOF
(req.url~"^/events/*")||
(req.url~"^/faq/*")
EOF
```

The output stored in the state file includes slashes that escape the double quotes, which seem to cause the discrepancy...I converted the statement from a multi-line string to a normal one (which forces me to manually escape the quotes) and it fixed my problem! However, my statements are very long and unreadable if I put them all on one line. Is there any way to use multi-line strings for Fastly's condition statements without running into this issue?

**Comment by msuterski** [comment]
@samijaber good to hear that you found the problem. My reference about case-sensitivity was mostly for @lczxpplnzeey.

I don't know how to deal with the multiline strings, though. If your statements are repeating a lot of the same (like your example) you could group the regex like

`statement = "req.url~\"^/(events|faq)/*)\""`

**Comment by samijaber** [comment]
@msuterski That makes sense! I thought you were replying to my comment.

I went ahead and simplified my regex so it's more readable on a single line, and called it a day. That'll do for now on my end, but it seems like there's a deeper problem with how the Fastly provider compares multi-line strings with the output!

**Comment by lczxpplnzeey** [comment]
@msuterski 

Is this a bug?  I tried changing it to caps and get this error:

* fastly_service_v1.dev-example.com: Fastly Header type is case sensitive and must be one of 'request', 'fetch', 'cache', or 'response'; found: RESPONSE

And looking at my old configs, they are set to lower case response/request.

I don't know where this is being changed or set to all caps, other than terraform when it's applying it.

Of note, I'm still on terraform v0.10.7 and fastly 0.1.4

**Comment by lczxpplnzeey** [comment]
dug further, below is a snippet of my terraform plan:

condition {
	  name = "http-https-condition_www.example.com"
	  type = "request"
	  statement = "req.http.Host ~ \"^www.example.com\""
	  priority = 514
  }

and here's the state file for it:

                            "condition.1253740285.name": "http-https-condition_www.example.com",
                            "condition.1253740285.priority": "514",
                            "condition.1253740285.statement": "req.http.Host ~ \"^www.exmple.com\"",
                            "condition.1253740285.type": "REQUEST",


So it looks like you are right that they're not matching.  
But I can't capitalize it to match.

**Comment by msuterski** [comment]
@lczxpplnzeey I was referring to `conditions`, not `headers`.

**Comment by lczxpplnzeey** [comment]
@msuterski Let me redo my conditions then to match and thanks for quick reply

**Comment by lczxpplnzeey** [comment]
Yep that fixed it.

Thanks.
