### ISSUE TITLE
Bad request with `force_delete` on a TLS subscription

### ISSUE THREAD

**Issue by sjparkinson** [fastly/terraform-provider-fastly#653]
I've tried to replace a TLS subscription and encountered an unexpected 400 Bad Request error given the use of `force_delete` in the configuration.

Might just be a misunderstanding on when we have to add `force_destroy` in reviewing this issue, but I'm not sure.

### Terraform Version

Terraform v1.3.9
on darwin_arm64

### Affected Resource(s)

- `fastly_tls_subscription`

### Terraform Configuration Files

Before:

```hcl
resource "fastly_tls_subscription" "cert" {
  domains = [
    "example.com",
  ]
  certificate_authority = "lets-encrypt"
  configuration_id      = data.fastly_tls_configuration.tls_1_3_0rtt.id
}
```

After:

```hcl
resource "fastly_tls_subscription" "cert" {
  domains = [
    "example.com",
  ]
  certificate_authority = "certainly"
  configuration_id      = data.fastly_tls_configuration.tls_1_3_0rtt.id
  force_update          = true
  force_destroy         = true

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output

```
terragrunt apply -auto-approve tfplan
fastly_tls_subscription.domain_redirects: Creating...
fastly_tls_subscription.domain_redirects: Creation complete after 2s [id=ESfT5O2Q5ZBvJHAb8eB3Jg]
fastly_tls_subscription.domain_redirects (deposed object e9d60fa1): Destroying... [id=lEAJvcHPQlbi8qw6GHsSRQ]
╷
│ Error: 400 - Bad Request:
│ 
│     Title:  Can't delete subscription
│     Detail: Subscription has active domains
│ 
│ 
╵
ERRO[0002] Terraform invocation failed in /home/circleci/project/terraform/tls 
ERRO[0002] 1 error occurred:
	* exit status 1
          

Exited with code exit status 1
CircleCI received exit code 1
```

Plan:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+/- create replacement and then destroy

Terraform will perform the following actions:

  # fastly_tls_subscription.domain_redirects must be replaced
+/- resource "fastly_tls_subscription" "domain_redirects" {
      ~ certificate_authority   = "lets-encrypt" -> "certainly" # forces replacement
      ~ certificate_id          = "osK9ytjBjE7yK9p7TYMWh2" -> (known after apply)
      ~ common_name             = "example.com" -> (known after apply)
      ~ created_at              = "2023-03-01T15:59:24Z" -> (known after apply)
      ~ force_destroy           = false -> true
      ~ force_update            = false -> true
      ~ id                      = "lEAJvcHPQlbi8qw6GHsSRQ" -> (known after apply)
      ```
```

### Expected Behavior

The TLS subscription should have successfully been deleted.

### Actual Behavior

The new TLS subscription was created successfully, but the existing subscription was not deleted.

**Comment by Integralist** [comment]
Hi @sjparkinson 

So just to clarify that you're trying to switch from one CA (lets-encrypt) to another (certainly) and you encountered and error saying you were not able to delete the TLS subscription because there was active domains attached to it. 

At that point you added the attributes `force_update` and `force_destroy` because (as per [the documentation](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/tls_subscription#force_update)) you understood them to be required for this type of change. But in adding those it didn't help and you still saw the same error.

Is that correct?

Additionally, you mentioned the new TLS Subscription had been created but the existing TLS Subscription was of course still in place. Did that introduce a break in your environment?

**Comment by Integralist** [comment]
Interestingly the `force_destroy` attribute looks to be an undocumented API feature.

If I look at the API documentation for [deleting a TLS Subscription](https://developer.fastly.com/reference/api/tls/subs/#delete-tls-sub) I don't see anything related to 'force'.

I can see that we expose a `Force` struct field in our go-fastly API client:
https://github.com/fastly/terraform-provider-fastly/blob/main/fastly/resource_fastly_tls_subscription.go#L360

Which in turn adds `?force=true` to the API endpoint:
- https://github.com/fastly/go-fastly/blob/5271fecdb32734c33e91306bd5dc0d6fec11b771/fastly/tls_subscription.go#L291-L293
- https://github.com/fastly/go-fastly/blob/5271fecdb32734c33e91306bd5dc0d6fec11b771/fastly/fixtures/tls_subscription/update.yaml#L15

**Comment by sjparkinson** [comment]
> So just to clarify that you're trying to switch from one CA (lets-encrypt) to another (certainly) and you encountered and error saying you were not able to delete the TLS subscription because there was active domains attached to it.
> 
> At that point you added the attributes `force_update` and `force_destroy` because (as per [the documentation](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/tls_subscription#force_update)) you understood them to be required for this type of change. But in adding those it didn't help and you still saw the same error.
> 
> Is that correct?

Not quite, I added the two attributes at the same time as the CA swap, assuming that they would be needed in order to delete the resource.

> Additionally, you mentioned the new TLS Subscription had been created but the existing TLS Subscription was of course still in place. Did that introduce a break in your environment?

No break in the environment as far as I'm aware, as I was left with two subscriptions for the same set of domains. Easy enough to clean up manually.

Edit: I was also willing to accept a bit of downtime as part of this change given the new subscription was unlikely to be deployed before the old one was deleted.

**Comment by Integralist** [comment]
> Edit: I was also willing to accept a bit of downtime as part of this change given the new subscription was unlikely to be deployed before the old one was deleted.

👍🏻 Yup agreed a migration such as this was always going to be tricky 🙂 

OK, I'll dig into this on Monday (as tomorrow, Friday,  is a 'wellness day' for the company).

**Comment by Integralist** [comment]
👋🏻 @sjparkinson 

I configured TLS on an apex domain (and a subdomain) with Lets-Encrypt. 

I then migrated to Certainly, which involved me just changing the TF config from `certificate_authority = "lets-encrypt"` to `certificate_authority = "certainly"`. This process was successful and I didn't see any "Can't delete subscription" errors.

Now one thing to note is that when I create TLS using Lets-Encrypt I had both these attributes set:

```
force_destroy = true
force_update  = true
```

Could you run `terraform show` and see what the `fastly_tls_subscription` resource has defined in its internal state (I'm interested to know if those attributes are reflecting your config, e.g. are set to true or not).

Maybe you could try applying those attributes first, before then trying to apply a change to the `certificate_authority` attribute. Now I'm not entirely sure why that would make any difference but at this point in time I'm unable to replicate the issue you've had in migrating between the CAs.

> **NOTE:** One confusion I had was that my browser was still showing me the cert issued by Lets-Encrypt, and only when opening an incognito browser session could I get it to show the Certainly cert. Maybe that is a very obvious/common browser caching thing, but if it is I was not aware of it and have reached out (internally) to our TLS team to enquire about that behaviour.

Let me know if the suggested 'two-step' process makes any difference for you.

Thanks!

**Comment by sjparkinson** [comment]
> I then migrated to Certainly, which involved me just changing the TF config from `certificate_authority = "lets-encrypt"` to `certificate_authority = "certainly"`. This process was successful and I didn't see any "Can't delete subscription" errors.
> 
> Now one thing to note is that when I create TLS using Lets-Encrypt I had both these attributes set

I suspect this is it. I've lost the state and the service is all migrated at this point. My approach was to only add these attributes when also applying the change to `certificate_authority`. My guess is `force_destroy = true` needs to have been applied earlier that I was expecting in order for it to work.

I was running with the assumption of if I added that attribute at the same time as another change that would result in a destroy then the `force` param would be added.

**Comment by Integralist** [comment]
OK, thanks for the update. In that case, I'll close off this issue now. If you need to continue the discussion then please comment again or re-open the issue if you need to. Thanks!
