### ISSUE TITLE
gzip should use default extensions and content_types

### ISSUE THREAD

**Issue by jrynyt** [fastly/terraform-provider-fastly#66]
### Terraform Version
v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- fastly_service_v1

### Terraform Configuration Files
```hcl
resource "fastly_service_v1" "service" {
...
  gzip {
    name = "gzip_settings"
  }
}
```

### Expected Behavior
If in a `gzip` block you don't provide `extensions` and `content_types`, which are listed as optional, you should get the defaults as described in https://docs.fastly.com/guides/basic-configuration/enabling-automatic-gzipping, not nothing. The [Fastly API reference](https://docs.fastly.com/api/config#gzip) also says of these fields: "If you omit this field a default list will be used."

### Actual Behavior
If you don't include `extensions` and `content_types`, Fastly produces this VCL (notice the regexes):
```
if ((beresp.status == 200 || beresp.status == 404) && (beresp.http.content-type ~ "^()\s*($|;)" || req.url ~ "\.()($|\?)" ) ) {
```

**Comment by chadgrant** [comment]
This is still an issue. Updating the docs would help

**Comment by JoshMock** [comment]
I just discovered a `gzip` block with no `extensions` or `content_types` does nothing. Having some way to trigger Fastly's default gzip policy would be a very helpful enhancement. If that's not reasonable, improving the docs to make it clear how the `gzip` block actually works is needed.
