### ISSUE TITLE
[Feature request] Support config store

### ISSUE THREAD

**Issue by mike-carey** [fastly/terraform-provider-fastly#701]
### Description

Fastly's config store is not currently a resource that can be managed by terraform.

### Affected Fastly Terraform Resource(s)

- `fastly_service_compute`

### Resources

![image](https://github.com/fastly/terraform-provider-fastly/assets/32496966/1f4a40a9-6584-4557-9900-576b55bb05dc)
<img width="1432" alt="image" src="https://github.com/fastly/terraform-provider-fastly/assets/32496966/92db8ca6-5168-454e-bebc-fffe10547ddc">

- https://developer.fastly.com/reference/cli/config-store/
- https://www.fastly.com/blog/introducing-config-store-storing-and-updating-configuration-data-at-the-edge
- https://docs.fastly.com/en/guides/working-with-config-stores

**Comment by Integralist** [comment]
Hi @mike-carey 

Thanks for opening this issue. 

Just to let you know that we have an internal ticket tracking this work, and although I can't give an exact ETA for when it'll be in a new release, we should hopefully be starting on the implementation soon.

**Comment by Integralist** [comment]
This feature was implemented and released in:
https://github.com/fastly/terraform-provider-fastly/releases/tag/v5.1.0

Docs:
- https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/configstore
- https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/configstore_entries
