### ISSUE TITLE
Configure BigQuery logging endpoint through terraform.

### ISSUE THREAD

**Issue by kf6nux** [fastly/terraform-provider-fastly#72]
### Affected Resource(s)
- fastly_service_v1

### Feature Request
Configure logging endpoint for BigQuery through terraform.

### Important Factoids
fastly_service_v1 currently supports endpoints:
- S3 Buckets
- Papertrail
- Sumologic
- GCS (Google Cloud Storage)
- syslog
- logentries

Additional endpoints offered by Fastly but unhandled in fastly_service_v1 appear to be:
- BigQuery
- Spacess (Digital Ocean)
- ftp
- Heroku Logplex
- loggly
- Scalyr

### References
I couldn't find any GitHub issues or PRs in either this repo or elsewhere regarding this feature. 

Here are Fastly's docs on their supported logging endpoints: https://docs.fastly.com/guides/streaming-logs/setting-up-remote-log-streaming

Here are the Terraform docs I landed on when looking for BigQuery logging support: https://www.terraform.io/docs/providers/fastly/r/service_v1.html

**Comment by giorgiosironi** [comment]
We will try to workaround the lack of BigQuery support by using GoogleCloud Storage instead.

**Comment by phamann** [comment]
This was fixed in #80 and released in v0.3.0

**Comment by radeksimko** [comment]
Thanks for the note @phamann , closing.
