### ISSUE TITLE
Unable to set backend ssl_ciphers

### ISSUE THREAD

**Issue by jeff-lee** [fastly/terraform-provider-fastly#73]
### Terraform Version
$ tf --version
Terraform v0.11.7
+ provider.fastly v0.1.4

### Affected Resource(s)
- fastly_service_v1.backend

### Terraform Configuration Files
```hcl
provider "fastly" {
  api_key = "${ var.fastly_token }"
}

resource "fastly_service_v1" "test-cipher" {
  name        = "test-cipher"

  domain    { name = "${ var.domain }" }

  backend {
    name                = "test-cipher"
    address             = "${ var.backend_addr }"
    port                = 443
    use_ssl             = true
    ssl_cert_hostname   = "${ var.cert_hostname }"
    ssl_ca_cert         = "${ var.ca_cert }"
    min_tls_version     = "1.2"
    max_tls_version     = "1.2"
    ssl_ciphers         = "ECDHE-RSA-AES128-GCM-SHA256"
  }

  force_destroy = true
}
```

### Debug Output
https://gist.github.com/jeff-lee/caddc2e6abb6a2f39a7b73adf5945194

### Expected Behavior
The backend should be configured with the specified ssl ciphers

### Actual Behavior
The backend was created with null ssl ciphers

### Steps to Reproduce
1. `terraform apply`

**Comment by thommahoney** [comment]
This appears to be a bug in the sethvargo/go-fastly library. It is encoding the data incorrectly eg.

```
ssl_ciphers%7C0=ECDHE-RSA-AES128-GCM-SHA256
```

(`%7C` is `|`)

**Comment by smaeda-ks** [comment]
Closing as I believe this was already fixed since then.
