### ISSUE TITLE
Failure to activate a new version cannot be recovered from

### ISSUE THREAD

**Issue by giorgiosironi** [fastly/terraform-provider-fastly#74]
### Terraform Version
`Terraform v0.11.5`

### Affected Resource(s)
Please list the resources as a list, for example:
- `fastly_service_v1`

### Terraform Configuration Files
```hcl
{
  "resource": {
    "fastly_service_v1": {
      "fastly-cdn": {
        "domain": [
          {
            "name": "continuumtest--cdn-iiif.elifesciences.org"
          }
        ],
        "force_destroy": true,
        "name": "iiif--continuumtest",
        "backend": {
          "name": "iiif--continuumtest",
          "ssl_check_cert": true,
          "ssl_cert_hostname": "continuumtest--iiif.elifesciences.org",
          "address": "continuumtest--iiif.elifesciences.org",
          "use_ssl": true,
          "port": 443
        }
      }
    }
  }
}
```

Last Friday, some connection problem caused a timeout in an API call, at some point between the `Version` creation and its activation. I initially ignored this and restarted `terraform apply`, so I don't have logs about this failure.

### Expected Behavior

The existing version should have been activated.

### Actual Behavior

<img src="https://screenshotscdn.firefoxusercontent.com/images/a22f7fab-80ab-4f3d-834d-53eefa493a4f.png" />

The step on the top is me enabling the version manually from the control panel. Executing `terraform apply` with a deactivated version seems to not cause any change to happen.

### Steps to Reproduce

1. `terraform apply`
2. Interrupt after version creation but before it is enabled. I'll try also to deactivate it from the control panel on fastly.com
3. `terraform apply` again, should ignore the deactivated state assuming this is fine.

It is also possible the version has been deactivated for some reason, but I cannot find that event in the control panel which makes the case for it never being activated.

**Comment by giorgiosironi** [comment]
I can confirm that it suffices to get to this state:
<img src="https://screenshotscdn.firefoxusercontent.com/images/1121c0e9-28d0-48d4-874b-747e6746d8e1.png" />
and `terraform apply` then leaves the deactivated version in place. Perhaps I'm missing something in my resource definition that maps to that state.

**Comment by smaeda-ks** [comment]
This issue seems to be stale. I'm going to close this as I don't think this is the case with the latest version.
