### ISSUE TITLE
Slashes in Condition Names cause 404s when modifying

### ISSUE THREAD

**Issue by lczxpplnzeey** [fastly/terraform-provider-fastly#82]
terraform versions: 0.10.7 & 0.11.7
fastly provider: 0.1.4

when you create a response condition name with slashes:

response_object {
        **name = "301 response for www.example.com/some/path"**
        status = 301
        request_condition = "response_condition_redirect for www.example.com/some/path"
}

and then try to make a change to it from 301 to 302

response_object {
        name = "301 response for www.example.com/some/path"
        **status = 302**
        request_condition = "response_condition_redirect for www.example.com/some/path"
}

You get a terraform error:

fastly_service_v1.some-website: 1 error(s) occurred:
fastly_service_v1.some-website: 404 - Not Found

Even though the service ID is valid and works.

Likely related to https://github.com/sethvargo/go-fastly/pull/66

So it looks like you can create the conditions with slashes but you can not modify it afterwards.

**Comment by lczxpplnzeey** [comment]
This turns out due to the fact that the names of the conditions have slashes "/" in them.


condition {
	  name = "response_condition_redirect for example.com/somepath"
	  type = "request"
	  statement = "req.http.host == \"example.com\""
  }

**Comment by cransom** [comment]
I found something similar where a `/` in the name attribute of a `request_setting` also triggered a 404.

**Comment by philippschulte** [comment]
This was solved by #154.
