### ISSUE TITLE
Healthcheck parameter set to default value in state

### ISSUE THREAD

**Issue by ncaunt-sr** [fastly/terraform-provider-fastly#87]
When setting the `initial` field of a healthcheck to 0, Fastly does not update its configuration and TF sets its default value for that field in its remote state. A subsequent plan describes the healthcheck as having changed because of this and attempts to set it back to the value in the TF config.

I'm not sure if 0 is an acceptable value to Fastly for the `initial` field of a healthcheck (hence it not updating its config), but I am confused about why the provider has stored the default value in its state.

### Terraform Version
Terraform v0.11.7
+ provider.external v1.0.0
+ provider.fastly v0.2.0
+ provider.google v1.16.2

### Affected Resource(s)
- fastly.fastly_service_v1

### Expected Behavior
The `initial` field of the healthcheck was expected to be set to 0 when applying the configuration.

### Actual Behavior
When applying, the `initial` field of the healthcheck was left at its previous value by Fastly (1) and the TF remote state records it as being 2, which is the default value for this field in the provider. TF reports no problems occurred.

### Output of `terraform apply`
```
  healthcheck.3168930295.check_interval:    "5000" => "0"
  healthcheck.3168930295.expected_response: "200" => "0"
  healthcheck.3168930295.host:              "xxx" => ""
  healthcheck.3168930295.http_version:      "1.1" => ""
  healthcheck.3168930295.initial:           "1" => "0"
  healthcheck.3168930295.method:            "HEAD" => ""
  healthcheck.3168930295.name:              "xxx" => ""
  healthcheck.3168930295.path:              "/xxx" => ""
  healthcheck.3168930295.threshold:         "2" => "0"
  healthcheck.3168930295.timeout:           "5000" => "0"
  healthcheck.3168930295.window:            "5" => "0"
  healthcheck.3592920224.check_interval:    "" => "5000"
  healthcheck.3592920224.expected_response: "" => "200"
  healthcheck.3592920224.host:              "" => "xxx"
  healthcheck.3592920224.http_version:      "" => "1.1"
  healthcheck.3592920224.initial:           "" => "0"
  healthcheck.3592920224.method:            "" => "HEAD"
  healthcheck.3592920224.name:              "" => "xxx"
  healthcheck.3592920224.path:              "" => "/xxx"
  healthcheck.3592920224.threshold:         "" => "2"
  healthcheck.3592920224.timeout:           "" => "5000"
  healthcheck.3592920224.window:            "" => "5"
```

### Output of subsequent `terraform plan`
```
      healthcheck.3592920224.check_interval:    "" => "5000"
      healthcheck.3592920224.expected_response: "" => "200"
      healthcheck.3592920224.host:              "" => "xxx"
      healthcheck.3592920224.http_version:      "" => "1.1"
      healthcheck.3592920224.initial:           "" => "0"
      healthcheck.3592920224.method:            "" => "HEAD"
      healthcheck.3592920224.name:              "" => "xxx"
      healthcheck.3592920224.path:              "" => "/xxx"
      healthcheck.3592920224.threshold:         "" => "2"
      healthcheck.3592920224.timeout:           "" => "5000"
      healthcheck.3592920224.window:            "" => "5"
      healthcheck.61650446.check_interval:      "5000" => "0"
      healthcheck.61650446.expected_response:   "200" => "0"
      healthcheck.61650446.host:                "xxx" => ""
      healthcheck.61650446.http_version:        "1.1" => ""
      healthcheck.61650446.initial:             "2" => "0"
      healthcheck.61650446.method:              "HEAD" => ""
      healthcheck.61650446.name:                "xxx" => ""
      healthcheck.61650446.path:                "/xxx" => ""
      healthcheck.61650446.threshold:           "2" => "0"
      healthcheck.61650446.timeout:             "5000" => "0"
      healthcheck.61650446.window:              "5" => "0"
```

**Comment by Integralist** [comment]
Thank you for taking the time to open this issue.

I appreciate this was reported a long time ago (and I appreciate your patience awaiting our feedback) but I believe we may now have a fix in place to resolve the issue you're describing. We merged it this morning as the new minor version `v0.21.3`, here are some details about the changes:

- [Migrate Terraform provider to use latest Go-Fastly 2.0.0 release](https://github.com/fastly/terraform-provider-fastly/releases/tag/v0.21.3).
- [Key changes in Go-Fastly 2.0.0](https://github.com/fastly/terraform-provider-fastly/issues/85) that I think relate to this issue.

If possible, could you try upgrading to the latest version (`v0.21.3`) and let me know if this indeed resolves the issue.

Thanks again.

**Comment by smaeda-ks** [comment]
should be fixed in https://github.com/fastly/terraform-provider-fastly/pull/511
