### ISSUE TITLE
Support log streaming integration with GrafanaCloud

### ISSUE THREAD

**Issue by omelnyk1** [fastly/terraform-provider-fastly#891]
Hello team 👋

Recently you released log streaming integration with GrafanaCloud. The documentation is available [here](https://docs.fastly.com/en/guides/log-streaming-grafana-cloud-logs).
Could you please also update resource [fastly_service_vcl](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl) in terraform provider to support this functionality?

Thank you.

**Comment by mdenomy** [comment]
Hi @omelnyk1 we are working to add that now

**Comment by omelnyk1** [comment]
Hello @mdenomy 
Thank you for reply. Do you guys have the date for new release?

**Comment by mdenomy** [comment]
Hi @omelnyk1. Those changes, and the cli, were released yesterday
