### ISSUE TITLE
Terraform apply fails with "Record not found / Cannot find 'service'"

### ISSUE THREAD

**Issue by sansb** [fastly/terraform-provider-fastly#91]
Hi there,

I hope this counts as a bug report and not a general help question. I am trying to create a Fastly service with Terraform. When I run `terraform apply`, Terraform fails with an error that does not tell me what is wrong.

### Terraform Version
Terraform v0.11.8
+ provider.fastly v0.3.0

### Affected Resource(s)
- fastly_service_v1

### Terraform Configuration Files
```hcl
provider "fastly" {
  api_key = "hunter2"
}
resource "fastly_service_v1" "app" {
  name = "app"

  domain {
    name    = "app.amitree-staging.com"
    comment = "demo"
  }
}
```

### Debug Output
https://gist.github.com/sansb/47f860b46dd1250045d1d68bb590c70d

### Expected Behavior
If the build fails, Terraform should tell me why

### Actual Behavior
Terraform prints this:
```
* fastly_service_v1.app: 404 - Not Found:

    Title:  Record not found
    Detail: Cannot find 'service'
```

### Steps to Reproduce
Run `terraform apply`

**Comment by lanej** [comment]
It's possible this is fixed by #89.

@thommahoney should we output the Fastly API client log when `TF_LOG=debug`?

**Comment by sansb** [comment]
Outputting the API client log would be super useful, I think, so a user could get better hints about what they're doing wrong.

**Comment by sansb** [comment]
@lanej Thanks for the idea. I found that curling the API directly returns the same unhelpful error message-
```
curl -H "Fastly-Key: hunter2" -H "Accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -X POST -F "name=test-service" https://api.fastly.com/service
{"msg":"Record not found","detail":"Cannot find 'service'"}
```

So I will file a ticket with Fastly and close this ticket. Thank you.

**Comment by alvin-huang** [comment]
@sansb It's been a few months so I am sure you resolved the issue with Fastly but I recently ran into this myself. Turns out the reason was I was using an API token that was scoped to one service and it didn't allow me to create a new service.

It seems like you need a global token with access to all services to create a new service (not ideal). The scope description of the token that worked is: `global scope. Access to All Services.`
