### ISSUE TITLE
Cannot delete S3 logging endpoint with / in its name

### ISSUE THREAD

**Issue by jwadolowski** [fastly/terraform-provider-fastly#99]
### Terraform Version

```
$ terraform -v
Terraform v0.11.8
+ provider.fastly v0.2.0
```

### Affected Resource(s)

`fastly_service_v1`

### Terraform Configuration Files

```
resource "fastly_service_v1" "dev" {
  name = "prefix/DEV"

  s3logging {
    name             = "prefix/DEV"
    bucket_name      = "fastly-logs"
    # ...
  }
}
```

### Expected Behavior

Properly defined S3 logging endpoint can be deleted without issues.

### Actual Behavior

404 is returned.

### Steps to Reproduce

1. Define Fastly service with S3 logging endpoint named `prefix/xyz` (see example above)
2. Run `terraform apply` - at this stage everything should be fine
3. Delete `s3logging` property from your `*.tf` file
4. Run `terraform apply` again

```
Error: Error applying plan:

1 error(s) occurred:

* fastly_service_v1.dev: 1 error(s) occurred:

* fastly_service_v1.dev: 404 - Not Found
```

### Important Factoids

I've just raised a bug in [go-fastly](https://github.com/sethvargo/go-fastly), as I belive it should be fixed there: https://github.com/sethvargo/go-fastly/issues/91

**Comment by philippschulte** [comment]
This was solved by #154.
